Repository segmentio/action-destinations, pull requests merged in 2023-09, with the labels that each got.

#1507 [STRATCONN-2850] Return transformed payload from Segment Profile Destination
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/create-test-integration.ts
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/types.ts
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/index.ts
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/index.ts
Labels: not-partner-eng-review

#1542 [STRATCONN-3110] Optimizely test credentials timing out
  packages/core/src/create-test-integration.ts
  packages/destination-actions/src/destinations/optimizely-feature-experimentation-actions/index.ts
  packages/destination-actions/src/destinations/optimizely-feature-experimentation-actions/trackEvent/functions.ts
  packages/destination-actions/src/destinations/optimizely-feature-experimentation-actions/trackEvent/index.ts
Labels: not-partner-eng-review

#1533 Add ABsmartly first actions implementation
  packages/destination-actions/src/destinations/absmartly/__tests__/event.test.ts
  packages/destination-actions/src/destinations/absmartly/__tests__/exposure.test.ts
  packages/destination-actions/src/destinations/absmartly/__tests__/goal.test.ts
  packages/destination-actions/src/destinations/absmartly/__tests__/index.test.ts
  packages/destination-actions/src/destinations/absmartly/__tests__/timestamp.test.ts
  packages/destination-actions/src/destinations/absmartly/__tests__/unit.test.ts
  packages/destination-actions/src/destinations/absmartly/attribute.ts
  packages/destination-actions/src/destinations/absmartly/event.ts
  packages/destination-actions/src/destinations/absmartly/exposure.ts
  packages/destination-actions/src/destinations/absmartly/generated-types.ts
  packages/destination-actions/src/destinations/absmartly/goal.ts
  packages/destination-actions/src/destinations/absmartly/index.ts
  packages/destination-actions/src/destinations/absmartly/timestamp.ts
  packages/destination-actions/src/destinations/absmartly/trackExposure/__tests__/index.test.ts
  packages/destination-actions/src/destinations/absmartly/trackExposure/generated-types.ts
  packages/destination-actions/src/destinations/absmartly/trackExposure/index.ts
  packages/destination-actions/src/destinations/absmartly/trackGoal/__tests__/index.test.ts
  packages/destination-actions/src/destinations/absmartly/trackGoal/generated-types.ts
  packages/destination-actions/src/destinations/absmartly/trackGoal/index.ts
  packages/destination-actions/src/destinations/absmartly/unit.ts
Labels: partner-eng-cloud-review

#1544 [TikTok Audiences] Post testing party updates
  packages/destination-actions/src/destinations/tiktok-audiences/addToAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addToAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addUser/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/constants.ts
  packages/destination-actions/src/destinations/tiktok-audiences/createAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-audiences/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeFromAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeFromAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeUser/index.ts
Labels: not-partner-eng-review

#1554 STRATCONN-2967 - Hide internal mappings for LiveRamp
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/generated-types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/generated-types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/index.ts
Labels: not-partner-eng-review

#1555 STRATCONN-3095: Develop new Google Campaign Manager Action Destination
  packages/browser-destinations/destinations/google-campaign-manager/README.md
  packages/browser-destinations/destinations/google-campaign-manager/package.json
  packages/browser-destinations/destinations/google-campaign-manager/src/__tests__/counterActivity.test.ts
  packages/browser-destinations/destinations/google-campaign-manager/src/__tests__/salesActivity.test.ts
  packages/browser-destinations/destinations/google-campaign-manager/src/counterActivity/generated-types.ts
  packages/browser-destinations/destinations/google-campaign-manager/src/counterActivity/index.ts
  packages/browser-destinations/destinations/google-campaign-manager/src/generated-types.ts
  packages/browser-destinations/destinations/google-campaign-manager/src/index.ts
  packages/browser-destinations/destinations/google-campaign-manager/src/salesActivity/generated-types.ts
  packages/browser-destinations/destinations/google-campaign-manager/src/salesActivity/index.ts
  packages/browser-destinations/destinations/google-campaign-manager/src/types.ts
  packages/browser-destinations/destinations/google-campaign-manager/tsconfig.json
  packages/destinations-manifest/package.json
  packages/destinations-manifest/src/index.ts
Labels: browser-destinations, not-partner-eng-review

#1484 Update action tester doc
  docs/actions_tester.md
Labels: not-partner-eng-review

#1527 Add Rupt integration (prev. Sabil)
  packages/browser-destinations/destinations/rupt/README.md
  packages/browser-destinations/destinations/rupt/package.json
  packages/browser-destinations/destinations/rupt/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/rupt/src/attach.types.ts
  packages/browser-destinations/destinations/rupt/src/attach/__tests__/index.test.ts
  packages/browser-destinations/destinations/rupt/src/attach/generated-types.ts
  packages/browser-destinations/destinations/rupt/src/attach/index.ts
  packages/browser-destinations/destinations/rupt/src/generated-types.ts
  packages/browser-destinations/destinations/rupt/src/index.ts
  packages/browser-destinations/destinations/rupt/src/types.ts
  packages/browser-destinations/destinations/rupt/tsconfig.json
Labels: partner-eng-device-review

#1514 [Hubspot Cloud Actions]- Implemented Batching for Upsert Contact
  packages/destination-actions/src/destinations/hubspot/index.ts
  packages/destination-actions/src/destinations/hubspot/upsertContact/__tests__/__helpers__/test-utils.ts
  packages/destination-actions/src/destinations/hubspot/upsertContact/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/hubspot/upsertContact/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertContact/generated-types.ts
  packages/destination-actions/src/destinations/hubspot/upsertContact/index.ts
Labels: not-partner-eng-review

#1559 LaunchDarkly: add enable_batching field to Audiences destination action.
  packages/destination-actions/src/destinations/launchdarkly-audiences/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/launchdarkly-audiences/syncAudience/index.ts
Labels: partner-eng-cloud-review

#1563 Ccp 419
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
Labels: partner-eng-cloud-review

#1547 Optimizely Audiences - fixing bug
  packages/destination-actions/src/destinations/optimizely-advanced-audience-targeting/syncAudience/index.ts
Labels: partner-eng-cloud-review

#1572 [Salesforce Marketing Cloud] Enables bulk batching for RETL, Engage
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/contactDataExtension/generated-types.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/contactDataExtension/index.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/dataExtension/generated-types.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/dataExtension/index.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-properties.ts
Labels: Ready for Release, not-partner-eng-review

#1560 convert and cast predefined phone attributes as numbers
  packages/destination-actions/src/destinations/airship/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/airship/setAttributes/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/airship/setAttributes/generated-types.ts
  packages/destination-actions/src/destinations/airship/setAttributes/index.ts
  packages/destination-actions/src/destinations/airship/utilities.ts
Labels: partner-eng-cloud-review

#1567 Update Attio integration instructions, drop required `name` property
  packages/destination-actions/src/destinations/attio/assertRecord/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/attio/assertRecord/generated-types.ts
  packages/destination-actions/src/destinations/attio/assertRecord/index.ts
  packages/destination-actions/src/destinations/attio/groupWorkspace/generated-types.ts
  packages/destination-actions/src/destinations/attio/groupWorkspace/index.ts
  packages/destination-actions/src/destinations/attio/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/attio/identifyUser/index.ts
Labels: partner-eng-cloud-review

#1558 VWO Web mode hotfix
  packages/browser-destinations/destinations/vwo/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/vwo/src/identifyUser/index.ts
  packages/browser-destinations/destinations/vwo/src/index.ts
  packages/browser-destinations/destinations/vwo/src/trackEvent/index.ts
Labels: partner-eng-device-review

#1543 Pendo Web Actions Destination
  packages/browser-destinations/destinations/pendo-web-actions/README.md
  packages/browser-destinations/destinations/pendo-web-actions/package.json
  packages/browser-destinations/destinations/pendo-web-actions/src/generated-types.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/group/__tests__/index.test.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/group/generated-types.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/group/index.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/identify/__tests__/index.test.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/identify/generated-types.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/identify/index.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/index.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/loadScript.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/track/__tests__/index.test.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/track/generated-types.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/track/index.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/types.ts
  packages/browser-destinations/destinations/pendo-web-actions/tsconfig.json
Labels: partner-eng-cloud-review

#1574 tidying up package.json for 2 Integrations
  packages/browser-destinations/destinations/google-campaign-manager/package.json
  packages/browser-destinations/destinations/pendo-web-actions/package.json
Labels: partner-eng-device-review

#1580 Stratconn 3154 - LiveRamp audiences should emit a proper error message if the SFTP folders are not found
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/sftp.ts
Labels: not-partner-eng-review (cloud)

#1587 Scaffold Klaviyo Destination
  packages/destination-actions/src/destinations/klaviyo/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/index.ts
Labels: not-partner-eng-review (cloud)

#1576 Mass update peerDependencies for browser-destinations to specify supported analytics-next version
  packages/browser-destinations/destinations/adobe-target/package.json
  packages/browser-destinations/destinations/amplitude-plugins/package.json
  packages/browser-destinations/destinations/braze-cloud-plugins/package.json
  packages/browser-destinations/destinations/braze/package.json
  packages/browser-destinations/destinations/commandbar/package.json
  packages/browser-destinations/destinations/friendbuy/package.json
  packages/browser-destinations/destinations/fullstory/package.json
  packages/browser-destinations/destinations/google-analytics-4-web/package.json
  packages/browser-destinations/destinations/google-campaign-manager/package.json
  packages/browser-destinations/destinations/heap/package.json
  packages/browser-destinations/destinations/hubspot-web/package.json
  packages/browser-destinations/destinations/intercom/package.json
  packages/browser-destinations/destinations/iterate/package.json
  packages/browser-destinations/destinations/koala/package.json
  packages/browser-destinations/destinations/logrocket/package.json
  packages/browser-destinations/destinations/pendo-web-actions/package.json
  packages/browser-destinations/destinations/playerzero-web/package.json
  packages/browser-destinations/destinations/ripe/package.json
  packages/browser-destinations/destinations/rupt/package.json
  packages/browser-destinations/destinations/screeb/package.json
  packages/browser-destinations/destinations/segment-utilities-web/package.json
  packages/browser-destinations/destinations/sprig-web/package.json
  packages/browser-destinations/destinations/stackadapt/package.json
  packages/browser-destinations/destinations/tiktok-pixel/package.json
  packages/browser-destinations/destinations/upollo/package.json
  packages/browser-destinations/destinations/userpilot/package.json
  packages/browser-destinations/destinations/vwo/package.json
  packages/browser-destinations/destinations/wisepops/package.json
  packages/cli/templates/destinations/browser/package.json
Labels: not-partner-eng-review (device)

#1565 CUSTINT-20007: segment.com Emarsys destination - remove mandatory fields
  packages/destination-actions/src/destinations/emarsys/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/emarsys/upsertContact/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/emarsys/upsertContact/generated-types.ts
  packages/destination-actions/src/destinations/emarsys/upsertContact/index.ts
Labels: partner-eng-review (cloud)

#1488 Added CDP Resolution Browser Action
  packages/browser-destinations/destinations/cdpresolution/README.md
  packages/browser-destinations/destinations/cdpresolution/package.json
  packages/browser-destinations/destinations/cdpresolution/src/generated-types.ts
  packages/browser-destinations/destinations/cdpresolution/src/index.ts
  packages/browser-destinations/destinations/cdpresolution/src/sync/__tests__/index.test.ts
  packages/browser-destinations/destinations/cdpresolution/src/sync/generated-types.ts
  packages/browser-destinations/destinations/cdpresolution/src/sync/index.ts
  packages/browser-destinations/destinations/cdpresolution/src/types.ts
  packages/browser-destinations/destinations/cdpresolution/tsconfig.json
Labels: partner-eng-review (device)

#1582 [DevRev]: Add new browser destination with a pluging Rev User Enrichment
  packages/browser-destinations/destinations/devrev/README.md
  packages/browser-destinations/destinations/devrev/package.json
  packages/browser-destinations/destinations/devrev/src/generated-types.ts
  packages/browser-destinations/destinations/devrev/src/index.ts
  packages/browser-destinations/destinations/devrev/src/revUserEnrichment/__tests__/index.test.ts
  packages/browser-destinations/destinations/devrev/src/revUserEnrichment/generated-types.ts
  packages/browser-destinations/destinations/devrev/src/revUserEnrichment/index.ts
  packages/browser-destinations/destinations/devrev/tsconfig.json
Labels: partner-eng-review (device)

#1501 [TTD] Add Native Audience Support
  packages/destination-actions/src/destinations/the-trade-desk-crm/functions.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/generated-types.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/index.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/properties.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/syncAudience/index.ts
Labels: not-partner-eng-review (cloud)

#1595 [STRATCONN-3023]-Added traits support in sendTrack action
  packages/destination-actions/src/destinations/segment/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendTrack/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendTrack/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendTrack/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendTrack/index.ts
Labels: not-partner-eng-review (cloud)

#1592 [PINT-1988] Specify device type when associating named user
  packages/destination-actions/src/destinations/airship/utilities.ts
Labels: partner-eng-review (cloud)

#1575 Update amplitude destination based on changes to analyticsjs
  packages/destination-actions/src/destinations/amplitude/__tests__/amplitude.test.ts
  packages/destination-actions/src/destinations/amplitude/__tests__/user-agent.test.ts
  packages/destination-actions/src/destinations/amplitude/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/amplitude/identifyUser/index.ts
  packages/destination-actions/src/destinations/amplitude/logEvent/generated-types.ts
  packages/destination-actions/src/destinations/amplitude/logEvent/index.ts
  packages/destination-actions/src/destinations/amplitude/logEventV2/generated-types.ts
  packages/destination-actions/src/destinations/amplitude/logEventV2/index.ts
  packages/destination-actions/src/destinations/amplitude/logPurchase/generated-types.ts
  packages/destination-actions/src/destinations/amplitude/logPurchase/index.ts
  packages/destination-actions/src/destinations/amplitude/properties.ts
  packages/destination-actions/src/destinations/amplitude/user-agent.ts
Labels: not-partner-eng-review (cloud)

#1597 Stratconn 3144 mixpanel actions
  packages/destination-actions/src/destinations/mixpanel/mixpanel-properties.ts
  packages/destination-actions/src/destinations/mixpanel/mixpanel-types.ts
  packages/destination-actions/src/destinations/mixpanel/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/mixpanel/trackEvent/functions.ts
  packages/destination-actions/src/destinations/mixpanel/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/mixpanel/trackPurchase/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/mixpanel/trackPurchase/generated-types.ts
Labels: not-partner-eng-review (cloud)

#1584 STRATCONN-3141 - Ensure action liveramp audience SFTP uploads respect timeout
  packages/core/src/errors.ts
  packages/core/src/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/audienceEnteredSftp.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/sftp.ts
Labels: not-partner-eng-review (cloud)

#1557 PE-88 Snap products - add product array support for Snapchat Conversions API
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/generated-types.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
  packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
Labels: partner-eng-review (cloud)

#1605 STRATCONN-3184 - fix for iterable date issue
  packages/browser-destinations/destinations/cdpresolution/src/generated-types.ts
  packages/destination-actions/src/destinations/iterable/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/iterable/trackEvent/index.ts
  packages/destination-actions/src/destinations/iterable/utils.ts
Labels: partner-eng-review (cloud)

#1593 [DevRev]: Update streamEvent with new fields for RevUser identification
  packages/destination-actions/src/destinations/devrev/mocks/index.ts
  packages/destination-actions/src/destinations/devrev/streamEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/devrev/streamEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/devrev/streamEvent/generated-types.ts
  packages/destination-actions/src/destinations/devrev/streamEvent/index.ts
Labels: partner-eng-review (cloud)

#1579 [CHANNELS-833] Remove Integration Wrapper on errors thrown with 500
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-sms.test.ts
  packages/destination-actions/src/destinations/engage/twilio/utils/TwilioMessageSender.ts
  packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
Labels: partner-eng-review (cloud)

#1607 [STRATCONN] 3182 added dropdown for facebook capi
  packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-properties.ts
Labels: not-partner-eng-review (cloud)

#1588 Acoustic S3TC Sept13 main - resolve unexpected exception
  packages/destination-actions/src/destinations/acoustic-s3tc/__tests__/index.test.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/generated-types.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/index.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/__tests__/__snapshots__/eventprocessing.test.ts.snap
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/__tests__/index.test.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/__tests__/preCheck.test.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/eventprocessing.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/generated-types.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/index.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/preCheck.ts
Labels: partner-eng-review (cloud)

#1612 CHANNELS-899 Monitoring event streams feature flag
  packages/destination-actions/src/destinations/engage/twilio/utils/PhoneMessageSender.ts
  packages/destination-actions/src/destinations/engage/utils/EngageStats.ts
  packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
Labels: not-partner-eng-review (cloud)

#1589 Update Attio Actions destination to use IDs as unique lookup field
  packages/destination-actions/src/destinations/attio/assertRecord/index.ts
  packages/destination-actions/src/destinations/attio/groupWorkspace/__tests__/index.test.ts
  packages/destination-actions/src/destinations/attio/groupWorkspace/generated-types.ts
  packages/destination-actions/src/destinations/attio/groupWorkspace/index.ts
  packages/destination-actions/src/destinations/attio/identifyUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/attio/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/attio/identifyUser/index.ts
Labels: partner-eng-review (cloud)
