Repository segmentio/action-destinations, pull requests merged in 2023-08, with the labels that each got.

#1429 Channels-783 Allow merge tags in TapAction field of mobile push
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-mobile-push.test.ts
  packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/PushSender.ts
  packages/destination-actions/src/destinations/engage/utils/EngageStats.ts
  packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
Labels: Ready for Release

#1453 CCP-322: Add to email to to name fallback list before User in sendgrid DA
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
Labels: Ready for Release

#1451 CHANNELS-819 fixing error tags
  packages/destination-actions/src/destinations/engage/utils/EngageActionPerformer.ts
  packages/destination-actions/src/destinations/engage/utils/EngageStats.ts
  packages/destination-actions/src/destinations/engage/utils/ResponseError.ts
Labels: Ready for Release

#1437 convert date strings to Airship-friendly format
  packages/destination-actions/src/destinations/airship/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/airship/__tests__/airship.test.ts
  packages/destination-actions/src/destinations/airship/__tests__/utilities.test.ts
  packages/destination-actions/src/destinations/airship/index.ts
  packages/destination-actions/src/destinations/airship/setAttributes/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/airship/utilities.ts
Labels: Partner Hold, partner-eng-review

#1461 ACT-841 Remove push command in favor of action-cli
  packages/cli-internal/src/__tests__/push.test.ts
  packages/cli-internal/src/__tests__/testData.ts
  packages/cli-internal/src/commands/push.ts
Labels: not-partner-eng-review

#1445 Add audience scaffolds
  packages/cli/src/commands/init.ts
  packages/cli/templates/destinations/audience-custom-auth/index.ts
  packages/cli/templates/destinations/audience-oauth2/index.ts
  packages/destination-actions/src/destinations/example/generated-types.ts
Labels: not-partner-eng-review

#1454 Add unsubscribe and preference link context to test emails
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
Labels: partner-eng-review

#1477 Temporary fix for Airship failing tests
  packages/destination-actions/src/destinations/airship/__tests__/utilities.test.ts
Labels: partner-eng-review

#1465 SD-91672 | Optins added | Insider Destination
  packages/destination-actions/src/destinations/insider/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/insider-helpers.ts
  packages/destination-actions/src/destinations/insider/updateUserProfile/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/updateUserProfile/generated-types.ts
  packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
Labels: partner-eng-review

#1469 CHannels-806: Mobile Push Cleanup
  packages/destination-actions/src/destinations/engage-messaging-twilio/sendMobilePush.types.ts
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-mobile-push.test.ts
  packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/PushSender.ts
  packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/actionDefinition.ts
  packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
Labels: partner-eng-review

#1472 [CCP-322] Remove 'to name' from engage sendgrid destination action
  packages/destination-actions/src/destinations/engage/sendgrid/__tests__/send-email.test.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
Labels: partner-eng-review

#1476 Return updated refresh token so that it can be saved
  packages/destination-actions/src/destinations/hilo/index.ts
Labels: partner-eng-review

#1478 fix tests
  packages/destination-actions/src/destinations/airship/__tests__/utilities.test.ts
Labels: partner-eng-review

#1448 [Liveramp] Split into 2 actions
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEntered/sftp.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/generated-types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/s3.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/generated-types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/sftp.ts
  packages/destination-actions/src/destinations/liveramp-audiences/generated-types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/operations.ts
Labels: not-partner-eng-review

#1471 [Stratconn 2954]: Add key in linkedin audience to support RETL
  packages/destination-actions/src/destinations/linkedin-audiences/api/index.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
Labels: not-partner-eng-review

#1458 [CHANNELS-804] Delivery Attempt and Replay in s3logs for Engage logs
  packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
Labels: partner-eng-review

#1479 Two minor updates to tidy up messaging and add version and last update meta, Final on this version
  packages/destination-actions/src/destinations/acoustic/generated-types.ts
  packages/destination-actions/src/destinations/acoustic/index.ts
Labels: partner-eng-review

#1462 Extra context fields requested by client in Mixpanel
  packages/destination-actions/src/destinations/mixpanel/mixpanel-properties.ts
  packages/destination-actions/src/destinations/mixpanel/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/mixpanel/trackPurchase/generated-types.ts
Labels: partner-eng-review

#1468 CCP-356: make sure preview text appears in html and design emails
  packages/destination-actions/src/destinations/engage/sendgrid/__tests__/send-email.test.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/insertEmailPreviewText.ts
Labels: partner-eng-review

#1498 update tiktok web conversion API to 1.3
  packages/destination-actions/src/destinations/tiktok-conversions/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-conversions/index.ts
  packages/destination-actions/src/destinations/tiktok-conversions/reportWebEvent/index.ts
Labels: partner-eng-review

#1505 STRATCONN 3059 - LiveRamp: add special hash handling for email and phone number
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/generated-types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/generated-types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/operations.ts
Labels: not-partner-eng-review

#1482 Stratconn 3002 implement entities mapping presets
  packages/destination-actions/src/destinations/iterable/index.ts
  packages/destination-actions/src/destinations/iterable/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/iterable/updateUser/__tests__/index.test.ts
Labels: not-partner-eng-review

#1474 Stratconn 3001 implement entities mapping presets
  packages/destination-actions/src/destinations/braze/__tests__/braze.test.ts
  packages/destination-actions/src/destinations/braze/index.ts
Labels: not-partner-eng-review

#1485 Implemented entities mapping presets and added unit test case
  packages/destination-actions/src/destinations/customerio/__tests__/createUpdatePerson.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/trackEvent.test.ts
  packages/destination-actions/src/destinations/customerio/index.ts
  packages/destination-actions/src/destinations/index.ts
Labels: not-partner-eng-review

#1496 Added condition for empty string in mapping
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/user-data.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-user-data.ts
Labels: not-partner-eng-review

#1519 Stratconn 2975 full story web action
  packages/browser-destinations/destinations/fullstory/src/__tests__/fullstory.test.ts
  packages/browser-destinations/destinations/fullstory/src/identifyUser/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/user-data.test.ts
Labels: partner-eng-device-review

#1400 [SDK-3485] braze subscription groups
  packages/browser-destinations/destinations/braze/src/__tests__/__snapshots__/integration.test.ts.snap
  packages/browser-destinations/destinations/braze/src/__tests__/updateUserProfile.test.ts
  packages/browser-destinations/destinations/braze/src/index.ts
  packages/browser-destinations/destinations/braze/src/updateUserProfile/generated-types.ts
  packages/browser-destinations/destinations/braze/src/updateUserProfile/index.ts
Labels: partner-eng-device-review

#1441 [external] add new launchdarkly-audiences destination
  packages/destination-actions/src/destinations/launchdarkly-audiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/launchdarkly-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/launchdarkly-audiences/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/launchdarkly-audiences/constants.ts
  packages/destination-actions/src/destinations/launchdarkly-audiences/generated-types.ts
  packages/destination-actions/src/destinations/launchdarkly-audiences/index.ts
  packages/destination-actions/src/destinations/launchdarkly-audiences/syncAudience/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/launchdarkly-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/launchdarkly-audiences/syncAudience/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/launchdarkly-audiences/syncAudience/custom-audience-operations.ts
  packages/destination-actions/src/destinations/launchdarkly-audiences/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/launchdarkly-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/launchdarkly-audiences/types.ts
Labels: partner-eng-cloud-review

#1385 pushwoosh integration
  packages/destination-actions/src/destinations/pushwoosh/__tests__/index.test.ts
  packages/destination-actions/src/destinations/pushwoosh/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/pushwoosh/generated-types.ts
  packages/destination-actions/src/destinations/pushwoosh/index.ts
  packages/destination-actions/src/destinations/pushwoosh/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/pushwoosh/trackEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/pushwoosh/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/pushwoosh/trackEvent/index.ts
  packages/destination-actions/src/destinations/pushwoosh/updateUserProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/pushwoosh/updateUserProfile/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/pushwoosh/updateUserProfile/generated-types.ts
  packages/destination-actions/src/destinations/pushwoosh/updateUserProfile/index.ts
  packages/destination-actions/src/destinations/pushwoosh/utilities.ts
Labels: partner-eng-cloud-review

#1515 [Gameball Cloud Actions] Fix Request Headers & Unit Test
  packages/destination-actions/src/destinations/gameball/identifyPlayer/__tests__/index.test.ts
  packages/destination-actions/src/destinations/gameball/trackOrder/__tests__/index.test.ts
  packages/destination-actions/src/destinations/gameball/util.ts
Labels: partner-eng-cloud-review

#1516 [DevRev]: update API base URL in destination
  packages/destination-actions/src/destinations/devrev/createRevUser/index.ts
  packages/destination-actions/src/destinations/devrev/createWork/index.ts
  packages/destination-actions/src/destinations/devrev/index.ts
  packages/destination-actions/src/destinations/devrev/streamEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/devrev/streamEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/devrev/streamEvent/index.ts
  packages/destination-actions/src/destinations/devrev/utils/constants.ts
  packages/destination-actions/src/destinations/devrev/utils/helpers.ts
  packages/destination-actions/src/destinations/devrev/utils/types.ts
Labels: partner-eng-cloud-review

#1506 Conman 627
  packages/destination-actions/src/destinations/engage-messaging-sendgrid/sendEmail.types.ts
  packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms.types.ts
  packages/destination-actions/src/destinations/engage/sendgrid/__tests__/send-email.test.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/actionDefinition.ts
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-sms.test.ts
  packages/destination-actions/src/destinations/engage/twilio/sendSms/actionDefinition.ts
  packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
Labels: partner-eng-cloud-review

#1502 [canny-functions] Add userId to group request
  packages/destination-actions/src/destinations/canny-functions/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/canny-functions/group/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/canny-functions/group/__tests__/index.test.ts
  packages/destination-actions/src/destinations/canny-functions/group/generated-types.ts
  packages/destination-actions/src/destinations/canny-functions/group/index.ts
Labels: partner-eng-cloud-review

#1504 CHANNELS-847: allow fields body & media to take precedence over content template
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-mobile-push.test.ts
  packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/PushSender.ts
Labels: partner-eng-cloud-review

#1459 fest(Segment): add all new endpoints to segment
  packages/destination-actions/src/destinations/talon-one/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/talon-one/index.ts
  packages/destination-actions/src/destinations/talon-one/t1-properties.ts
  packages/destination-actions/src/destinations/talon-one/trackEvent/index.ts
  packages/destination-actions/src/destinations/talon-one/trackEventV2/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/talon-one/trackEventV2/__tests__/index.test.ts
  packages/destination-actions/src/destinations/talon-one/trackEventV2/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/talon-one/trackEventV2/generated-types.ts
  packages/destination-actions/src/destinations/talon-one/trackEventV2/index.ts
  packages/destination-actions/src/destinations/talon-one/updateCustomerProfile/index.ts
  packages/destination-actions/src/destinations/talon-one/updateCustomerProfileV2/index.ts
  packages/destination-actions/src/destinations/talon-one/updateCustomerProfileV3/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/talon-one/updateCustomerProfileV3/__tests__/index.test.ts
  packages/destination-actions/src/destinations/talon-one/updateCustomerProfileV3/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/talon-one/updateCustomerProfileV3/generated-types.ts
  packages/destination-actions/src/destinations/talon-one/updateCustomerProfileV3/index.ts
  packages/destination-actions/src/destinations/talon-one/updateCustomerSession/index.ts
  packages/destination-actions/src/destinations/talon-one/updateCustomerSessionV2/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/talon-one/updateCustomerSessionV2/__tests__/index.test.ts
  packages/destination-actions/src/destinations/talon-one/updateCustomerSessionV2/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/talon-one/updateCustomerSessionV2/generated-types.ts
  packages/destination-actions/src/destinations/talon-one/updateCustomerSessionV2/index.ts
Labels: partner-eng-cloud-review

#1487 STRATCONN-2984 add some performance improvements to generateFile
  packages/destination-actions/src/destinations/gameball/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/operations.ts
  packages/destination-actions/src/destinations/pushwoosh/updateUserProfile/index.ts
Labels: not-partner-eng-review

#1509 [STRATCONN-3087] Pass statsContext to audience methods
  packages/core/src/destination-kit/index.ts
Labels: not-partner-eng-review

#1520 [STRATCONN-3090] TikTok Audiences - Implement statsClient for create/get audience
  packages/destination-actions/src/destinations/tiktok-audiences/addUser/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeUser/index.ts
Labels: not-partner-eng-review

#1513 [STRATCONN-3037] Add new action "addToAudience" to TikTok Audiences
  packages/destination-actions/src/destinations/tiktok-audiences/addToAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addToAudience/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addToAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addUser/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/createAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/functions.ts
  packages/destination-actions/src/destinations/tiktok-audiences/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-audiences/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/properties.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeUser/index.ts
Labels: not-partner-eng-review

#1518 [STRATCONN-3038] Add removeFromAudience action
  packages/destination-actions/src/destinations/tiktok-audiences/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeFromAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeFromAudience/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeFromAudience/index.ts
Labels: not-partner-eng-review

#1493 Adds `unsafe_hidden` and `readOnly` as InputField possibilities
  packages/core/src/destination-kit/types.ts
Labels: not-partner-eng-review

#1524 Braze US-07 Endpoint
  packages/browser-destinations/destinations/braze/src/index.ts
  packages/destination-actions/src/destinations/braze/index.ts
Labels: partner-eng-cloud-review, partner-eng-device-review

#1534 New Integration - Dynamic Yield Audiences
  packages/destination-actions/src/destinations/dynamic-yield-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/constants.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/generated-types.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/helpers.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/types.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/types.ts
Labels: partner-eng-cloud-review

#1490 [PINT-1852a]
  packages/destination-actions/src/destinations/airship/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/airship/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/airship/__tests__/utilities.test.ts
  packages/destination-actions/src/destinations/airship/index.ts
  packages/destination-actions/src/destinations/airship/registerAndAssociate/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/airship/registerAndAssociate/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/airship/registerAndAssociate/__tests__/index.test.ts
  packages/destination-actions/src/destinations/airship/registerAndAssociate/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/airship/registerAndAssociate/__tests__/test_data.json
  packages/destination-actions/src/destinations/airship/registerAndAssociate/generated-types.ts
  packages/destination-actions/src/destinations/airship/registerAndAssociate/index.ts
  packages/destination-actions/src/destinations/airship/utilities.ts
Labels: partner-eng-cloud-review

#1531 Amend publishConfig for meant to be public packages
  packages/browser-destination-runtime/package.json
  packages/browser-destinations/destinations/adobe-target/package.json
  packages/browser-destinations/destinations/amplitude-plugins/package.json
  packages/browser-destinations/destinations/braze-cloud-plugins/package.json
  packages/browser-destinations/destinations/braze/package.json
  packages/browser-destinations/destinations/commandbar/package.json
  packages/browser-destinations/destinations/friendbuy/package.json
  packages/browser-destinations/destinations/fullstory/package.json
  packages/browser-destinations/destinations/google-analytics-4-web/package.json
  packages/browser-destinations/destinations/heap/package.json
  packages/browser-destinations/destinations/hubspot-web/package.json
  packages/browser-destinations/destinations/intercom/package.json
  packages/browser-destinations/destinations/iterate/package.json
  packages/browser-destinations/destinations/koala/package.json
  packages/browser-destinations/destinations/logrocket/package.json
  packages/browser-destinations/destinations/playerzero-web/package.json
  packages/browser-destinations/destinations/ripe/package.json
  packages/browser-destinations/destinations/screeb/package.json
  packages/browser-destinations/destinations/segment-utilities-web/package.json
  packages/browser-destinations/destinations/sprig-web/package.json
  packages/browser-destinations/destinations/stackadapt/package.json
  packages/browser-destinations/destinations/tiktok-pixel/package.json
  packages/browser-destinations/destinations/upollo/package.json
  packages/browser-destinations/destinations/userpilot/package.json
  packages/browser-destinations/destinations/vwo/package.json
  packages/browser-destinations/destinations/wisepops/package.json
  packages/core/package.json
Labels: not-partner-eng-review

#1522 [STRATCONN] updated setConfigurationField from set to config
  packages/browser-destinations/destinations/google-analytics-4-web/src/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
Labels: not-partner-eng-review

#1529 Fix handling of errors salesforce bulk updates
  packages/destination-actions/src/destinations/salesforce/sf-operations.ts
  packages/destination-actions/src/destinations/salesforce/sf-utils.ts
Labels: not-partner-eng-review
