Repository segmentio/action-destinations, pull requests merged in 2023-11, with the labels that each got.

#1677 Conman 703/adding field
  packages/destination-actions/src/destinations/engage-messaging-sendgrid/sendEmail.types.ts
  packages/destination-actions/src/destinations/engage/sendgrid/__tests__/send-email.test.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/actionDefinition.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1684 Iterable Destination - Support allowNull for Phone Number Field
  packages/destination-actions/src/destinations/iterable/shared-fields.ts
  packages/destination-actions/src/destinations/iterable/trackPurchase/generated-types.ts
  packages/destination-actions/src/destinations/iterable/updateCart/generated-types.ts
  packages/destination-actions/src/destinations/iterable/updateUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/iterable/updateUser/generated-types.ts
Labels: partner-eng-review (cloud)

#1690 LaunchDarkly: Add the option to specify a custom events host name
  packages/destination-actions/src/destinations/launchdarkly/__tests__/index.test.ts
  packages/destination-actions/src/destinations/launchdarkly/aliasUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/launchdarkly/aliasUser/index.ts
  packages/destination-actions/src/destinations/launchdarkly/generated-types.ts
  packages/destination-actions/src/destinations/launchdarkly/index.ts
  packages/destination-actions/src/destinations/launchdarkly/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/launchdarkly/trackEvent/index.ts
  packages/destination-actions/src/destinations/launchdarkly/utils.ts
Labels: partner-eng-review (cloud)

#1693 Update Attio action to link User<>Workspace and append values
  packages/destination-actions/src/destinations/attio/api/index.ts
  packages/destination-actions/src/destinations/attio/assertRecord/__tests__/index.test.ts
  packages/destination-actions/src/destinations/attio/groupWorkspace/__tests__/index.test.ts
  packages/destination-actions/src/destinations/attio/groupWorkspace/generated-types.ts
  packages/destination-actions/src/destinations/attio/groupWorkspace/index.ts
  packages/destination-actions/src/destinations/attio/identifyUser/__tests__/index.test.ts
Labels: partner-eng-review (cloud)

#1701 [DV360] - Adds `refreshAccessToken`
  .vscode/launch.json
  packages/cli/src/commands/serve.ts
  packages/destination-actions/src/destinations/display-video-360/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1699 [Marketo Static Lists] Add audience functions
  packages/destination-actions/src/destinations/marketo-static-lists/__tests__/index.test.ts
  packages/destination-actions/src/destinations/marketo-static-lists/constants.ts
  packages/destination-actions/src/destinations/marketo-static-lists/generated-types.ts
  packages/destination-actions/src/destinations/marketo-static-lists/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1695 changes as asked by Partner
  packages/destination-actions/src/destinations/movable-ink/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/movable-ink/__tests__/index.test.ts
  packages/destination-actions/src/destinations/movable-ink/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/movable-ink/categoryView/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/movable-ink/categoryView/__tests__/index.test.ts
  packages/destination-actions/src/destinations/movable-ink/categoryView/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/movable-ink/categoryView/generated-types.ts
  packages/destination-actions/src/destinations/movable-ink/categoryView/index.ts
  packages/destination-actions/src/destinations/movable-ink/conversion/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/movable-ink/conversion/__tests__/index.test.ts
  packages/destination-actions/src/destinations/movable-ink/conversion/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/movable-ink/conversion/generated-types.ts
  packages/destination-actions/src/destinations/movable-ink/conversion/index.ts
  packages/destination-actions/src/destinations/movable-ink/fields.ts
  packages/destination-actions/src/destinations/movable-ink/generated-types.ts
  packages/destination-actions/src/destinations/movable-ink/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/movable-ink/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/movable-ink/identify/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/movable-ink/identify/generated-types.ts
  packages/destination-actions/src/destinations/movable-ink/identify/index.ts
  packages/destination-actions/src/destinations/movable-ink/index.ts
  packages/destination-actions/src/destinations/movable-ink/productAdded/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/movable-ink/productAdded/__tests__/index.test.ts
  packages/destination-actions/src/destinations/movable-ink/productAdded/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/movable-ink/productAdded/generated-types.ts
  packages/destination-actions/src/destinations/movable-ink/productAdded/index.ts
  packages/destination-actions/src/destinations/movable-ink/productViewed/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/movable-ink/productViewed/__tests__/index.test.ts
  packages/destination-actions/src/destinations/movable-ink/productViewed/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/movable-ink/productViewed/generated-types.ts
  packages/destination-actions/src/destinations/movable-ink/productViewed/index.ts
  packages/destination-actions/src/destinations/movable-ink/search/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/movable-ink/search/__tests__/index.test.ts
  packages/destination-actions/src/destinations/movable-ink/search/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/movable-ink/search/generated-types.ts
  packages/destination-actions/src/destinations/movable-ink/search/index.ts
  packages/destination-actions/src/destinations/movable-ink/sendCustomEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/movable-ink/sendCustomEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/movable-ink/sendCustomEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/movable-ink/sendCustomEvent/generated-types.ts
  packages/destination-actions/src/destinations/movable-ink/sendCustomEvent/index.ts
  packages/destination-actions/src/destinations/movable-ink/sendEntireEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/movable-ink/sendEntireEvent/generated-types.ts
  packages/destination-actions/src/destinations/movable-ink/sendEntireEvent/index.ts
Labels: partner-eng-review (cloud)

#1706 Add profile to list in upsertProfile
  packages/destination-actions/src/destinations/klaviyo/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/types.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1685 Creates new Action Hooks, starting with `onMappingSave` + implements the hook for LinkedIn CAPI
  README.md
  packages/cli/src/commands/generate/types.ts
  packages/cli/src/lib/server.ts
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/index.ts
  packages/core/src/destination-kit/types.ts
  packages/core/src/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1704 [The Trade Desk CRM] Drop invalid emails
  packages/destination-actions/src/destinations/the-trade-desk-crm/functions.ts
Labels: Ready for Release

#1705 STRATCONN-3267: Add Batching Capabilities to Braze
  packages/destination-actions/src/destinations/braze/trackEvent/index.ts
  packages/destination-actions/src/destinations/braze/trackPurchase/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/braze/trackPurchase/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/braze/trackPurchase/generated-types.ts
  packages/destination-actions/src/destinations/braze/trackPurchase/index.ts
  packages/destination-actions/src/destinations/braze/updateUserProfile/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/braze/updateUserProfile/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/braze/updateUserProfile/generated-types.ts
  packages/destination-actions/src/destinations/braze/updateUserProfile/index.ts
  packages/destination-actions/src/destinations/braze/utils.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1713 [Marketo Static Lists] Implement Update Handlers
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/generated-types.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/constants.ts
  packages/destination-actions/src/destinations/marketo-static-lists/functions.ts
  packages/destination-actions/src/destinations/marketo-static-lists/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/properties.ts
  packages/destination-actions/src/destinations/marketo-static-lists/removeFromList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/marketo-static-lists/removeFromList/generated-types.ts
  packages/destination-actions/src/destinations/marketo-static-lists/removeFromList/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1718 Revert "Hide postConversion Action from UI"
  packages/destination-actions/src/destinations/google-enhanced-conversions/postConversion/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1720 Changes to trackey added by Partner
  packages/destination-actions/src/destinations/trackey/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/trackey/__tests__/index.test.ts
  packages/destination-actions/src/destinations/trackey/constants.ts
  packages/destination-actions/src/destinations/trackey/group/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/trackey/group/__tests__/index.test.ts
  packages/destination-actions/src/destinations/trackey/group/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/trackey/group/generated-types.ts
  packages/destination-actions/src/destinations/trackey/group/index.ts
  packages/destination-actions/src/destinations/trackey/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/trackey/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/trackey/identify/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/trackey/identify/generated-types.ts
  packages/destination-actions/src/destinations/trackey/identify/index.ts
  packages/destination-actions/src/destinations/trackey/index.ts
  packages/destination-actions/src/destinations/trackey/track/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/trackey/track/__tests__/index.test.ts
  packages/destination-actions/src/destinations/trackey/track/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/trackey/track/generated-types.ts
  packages/destination-actions/src/destinations/trackey/track/index.ts
Labels: partner-eng-review (cloud)

#1676 Canvas destination
  packages/destination-actions/src/destinations/canvas/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/canvas/__tests__/index.test.ts
  packages/destination-actions/src/destinations/canvas/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/canvas/api.ts
  packages/destination-actions/src/destinations/canvas/common-fields.ts
  packages/destination-actions/src/destinations/canvas/generated-types.ts
  packages/destination-actions/src/destinations/canvas/index.ts
  packages/destination-actions/src/destinations/canvas/sendGroupEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/canvas/sendGroupEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/canvas/sendGroupEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/canvas/sendGroupEvent/generated-types.ts
  packages/destination-actions/src/destinations/canvas/sendGroupEvent/index.ts
  packages/destination-actions/src/destinations/canvas/sendIdentifyEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/canvas/sendIdentifyEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/canvas/sendIdentifyEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/canvas/sendIdentifyEvent/generated-types.ts
  packages/destination-actions/src/destinations/canvas/sendIdentifyEvent/index.ts
  packages/destination-actions/src/destinations/canvas/sendPageEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/canvas/sendPageEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/canvas/sendPageEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/canvas/sendPageEvent/generated-types.ts
  packages/destination-actions/src/destinations/canvas/sendPageEvent/index.ts
  packages/destination-actions/src/destinations/canvas/sendScreenEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/canvas/sendScreenEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/canvas/sendScreenEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/canvas/sendScreenEvent/generated-types.ts
  packages/destination-actions/src/destinations/canvas/sendScreenEvent/index.ts
  packages/destination-actions/src/destinations/canvas/sendTrackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/canvas/sendTrackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/canvas/sendTrackEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/canvas/sendTrackEvent/generated-types.ts
  packages/destination-actions/src/destinations/canvas/sendTrackEvent/index.ts
  packages/destination-actions/src/destinations/canvas/testing.ts
Labels: partner-eng-review (cloud)

#1708 Add additional field for updating only existing users if toggled to true
  packages/destination-actions/src/destinations/moengage/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/moengage/identifyUser/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/moengage/identifyUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moengage/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/moengage/identifyUser/index.ts
  packages/destination-actions/src/destinations/moengage/regional-endpoints.ts
Labels: partner-eng-review (cloud)

#1714 PE-90 - Customer.io - adding app_version field to a single Action
  packages/destination-actions/src/destinations/customerio/__tests__/createUpdateDevice.test.ts
  packages/destination-actions/src/destinations/customerio/createUpdateDevice/generated-types.ts
  packages/destination-actions/src/destinations/customerio/createUpdateDevice/index.ts
Labels: partner-eng-review (cloud)

#1707 SD-96619 - Platform Key Insider
  packages/destination-actions/src/destinations/insider-audiences/insider-helpers.ts
  packages/destination-actions/src/destinations/insider-audiences/insiderAudiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/insider/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/cartViewedEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/checkoutEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/insider-helpers.ts
  packages/destination-actions/src/destinations/insider/orderCompletedEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/productAddedEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/productListViewedEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/productRemovedEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/productViewedEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/updateUserProfile/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/userRegisteredEvent/__tests__/__snapshots__/snapshot.test.ts.snap
Labels: partner-eng-review (cloud)

#1700 fix for jimo initialize issue
  packages/browser-destinations/destinations/jimo/src/index.ts
Labels: partner-eng-review (cloud)

#1712 feat(Jimo/sendUserData): handle traits
  packages/browser-destinations/destinations/jimo/src/sendUserData/__tests__/index.test.ts
  packages/browser-destinations/destinations/jimo/src/sendUserData/generated-types.ts
  packages/browser-destinations/destinations/jimo/src/sendUserData/index.ts
  packages/browser-destinations/destinations/jimo/src/types.ts
Labels: partner-eng-review (device)

#1687 ReplayBird Web Browser Destination
  packages/browser-destinations/destinations/replaybird/README.md
  packages/browser-destinations/destinations/replaybird/package.json
  packages/browser-destinations/destinations/replaybird/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/replaybird/src/generated-types.ts
  packages/browser-destinations/destinations/replaybird/src/identifyUser/__tests__/index.test.ts
  packages/browser-destinations/destinations/replaybird/src/identifyUser/generated-types.ts
  packages/browser-destinations/destinations/replaybird/src/identifyUser/index.ts
  packages/browser-destinations/destinations/replaybird/src/index.ts
  packages/browser-destinations/destinations/replaybird/src/trackEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/replaybird/src/trackEvent/generated-types.ts
  packages/browser-destinations/destinations/replaybird/src/trackEvent/index.ts
  packages/browser-destinations/destinations/replaybird/src/types.ts
  packages/browser-destinations/destinations/replaybird/src/utils.ts
  packages/browser-destinations/destinations/replaybird/tsconfig.json
Labels: partner-eng-review (device)

#1683 APP-86828 Pendo browser destination
  packages/browser-destinations/destinations/pendo-web-actions/src/generated-types.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/group/__tests__/index.test.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/group/generated-types.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/group/index.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/identify/__tests__/index.test.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/identify/generated-types.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/identify/index.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/index.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/loadScript.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/track/index.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/types.ts
Labels: partner-eng-review (device)

#1692 Snap Web Plugin Action
  packages/browser-destinations/destinations/snap-plugins/README.md
  packages/browser-destinations/destinations/snap-plugins/package.json
  packages/browser-destinations/destinations/snap-plugins/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/snap-plugins/src/generated-types.ts
  packages/browser-destinations/destinations/snap-plugins/src/index.ts
  packages/browser-destinations/destinations/snap-plugins/src/snapPlugin/generated-types.ts
  packages/browser-destinations/destinations/snap-plugins/src/snapPlugin/index.ts
  packages/browser-destinations/destinations/snap-plugins/src/utils.ts
  packages/browser-destinations/destinations/snap-plugins/tsconfig.json
  packages/destination-actions/src/destinations/snap-conversions-api/index.ts
  packages/destinations-manifest/src/index.ts
Labels: partner-eng-review (device)

#1696 [CCP-243] - Expose redis cache to engage email DA and use for datafeed calls
  README.md
  packages/core/src/create-test-integration.ts
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/index.ts
  packages/core/src/destination-kit/types.ts
  packages/destination-actions/src/destinations/engage/sendgrid/__tests__/api-lookups.ts
  packages/destination-actions/src/destinations/engage/sendgrid/__tests__/send-email.test.ts
  packages/destination-actions/src/destinations/engage/sendgrid/previewApiLookup/api-lookups.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
  packages/destination-actions/src/destinations/engage/utils/EngageActionPerformer.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1717 Common parsing util
  packages/core/src/index.ts
  packages/core/src/mapping-kit/__tests__/value-keys.test.ts
  packages/core/src/mapping-kit/index.ts
  packages/core/src/mapping-kit/value-keys.ts
Labels: not-partner-eng-review (cloud)

#1727 Added key value pair of new regional endpoint
  packages/destination-actions/src/destinations/moengage/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/moengage/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moengage/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/moengage/index.ts
Labels: partner-eng-review (cloud)

#1733 [Hyperengage] Resolved issue with Timezone Offset and Added Missing user_id field in group call
  packages/destination-actions/src/destinations/hyperengage/__tests__/validateInput.test.ts
  packages/destination-actions/src/destinations/hyperengage/group/generated-types.ts
  packages/destination-actions/src/destinations/hyperengage/group/index.ts
  packages/destination-actions/src/destinations/hyperengage/identify/index.ts
  packages/destination-actions/src/destinations/hyperengage/track/generated-types.ts
  packages/destination-actions/src/destinations/hyperengage/track/index.ts
  packages/destination-actions/src/destinations/hyperengage/validateInput.ts
Labels: partner-eng-review (cloud)

#1743 rename full_name to display_name to fix API changes
  packages/destination-actions/src/destinations/devrev/createRevUser/index.ts
  packages/destination-actions/src/destinations/devrev/mocks/index.ts
Labels: partner-eng-review (cloud)

#1730 [STRATCONN-3376] Add phone number to TikTok Audiences
  packages/destination-actions/src/destinations/tiktok-audiences/addToAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addToAudience/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addToAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addUser/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addUser/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/functions.ts
  packages/destination-actions/src/destinations/tiktok-audiences/properties.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeFromAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeFromAudience/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeFromAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeUser/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeUser/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1735 LR: Fix CSV generator to account for all rows
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/operations.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/operations.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1738 Channels-973: parse text field of action buttons
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-mobile-push.test.ts
  packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/PushSender.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1744 Inc-7055 long term fix: add external ids to message tags
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-sms.test.ts
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-whatsapp.test.ts
  packages/destination-actions/src/destinations/engage/twilio/utils/PhoneMessageSender.ts
Labels: partner-eng-review (cloud)

#1726 Add updateHandler to Actions DV360
  packages/cli/src/lib/server.ts
  packages/destination-actions/package.json
  packages/destination-actions/src/destinations/display-video-360/__tests__/index.test.ts
  packages/destination-actions/src/destinations/display-video-360/__tests__/shared.test.ts
  packages/destination-actions/src/destinations/display-video-360/addToAudience/generated-types.ts
  packages/destination-actions/src/destinations/display-video-360/addToAudience/index.ts
  packages/destination-actions/src/destinations/display-video-360/constants.ts
  packages/destination-actions/src/destinations/display-video-360/errors.ts
  packages/destination-actions/src/destinations/display-video-360/generated-types.ts
  packages/destination-actions/src/destinations/display-video-360/index.ts
  packages/destination-actions/src/destinations/display-video-360/properties.ts
  packages/destination-actions/src/destinations/display-video-360/proto/protofile.ts
  packages/destination-actions/src/destinations/display-video-360/removeFromAudience/generated-types.ts
  packages/destination-actions/src/destinations/display-video-360/removeFromAudience/index.ts
  packages/destination-actions/src/destinations/display-video-360/shared.ts
  packages/destination-actions/src/destinations/display-video-360/types.ts
  yarn.lock
Labels: Ready for Release, not-partner-eng-review (cloud)

#1723 [STRATCONN] Klaviyo AddToProfileList and RemoveFromProfileList actions with engage setup
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/index.ts
  packages/destination-actions/src/destinations/klaviyo/properties.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/index.ts
  packages/destination-actions/src/destinations/klaviyo/types.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1742 Yahoo audiences 5
  packages/destination-actions/src/destinations/yahoo-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/generated-types.ts
  packages/destination-actions/src/destinations/yahoo-audiences/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/updateSegment/generated-types.ts
  packages/destination-actions/src/destinations/yahoo-audiences/updateSegment/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/utils-rt.ts
  packages/destination-actions/src/destinations/yahoo-audiences/utils-tax.ts
Labels: partner-eng-review (cloud)

#1734 fix for empty string in setting
  packages/browser-destinations/destinations/pendo-web-actions/src/loadScript.ts
Labels: partner-eng-review (device)

#1740 fix(Jimo): resolve when jimo is not an array & remove manualInit from settings
  packages/browser-destinations/destinations/jimo/src/generated-types.ts
  packages/browser-destinations/destinations/jimo/src/index.ts
  packages/browser-destinations/destinations/jimo/src/init-script.ts
Labels: partner-eng-review (device)

#1703 create trackEvent and identifyUser browser-destinations for 1flow
  packages/browser-destinations/destinations/1flow/README.md
  packages/browser-destinations/destinations/1flow/package.json
  packages/browser-destinations/destinations/1flow/src/1flow.ts
  packages/browser-destinations/destinations/1flow/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/1flow/src/api.ts
  packages/browser-destinations/destinations/1flow/src/generated-types.ts
  packages/browser-destinations/destinations/1flow/src/identifyUser/__tests__/index.test.ts
  packages/browser-destinations/destinations/1flow/src/identifyUser/generated-types.ts
  packages/browser-destinations/destinations/1flow/src/identifyUser/index.ts
  packages/browser-destinations/destinations/1flow/src/index.ts
  packages/browser-destinations/destinations/1flow/src/trackEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/1flow/src/trackEvent/generated-types.ts
  packages/browser-destinations/destinations/1flow/src/trackEvent/index.ts
  packages/browser-destinations/destinations/1flow/tsconfig.json
Labels: partner-eng-review (device)

#1619 [Strat-2879] | Set up DataDog Dashboard to track requests to Linkedin-audiences Actions
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
Labels: not-partner-eng-review (cloud)
