Repository segmentio/action-destinations, pull requests merged in 2023-12, with the labels that each got.

#1715 Adjust timestamps for consistency with other destinations
  packages/destination-actions/src/destinations/absmartly/__tests__/exposure.test.ts
  packages/destination-actions/src/destinations/absmartly/__tests__/goal.test.ts
  packages/destination-actions/src/destinations/absmartly/__tests__/timestamp.test.ts
  packages/destination-actions/src/destinations/absmartly/event.ts
  packages/destination-actions/src/destinations/absmartly/exposure.ts
  packages/destination-actions/src/destinations/absmartly/goal.ts
  packages/destination-actions/src/destinations/absmartly/segment.ts
  packages/destination-actions/src/destinations/absmartly/timestamp.ts
  packages/destination-actions/src/destinations/absmartly/trackExposure/__tests__/index.test.ts
  packages/destination-actions/src/destinations/absmartly/trackExposure/generated-types.ts
  packages/destination-actions/src/destinations/absmartly/trackExposure/index.ts
  packages/destination-actions/src/destinations/absmartly/trackGoal/__tests__/index.test.ts
  packages/destination-actions/src/destinations/absmartly/trackGoal/generated-types.ts
  packages/destination-actions/src/destinations/absmartly/trackGoal/index.ts
Labels: partner-eng-review (cloud)

#1754 [STRATCONN] 3413 Added External Id in AddProfileToList and RemoveProfileFromList
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/properties.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/index.ts
  packages/destination-actions/src/destinations/klaviyo/types.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1746 STRATCONN-3026 | Upgraded Google API from v13 to v15 in google enhanced conversion
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1747 [Usermaven] Fixed Timezone Offset Calculation
  packages/destination-actions/src/destinations/usermaven/request-params.ts
Labels: partner-eng-review (cloud)

#1765 Implement performBatch for remove from list
  packages/destination-actions/src/destinations/klaviyo/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/index.ts
  packages/destination-actions/src/destinations/klaviyo/types.ts
Labels: not-partner-eng-review (cloud)

#1760 Update Beta And Prod URL
  packages/browser-destinations/destinations/1flow/src/1flow.ts
Labels: partner-eng-review (device)

#1766 Add logging for unsubscribe links
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1769 Adding logic to not double-hash the email when already hashed.
  packages/destination-actions/src/destinations/tiktok-audiences/__tests__/functions.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/functions.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1757 [CCP-624] - Accept shouldRetryOnRetryableError in engage data feed action config + other misc. updates
  packages/cli/src/lib/server.ts
  packages/core/src/destination-kit/index.ts
  packages/destination-actions/src/destinations/engage/sendgrid/__tests__/send-email.test.ts
  packages/destination-actions/src/destinations/engage/sendgrid/previewApiLookup/actionDefinition.ts
  packages/destination-actions/src/destinations/engage/sendgrid/previewApiLookup/index.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/actionDefinition.ts
  packages/destination-actions/src/destinations/engage/utils/Profile.ts
  packages/destination-actions/src/destinations/engage/utils/__tests__/apiLookups.test.ts
  packages/destination-actions/src/destinations/engage/utils/apiLookups.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1728 Algolia Insightes - adding 2 new fields
  packages/destination-actions/src/destinations/algolia-insights/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/algolia-insights/algolia-insight-api.ts
  packages/destination-actions/src/destinations/algolia-insights/conversionEvents/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/algolia-insights/conversionEvents/generated-types.ts
  packages/destination-actions/src/destinations/algolia-insights/conversionEvents/index.ts
  packages/destination-actions/src/destinations/algolia-insights/productAddedEvents/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/algolia-insights/productAddedEvents/generated-types.ts
  packages/destination-actions/src/destinations/algolia-insights/productAddedEvents/index.ts
  packages/destination-actions/src/destinations/algolia-insights/productClickedEvents/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/algolia-insights/productClickedEvents/generated-types.ts
  packages/destination-actions/src/destinations/algolia-insights/productClickedEvents/index.ts
  packages/destination-actions/src/destinations/algolia-insights/productListFilteredEvents/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/algolia-insights/productListFilteredEvents/generated-types.ts
  packages/destination-actions/src/destinations/algolia-insights/productListFilteredEvents/index.ts
  packages/destination-actions/src/destinations/algolia-insights/productViewedEvents/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/algolia-insights/productViewedEvents/generated-types.ts
  packages/destination-actions/src/destinations/algolia-insights/productViewedEvents/index.ts
Labels: partner-eng-review (cloud)

#1763 pipedrive field changes
  packages/destination-actions/src/destinations/pipedrive/createUpdateDeal/generated-types.ts
  packages/destination-actions/src/destinations/pipedrive/createUpdateDeal/index.ts
  packages/destination-actions/src/destinations/pipedrive/createUpdateLead/generated-types.ts
  packages/destination-actions/src/destinations/pipedrive/createUpdateLead/index.ts
  packages/destination-actions/src/destinations/pipedrive/createUpdateOrganization/generated-types.ts
  packages/destination-actions/src/destinations/pipedrive/createUpdateOrganization/index.ts
  packages/destination-actions/src/destinations/pipedrive/createUpdatePerson/generated-types.ts
  packages/destination-actions/src/destinations/pipedrive/createUpdatePerson/index.ts
  packages/destination-actions/src/destinations/pipedrive/pipedriveApi/deals.ts
  packages/destination-actions/src/destinations/pipedrive/pipedriveApi/leads.ts
  packages/destination-actions/src/destinations/pipedrive/pipedriveApi/organizations.ts
  packages/destination-actions/src/destinations/pipedrive/pipedriveApi/persons.ts
Labels: partner-eng-review (cloud)

#1750 [STRATCONN-3415] Pre-Testing Party Fixes
  packages/destination-actions/src/destinations/display-video-360/__tests__/index.test.ts
  packages/destination-actions/src/destinations/display-video-360/__tests__/shared.test.ts
  packages/destination-actions/src/destinations/display-video-360/addToAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/display-video-360/addToAudience/generated-types.ts
  packages/destination-actions/src/destinations/display-video-360/addToAudience/index.ts
  packages/destination-actions/src/destinations/display-video-360/errors.ts
  packages/destination-actions/src/destinations/display-video-360/index.ts
  packages/destination-actions/src/destinations/display-video-360/properties.ts
  packages/destination-actions/src/destinations/display-video-360/removeFromAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/display-video-360/removeFromAudience/generated-types.ts
  packages/destination-actions/src/destinations/display-video-360/removeFromAudience/index.ts
  packages/destination-actions/src/destinations/display-video-360/shared.ts
Labels: Ready for Release, not-partner-eng-review (cloud)
