Repository segmentio/action-destinations, pull requests merged in 2023-10, with the labels that each got.

#1566 feat: hubble-web browser-destination
  packages/browser-destinations/destinations/hubble-web/README.md
  packages/browser-destinations/destinations/hubble-web/package.json
  packages/browser-destinations/destinations/hubble-web/src/__tests__/__snapshots__/index.test.ts.snap
  packages/browser-destinations/destinations/hubble-web/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/hubble-web/src/generated-types.ts
  packages/browser-destinations/destinations/hubble-web/src/identify/__tests__/index.test.ts
  packages/browser-destinations/destinations/hubble-web/src/identify/generated-types.ts
  packages/browser-destinations/destinations/hubble-web/src/identify/index.ts
  packages/browser-destinations/destinations/hubble-web/src/index.ts
  packages/browser-destinations/destinations/hubble-web/src/track/__tests__/index.test.ts
  packages/browser-destinations/destinations/hubble-web/src/track/generated-types.ts
  packages/browser-destinations/destinations/hubble-web/src/track/index.ts
  packages/browser-destinations/destinations/hubble-web/src/types.ts
  packages/browser-destinations/destinations/hubble-web/tsconfig.json
Labels: partner-eng-review (device)

#1618 [The Trade Desk CRM] Remove old create audience flow
  packages/destination-actions/src/destinations/the-trade-desk-crm/awsClient.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/functions.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/generated-types.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/index.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/properties.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/syncAudience/index.ts
Labels: not-partner-eng-review (cloud)

#1624 [TikTok Audiences] Remove feature flag
  packages/destination-actions/src/destinations/tiktok-audiences/addToAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addToAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addUser/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/constants.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeFromAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeFromAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeUser/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1620 [Strat-3157] | Updated type of num_items from string to integer
  packages/destination-actions/src/destinations/pinterest-conversions/pinterest-capi-custom-data.ts
  packages/destination-actions/src/destinations/pinterest-conversions/reportConversionEvent/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/pinterest-conversions/reportConversionEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/pinterest-conversions/reportConversionEvent/generated-types.ts
Labels: not-partner-eng-review (cloud)

#1550 [FullStory] V2Beta to V2
  packages/destination-actions/src/destinations/fullstory/__tests__/fullstory.test.ts
  packages/destination-actions/src/destinations/fullstory/__tests__/request-params.test.ts
  packages/destination-actions/src/destinations/fullstory/identifyUserV2/generated-types.ts
  packages/destination-actions/src/destinations/fullstory/identifyUserV2/index.ts
  packages/destination-actions/src/destinations/fullstory/index.ts
  packages/destination-actions/src/destinations/fullstory/request-params.ts
  packages/destination-actions/src/destinations/fullstory/trackEventV2/generated-types.ts
  packages/destination-actions/src/destinations/fullstory/trackEventV2/index.ts
Labels: partner-eng-review (cloud)

#1621 [Hyperengage] Destination
  packages/destination-actions/src/destinations/hyperengage/__tests__/hyperengage.test.ts
  packages/destination-actions/src/destinations/hyperengage/__tests__/validateInput.test.ts
  packages/destination-actions/src/destinations/hyperengage/commonFields.ts
  packages/destination-actions/src/destinations/hyperengage/generated-types.ts
  packages/destination-actions/src/destinations/hyperengage/group/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hyperengage/group/generated-types.ts
  packages/destination-actions/src/destinations/hyperengage/group/index.ts
  packages/destination-actions/src/destinations/hyperengage/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hyperengage/identify/generated-types.ts
  packages/destination-actions/src/destinations/hyperengage/identify/index.ts
  packages/destination-actions/src/destinations/hyperengage/index.ts
  packages/destination-actions/src/destinations/hyperengage/track/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hyperengage/track/generated-types.ts
  packages/destination-actions/src/destinations/hyperengage/track/index.ts
  packages/destination-actions/src/destinations/hyperengage/validateInput.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSFTP.types.ts
Labels: partner-eng-review (cloud)

#1622 Channels-911 Remove Eventstreams flagon
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-sms.test.ts
  packages/destination-actions/src/destinations/engage/twilio/utils/PhoneMessageSender.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1633 STRATCONN-3246 remove timestamp from LiveRamp filename default
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSFTP.types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1636 Yahoo audiences 2
  README.md
  packages/destination-actions/src/destinations/airship/utilities.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/__tests__/index.test.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/emailEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/upsertContact/__tests__/index.test.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/upsertContact/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/createCustomerNode/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/createCustomerNode/generated-types.ts
  packages/destination-actions/src/destinations/yahoo-audiences/createCustomerNode/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/createSegment/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/createSegment/generated-types.ts
  packages/destination-actions/src/destinations/yahoo-audiences/createSegment/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/generated-types.ts
  packages/destination-actions/src/destinations/yahoo-audiences/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/types.ts
  packages/destination-actions/src/destinations/yahoo-audiences/updateSegment/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/updateSegment/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/utils-tax.ts
Labels: partner-eng-review (cloud)

#1637 [STRATCONN 3248] Added timestamp mapping
  packages/destination-actions/src/destinations/segment-profiles/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/segment-properties.ts
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/generated-types.ts
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/index.ts
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/generated-types.ts
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/index.ts
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/generated-types.ts
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
Labels: not-partner-eng-review (cloud)

#1632 STRATCONN-3229 | Hubspot Cloud Actions- Can not read properties of undefined (Setting actions)
  packages/destination-actions/src/destinations/hubspot/upsertContact/__tests__/__helpers__/test-utils.ts
  packages/destination-actions/src/destinations/hubspot/upsertContact/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/hubspot/upsertContact/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertContact/index.ts
Labels: not-partner-eng-review (cloud)

#1590 Trackey integration
  packages/destination-actions/src/destinations/trackey/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/trackey/__tests__/index.test.ts
  packages/destination-actions/src/destinations/trackey/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/trackey/generated-types.ts
  packages/destination-actions/src/destinations/trackey/group.types.ts
  packages/destination-actions/src/destinations/trackey/identify.types.ts
  packages/destination-actions/src/destinations/trackey/index.ts
  packages/destination-actions/src/destinations/trackey/track.types.ts
Labels: partner-eng-review (cloud)

#1643 Migrates `type: hidden` to `type: 'string', hidden: true`
  packages/core/src/__tests__/schema-validation.test.ts
  packages/core/src/destination-kit/fields-to-jsonschema.ts
  packages/core/src/destination-kit/types.ts
  packages/destination-actions/src/destinations/ambee/subscribeUserToCampaign/index.ts
  packages/destination-actions/src/destinations/braze-cohorts/syncAudiences/index.ts
  packages/destination-actions/src/destinations/cordial/identities-fields.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
  packages/destination-actions/src/destinations/launchdarkly-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
  packages/destination-actions/src/destinations/livelike-cloud/trackEvent/index.ts
  packages/destination-actions/src/destinations/optimizely-advanced-audience-targeting/syncAudience/index.ts
  packages/destination-actions/src/destinations/optimizely-feature-experimentation-actions/trackEvent/index.ts
  packages/destination-actions/src/destinations/outfunnel/forwardGroupEvent/index.ts
  packages/destination-actions/src/destinations/outfunnel/forwardIdentifyEvent/index.ts
  packages/destination-actions/src/destinations/outfunnel/forwardTrackEvent/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/properties.ts
  packages/destination-actions/src/destinations/twilio-studio/triggerStudioFlow/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/updateSegment/index.ts
Labels: not-partner-eng-review (cloud)

#1645 Add upsert profile and track event actions to klaviyo
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/klaviyo/config.ts
  packages/destination-actions/src/destinations/klaviyo/index.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/index.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/index.ts
  packages/destination-actions/src/destinations/klaviyo/types.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/index.ts
Labels: not-partner-eng-review (cloud)

#1648 CDP Resolution cloud - updating initialize function
  packages/browser-destinations/destinations/cdpresolution/src/index.ts
Labels: partner-eng-review (device)

#1641 Tiktok pixel external
  packages/browser-destinations/destinations/tiktok-pixel/package.json
  packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/index.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/types.ts
Labels: partner-eng-review (device)

#1626 Jimo Browser Destination
  packages/browser-destinations/destinations/jimo/README.md
  packages/browser-destinations/destinations/jimo/package.json
  packages/browser-destinations/destinations/jimo/src/generated-types.ts
  packages/browser-destinations/destinations/jimo/src/index.ts
  packages/browser-destinations/destinations/jimo/src/init-script.ts
  packages/browser-destinations/destinations/jimo/src/sendUserData/__tests__/index.test.ts
  packages/browser-destinations/destinations/jimo/src/sendUserData/generated-types.ts
  packages/browser-destinations/destinations/jimo/src/sendUserData/index.ts
  packages/browser-destinations/destinations/jimo/src/types.ts
  packages/browser-destinations/destinations/jimo/tsconfig.json
  packages/browser-destinations/destinations/ripe/src/index.ts
Labels: partner-eng-review (device)

#1652 [STRATCONN-3250] [GA4 Web] Run setconfiguration before all actions
  packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
Labels: not-partner-eng-review (device)

#1658 [Stratconn 3084] Scaffold linked in conversions api
  packages/destination-actions/src/destinations/linkedin-conversions/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/linkedin-conversions/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/api/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/constants.ts
  packages/destination-actions/src/destinations/linkedin-conversions/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-conversions/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/types.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1660 Removed console from code
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/__tests__/index.test.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1654 [The Trade Desk CRM] Change getAudience method
  packages/destination-actions/src/destinations/the-trade-desk-crm/__tests__/index.test.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/functions.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1644 Action Destination for Kameleoon
  packages/destination-actions/src/destinations/kameleoon/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/kameleoon/__tests__/index.test.ts
  packages/destination-actions/src/destinations/kameleoon/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/kameleoon/generated-types.ts
  packages/destination-actions/src/destinations/kameleoon/index.ts
  packages/destination-actions/src/destinations/kameleoon/logEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/kameleoon/logEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/kameleoon/logEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/kameleoon/logEvent/generated-types.ts
  packages/destination-actions/src/destinations/kameleoon/logEvent/index.ts
  packages/destination-actions/src/destinations/kameleoon/properties.ts
Labels: partner-eng-review (cloud)

#1642 Mixpanel: ua parser fix + version fix
  packages/destination-actions/src/destinations/mixpanel/alias/__tests__/index.test.ts
  packages/destination-actions/src/destinations/mixpanel/alias/index.ts
  packages/destination-actions/src/destinations/mixpanel/common/__test__/utils.test.ts
  packages/destination-actions/src/destinations/mixpanel/common/utils.ts
  packages/destination-actions/src/destinations/mixpanel/groupIdentifyUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/mixpanel/groupIdentifyUser/index.ts
  packages/destination-actions/src/destinations/mixpanel/identifyUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/mixpanel/identifyUser/index.ts
  packages/destination-actions/src/destinations/mixpanel/index.ts
  packages/destination-actions/src/destinations/mixpanel/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/mixpanel/trackEvent/functions.ts
  packages/destination-actions/src/destinations/mixpanel/trackEvent/index.ts
  packages/destination-actions/src/destinations/mixpanel/trackPurchase/__tests__/index.test.ts
  packages/destination-actions/src/destinations/mixpanel/trackPurchase/index.ts
Labels: partner-eng-review (cloud)

#1646 Add actions-display-video-360
  packages/destination-actions/src/destinations/display-video-360/__tests__/index.test.ts
  packages/destination-actions/src/destinations/display-video-360/addToAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/display-video-360/addToAudience/generated-types.ts
  packages/destination-actions/src/destinations/display-video-360/addToAudience/index.ts
  packages/destination-actions/src/destinations/display-video-360/generated-types.ts
  packages/destination-actions/src/destinations/display-video-360/index.ts
  packages/destination-actions/src/destinations/display-video-360/removeFromAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/display-video-360/removeFromAudience/generated-types.ts
  packages/destination-actions/src/destinations/display-video-360/removeFromAudience/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1666 TikTok and Trade Desk changes
  packages/destination-actions/src/destinations/the-trade-desk-crm/functions.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addUser/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeUser/index.ts
Labels: not-partner-eng-review (cloud)

#1665 Scaffold Marketo Static Lists
  packages/destination-actions/src/destinations/marketo-static-lists/__tests__/index.test.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/generated-types.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/generated-types.ts
  packages/destination-actions/src/destinations/marketo-static-lists/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/removeFromList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/marketo-static-lists/removeFromList/generated-types.ts
  packages/destination-actions/src/destinations/marketo-static-lists/removeFromList/index.ts
Labels: not-partner-eng-review (cloud)

#1667 Update docs
  CONTRIBUTING.md
  docs/authentication.md
Labels: documentation

#1681 [The Trade Desk CRM] Avoid double hashing
  packages/destination-actions/src/destinations/the-trade-desk-crm/functions.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/syncAudience/__tests__/index.test.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1679 Yahoo audiences update
  packages/destination-actions/src/destinations/yahoo-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/updateSegment/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/updateSegment/generated-types.ts
  packages/destination-actions/src/destinations/yahoo-audiences/updateSegment/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/utils-rt.ts
  packages/destination-actions/src/destinations/yahoo-audiences/utils-tax.ts
Labels: partner-eng-review (cloud)

#1675 [STRATCONN-3301] Add createAudience/getAudience to DV360
  packages/destination-actions/src/destinations/display-video-360/__tests__/index.test.ts
  packages/destination-actions/src/destinations/display-video-360/constants.ts
  packages/destination-actions/src/destinations/display-video-360/generated-types.ts
  packages/destination-actions/src/destinations/display-video-360/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1674 Adding US-07 instance
  packages/destination-actions/src/destinations/braze-cohorts/index.ts
Labels: enhancement, Ready for Release, not-partner-eng-review (cloud)

#1669 STRATCONN-2921 braze: add support for merge_behavior
  packages/destination-actions/src/destinations/braze/identifyUser/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/braze/identifyUser/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/braze/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/braze/identifyUser/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1594 Stratconn 3130 dynamic field google enhanced conversion
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/functions.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1670 UserMotion Cloud Action
  packages/destination-actions/src/destinations/usermotion/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/usermotion/__tests__/index.test.ts
  packages/destination-actions/src/destinations/usermotion/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/usermotion/generated-types.ts
  packages/destination-actions/src/destinations/usermotion/group/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/usermotion/group/__tests__/index.test.ts
  packages/destination-actions/src/destinations/usermotion/group/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/usermotion/group/generated-types.ts
  packages/destination-actions/src/destinations/usermotion/group/index.ts
  packages/destination-actions/src/destinations/usermotion/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/usermotion/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/usermotion/identify/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/usermotion/identify/generated-types.ts
  packages/destination-actions/src/destinations/usermotion/identify/index.ts
  packages/destination-actions/src/destinations/usermotion/index.ts
  packages/destination-actions/src/destinations/usermotion/track/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/usermotion/track/__tests__/index.test.ts
  packages/destination-actions/src/destinations/usermotion/track/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/usermotion/track/generated-types.ts
  packages/destination-actions/src/destinations/usermotion/track/index.ts
Labels: partner-eng-review (cloud)

#1673 engage/sendgrid onResponse undefined bug
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
Labels: not-partner-eng-review (cloud)

#1649 SD-96364 | Madeira Madeira | Data sent by Segment is not reaching Insider.
  packages/destination-actions/src/destinations/insider-audiences/insider-helpers.ts
  packages/destination-actions/src/destinations/insider/cartViewedEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/insider/cartViewedEvent/index.ts
  packages/destination-actions/src/destinations/insider/checkoutEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/insider/checkoutEvent/index.ts
  packages/destination-actions/src/destinations/insider/insider-helpers.ts
  packages/destination-actions/src/destinations/insider/orderCompletedEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/insider/orderCompletedEvent/index.ts
  packages/destination-actions/src/destinations/insider/productAddedEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/insider/productAddedEvent/index.ts
  packages/destination-actions/src/destinations/insider/productListViewedEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/insider/productListViewedEvent/index.ts
  packages/destination-actions/src/destinations/insider/productRemovedEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/insider/productRemovedEvent/index.ts
  packages/destination-actions/src/destinations/insider/productViewedEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/insider/productViewedEvent/index.ts
  packages/destination-actions/src/destinations/insider/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/insider/trackEvent/index.ts
  packages/destination-actions/src/destinations/insider/updateUserProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
  packages/destination-actions/src/destinations/insider/userRegisteredEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/insider/userRegisteredEvent/index.ts
Labels: partner-eng-review (cloud)

#1651 Improve CI speed, add nx
  .github/workflows/ci.yml
  .nxignore
  README.md
  docs/testing.md
  nx.json
  package.json
  packages/actions-shared/package.json
  packages/browser-destination-runtime/package.json
  packages/browser-destinations-integration-tests/package.json
  packages/browser-destinations/package.json
  packages/browser-destinations/tsconfig.json
  packages/cli-internal/package.json
  packages/cli/src/__tests__/init.test.ts
  packages/core/package.json
  packages/destination-actions/package.json
  packages/destination-subscriptions/package.json
  scripts/assert-lockfile-updated.sh
  scripts/assert-types-updated.sh
  yarn.lock
Labels: not-partner-eng-review (cloud), not-partner-eng-review (device)

#1686 [Google Ads Conversion] - Updated default API version from deprecated v12 to v13
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
Labels: not-partner-eng-review (cloud)

#1697 Hide postConversion Action from UI
  packages/destination-actions/src/destinations/google-enhanced-conversions/postConversion/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)
