Repository segmentio/action-destinations, pull requests merged in 2024-02, with the labels that each got.

#1842 Add Window object change unit test
  packages/browser-destinations/__tests__/window.test.ts
Labels: not-partner-eng-review (device)

#1850 Avo inspector destination
  packages/destination-actions/src/destinations/avo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/avo/__tests__/index.test.ts
  packages/destination-actions/src/destinations/avo/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/avo/generated-types.ts
  packages/destination-actions/src/destinations/avo/index.ts
  packages/destination-actions/src/destinations/avo/sendSchemaToInspector/AvoSchemaParser.ts
  packages/destination-actions/src/destinations/avo/sendSchemaToInspector/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/avo/sendSchemaToInspector/__tests__/index.test.ts
  packages/destination-actions/src/destinations/avo/sendSchemaToInspector/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/avo/sendSchemaToInspector/avo-types.ts
  packages/destination-actions/src/destinations/avo/sendSchemaToInspector/avo.ts
  packages/destination-actions/src/destinations/avo/sendSchemaToInspector/generated-types.ts
  packages/destination-actions/src/destinations/avo/sendSchemaToInspector/index.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1856 [LinkedIn CAPI] Batch create a campaign conversion
  packages/destination-actions/src/destinations/linkedin-conversions/api/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/constants.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1857 [Userpilot] Add Group method to presets
  packages/browser-destinations/destinations/userpilot/src/index.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1853 Airship: changes to how tags work to support strings
  packages/destination-actions/src/destinations/airship/utilities.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1863 DV360 - Support no-auth endpoint for legacy destinations
  packages/destination-actions/src/destinations/display-video-360/__tests__/index.test.ts
  packages/destination-actions/src/destinations/display-video-360/index.ts
  packages/destination-actions/src/destinations/display-video-360/shared.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1828 New action destination for StackAdapt
  packages/destination-actions/src/destinations/stackadapt/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/stackadapt/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/stackadapt/forwardEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/stackadapt/forwardEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/stackadapt/forwardEvent/generated-types.ts
  packages/destination-actions/src/destinations/stackadapt/forwardEvent/index.ts
  packages/destination-actions/src/destinations/stackadapt/generated-types.ts
  packages/destination-actions/src/destinations/stackadapt/index.ts
Labels: partner-eng-review (cloud)

#1852 Schematic - field changes
  packages/destination-actions/src/destinations/schematic/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/identifyUser/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/schematic/identifyUser/index.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/index.ts
Labels: partner-eng-review (cloud)

#1867 add types for @json directive
  packages/core/src/mapping-kit/__tests__/value-keys.test.ts
  packages/core/src/mapping-kit/value-keys.ts
Labels: not-partner-eng-review (cloud)

#1877 Update name of AppFit destination
  packages/destination-actions/src/destinations/app-fit/index.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1876 Adding Accoil Detination
  packages/destination-actions/src/destinations/accoil-analytics/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/__tests__/index.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/generated-types.ts
  packages/destination-actions/src/destinations/accoil-analytics/index.ts
  packages/destination-actions/src/destinations/accoil-analytics/postToAccoil/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/postToAccoil/__tests__/index.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/postToAccoil/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/postToAccoil/generated-types.ts
  packages/destination-actions/src/destinations/accoil-analytics/postToAccoil/index.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1875 DV360 - Fix 403 Errors in Data Syncs
  packages/destination-actions/src/destinations/display-video-360/__tests__/index.test.ts
  packages/destination-actions/src/destinations/display-video-360/errors.ts
  packages/destination-actions/src/destinations/display-video-360/index.ts
  packages/destination-actions/src/destinations/display-video-360/shared.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1874 [linkedin-conversions] Correctly throw IntegrationErrors when there is an error response in `perform`
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/types.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1866 minor changes to Avo
  packages/destination-actions/src/destinations/avo/index.ts
  packages/destination-actions/src/destinations/avo/sendSchemaToInspector/avo.ts
  packages/destination-actions/src/destinations/avo/sendSchemaToInspector/generated-types.ts
  packages/destination-actions/src/destinations/avo/sendSchemaToInspector/index.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1855 PT-623: Adding preset for iterable
  packages/destination-actions/src/destinations/iterable/index.ts
  packages/destination-actions/src/destinations/iterable/trackEvent/__tests__/index.test.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1737 Responsys: Initial commit
  packages/destination-actions/src/destinations/responsys/__tests__/index.test.ts
  packages/destination-actions/src/destinations/responsys/generated-types.ts
  packages/destination-actions/src/destinations/responsys/index.ts
  packages/destination-actions/src/destinations/responsys/sendAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/responsys/sendAudience/generated-types.ts
  packages/destination-actions/src/destinations/responsys/sendAudience/index.ts
  packages/destination-actions/src/destinations/responsys/sendCustomTraits/__tests__/index.test.ts
  packages/destination-actions/src/destinations/responsys/sendCustomTraits/generated-types.ts
  packages/destination-actions/src/destinations/responsys/sendCustomTraits/index.ts
  packages/destination-actions/src/destinations/responsys/shared_properties.ts
  packages/destination-actions/src/destinations/responsys/types.ts
  packages/destination-actions/src/destinations/responsys/upsertListMember/__tests__/index.test.ts
  packages/destination-actions/src/destinations/responsys/upsertListMember/generated-types.ts
  packages/destination-actions/src/destinations/responsys/upsertListMember/index.ts
  packages/destination-actions/src/destinations/responsys/utils.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1872 updating presets to point to V2 Actions
  packages/destination-actions/src/destinations/fullstory/index.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1851 Added preset for Customer.io jsm step event
  packages/destination-actions/src/destinations/customerio/__tests__/trackEvent.test.ts
  packages/destination-actions/src/destinations/customerio/index.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1879 PR feedback for FullStory Web API upgrade
  packages/browser-destinations/destinations/fullstory/src/identifyUserV2/index.ts
  packages/browser-destinations/destinations/fullstory/src/viewedPageV2/index.ts
Labels: partner-eng-review (device)

#1878 feat(Jimo/Actions): sendTrackEvent
  packages/browser-destinations/destinations/jimo/src/index.ts
  packages/browser-destinations/destinations/jimo/src/sendTrackEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/jimo/src/sendTrackEvent/generated-types.ts
  packages/browser-destinations/destinations/jimo/src/sendTrackEvent/index.ts
Labels: Ready for Release, partner-eng-review (device)

#1800 Update Customer.io destination to use v2 api
  packages/destination-actions/src/destinations/customerio/__tests__/createUpdateDevice.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/createUpdateObject.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/createUpdatePerson.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/delete.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/deleteDevice.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/deleteDevice.ts
  packages/destination-actions/src/destinations/customerio/__tests__/deleteObject.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/deletePerson.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/deleteRelationship.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/mergePeople.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/reportDeliveryEvent.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/suppressPerson.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/trackEvent.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/trackPageView.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/trackScreenView.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/unsuppressPerson.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/utils.test.ts
  packages/destination-actions/src/destinations/customerio/createUpdateDevice/generated-types.ts
  packages/destination-actions/src/destinations/customerio/createUpdateDevice/index.ts
  packages/destination-actions/src/destinations/customerio/createUpdateObject/generated-types.ts
  packages/destination-actions/src/destinations/customerio/createUpdateObject/index.ts
  packages/destination-actions/src/destinations/customerio/createUpdatePerson/generated-types.ts
  packages/destination-actions/src/destinations/customerio/createUpdatePerson/index.ts
  packages/destination-actions/src/destinations/customerio/deleteDevice/index.ts
  packages/destination-actions/src/destinations/customerio/deleteObject/generated-types.ts
  packages/destination-actions/src/destinations/customerio/deleteObject/index.ts
  packages/destination-actions/src/destinations/customerio/deletePerson/generated-types.ts
  packages/destination-actions/src/destinations/customerio/deletePerson/index.ts
  packages/destination-actions/src/destinations/customerio/deleteRelationship/generated-types.ts
  packages/destination-actions/src/destinations/customerio/deleteRelationship/index.ts
  packages/destination-actions/src/destinations/customerio/index.ts
  packages/destination-actions/src/destinations/customerio/mergePeople/generated-types.ts
  packages/destination-actions/src/destinations/customerio/mergePeople/index.ts
  packages/destination-actions/src/destinations/customerio/reportDeliveryEvent/generated-types.ts
  packages/destination-actions/src/destinations/customerio/reportDeliveryEvent/index.ts
  packages/destination-actions/src/destinations/customerio/suppressPerson/generated-types.ts
  packages/destination-actions/src/destinations/customerio/suppressPerson/index.ts
  packages/destination-actions/src/destinations/customerio/test-helper.ts
  packages/destination-actions/src/destinations/customerio/trackEvent/index.ts
  packages/destination-actions/src/destinations/customerio/trackPageView/generated-types.ts
  packages/destination-actions/src/destinations/customerio/trackPageView/index.ts
  packages/destination-actions/src/destinations/customerio/trackScreenView/generated-types.ts
  packages/destination-actions/src/destinations/customerio/trackScreenView/index.ts
  packages/destination-actions/src/destinations/customerio/unsuppressPerson/generated-types.ts
  packages/destination-actions/src/destinations/customerio/unsuppressPerson/index.ts
  packages/destination-actions/src/destinations/customerio/utils.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1839 [snap-conversion-api] Base refactor to switch between snap capi imple…
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/capiV2tests.ts
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/capiV3tests.ts
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-v2.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-v3.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/utils.ts
  packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1885 Avo update wording based on customer feedback
  packages/destination-actions/src/destinations/avo/generated-types.ts
  packages/destination-actions/src/destinations/avo/index.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1864 Acoustic S3TC Sept13 - UniqueRecip, replace CSV to JSON basis
  packages/destination-actions/src/destinations/acoustic-s3tc/generated-types.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/index.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/__tests__/__snapshots__/eventprocessing.test.ts.snap
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/__tests__/eventprocessing.test.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/eventprocessing.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/generated-types.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/index.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1888 Schematic destination - updates to trackEvent
  packages/destination-actions/src/destinations/schematic/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/index.ts
Labels: partner-eng-review (cloud)

#1889 Refactor ordered product event request handling
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1881 Marketo Static Lists Updates
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/generated-types.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/constants.ts
  packages/destination-actions/src/destinations/marketo-static-lists/functions.ts
  packages/destination-actions/src/destinations/marketo-static-lists/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/properties.ts
  packages/destination-actions/src/destinations/marketo-static-lists/removeFromList/generated-types.ts
  packages/destination-actions/src/destinations/marketo-static-lists/removeFromList/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1884 Revamp DV360 refresh_token flow
  packages/destination-actions/src/destinations/display-video-360/__tests__/index.test.ts
  packages/destination-actions/src/destinations/display-video-360/shared.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1890 [GA4 Cloud] Add new consent fields
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/addPaymentInfo.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/addToCart.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/addToWishlist.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/beginCheckout.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/customEvent.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/generateLead.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/login.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/pageView.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/purchase.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/refund.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/removeFromCart.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/search.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/selectItem.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/selectPromotion.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/signUp.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/viewCart.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/viewItem.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/viewItemList.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/__tests__/viewPromotion.test.ts
  packages/destination-actions/src/destinations/google-analytics-4/addPaymentInfo/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/addPaymentInfo/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/addToCart/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/addToCart/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/addToWishlist/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/addToWishlist/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/beginCheckout/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/beginCheckout/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/customEvent/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/customEvent/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/ga4-functions.ts
  packages/destination-actions/src/destinations/google-analytics-4/ga4-properties.ts
  packages/destination-actions/src/destinations/google-analytics-4/ga4-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/generateLead/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/generateLead/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/login/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/login/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/pageView/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/pageView/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/purchase/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/purchase/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/refund/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/refund/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/removeFromCart/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/removeFromCart/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/search/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/search/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/selectItem/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/selectItem/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/selectPromotion/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/selectPromotion/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/signUp/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/signUp/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/viewCart/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/viewCart/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/viewItem/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/viewItem/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/viewItemList/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/viewItemList/index.ts
  packages/destination-actions/src/destinations/google-analytics-4/viewPromotion/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/viewPromotion/index.ts
Labels: not-partner-eng-review (cloud)

#1847 [STRAT-3396] - Add Consent Signals to Google Enhanced Conversions
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadCallConversion.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
Labels: not-partner-eng-review (cloud)

#1887 [LinkedIn Conversions] Update Conversion Rules
  packages/cli/src/lib/server.ts
  packages/destination-actions/src/destinations/linkedin-conversions/api/api.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/api/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/types.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1854 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Ready for Release, not-partner-eng-review (cloud)

#1892 Kafka destination
  packages/destination-actions/package.json
  packages/destination-actions/src/destinations/kafka/generated-types.ts
  packages/destination-actions/src/destinations/kafka/index.ts
  packages/destination-actions/src/destinations/kafka/send/__tests__/index.test.ts
  packages/destination-actions/src/destinations/kafka/send/generated-types.ts
  packages/destination-actions/src/destinations/kafka/send/index.ts
  packages/destination-actions/src/destinations/kafka/utils.ts
  yarn.lock
Labels: partner-eng-review (cloud)

#1891 Algolia changes requested by Partner
  packages/destination-actions/src/destinations/algolia-insights/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/algolia-insights/algolia-insight-api.ts
  packages/destination-actions/src/destinations/algolia-insights/conversionEvents/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/algolia-insights/conversionEvents/__tests__/index.test.ts
  packages/destination-actions/src/destinations/algolia-insights/conversionEvents/generated-types.ts
  packages/destination-actions/src/destinations/algolia-insights/conversionEvents/index.ts
  packages/destination-actions/src/destinations/algolia-insights/productAddedEvents/index.ts
  packages/destination-actions/src/destinations/algolia-insights/productClickedEvents/index.ts
  packages/destination-actions/src/destinations/algolia-insights/productListFilteredEvents/index.ts
  packages/destination-actions/src/destinations/algolia-insights/productViewedEvents/index.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1897 TikTok Audience Destinations doc changes
  packages/destination-actions/src/destinations/tiktok-audiences/addUser/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/createAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeUser/index.ts
Labels: documentation, not-partner-eng-review (cloud)

#1843 Conditional input fields + implementation for LinkedIn CAPI, Salesforce
  README.md
  packages/core/src/destination-kit/types.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
  packages/destination-actions/src/destinations/salesforce/sf-properties.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1899 [STRATCONN-3575] Updates salesforce enable_batch field to reflect accurate batch sizes
  packages/destination-actions/src/destinations/salesforce/account/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/cases/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/contact/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/customObject/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/lead/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/opportunity/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/sf-properties.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1871 [MAIN] [STRATCONN] added new consent
  packages/browser-destinations/destinations/google-analytics-4-web/src/__tests__/setConfigurationFields.test.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
  packages/browser-destinations/package.json
  yarn.lock
Labels: Ready for Release, not-partner-eng-review (device)

#1817 [STRATCONN] [MAIN] GA4 updates in set config settings default values
  packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
Labels: Ready for Release, not-partner-eng-review (device)

#1825 [STRAT-3534] | Fixed Google Enhanced Conversion Action Dynamic Field Dropdown
  packages/core/src/destination-kit/action.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/functions.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1848 Add null checks for possible null trait
  packages/destination-actions/src/destinations/engage/sendgrid/__tests__/send-email.test.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-sms.test.ts
  packages/destination-actions/src/destinations/engage/twilio/utils/TwilioMessageSender.ts
  packages/destination-actions/src/destinations/engage/utils/Profile.ts
Labels: partner-eng-review (cloud)

#1893 [Snap CAPI v3] Add missing IDFV and app-id fields
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/capiV3tests.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-v3.ts
Labels: partner-eng-review (cloud)
