Repository segmentio/action-destinations, pull requests merged in 2024-04, with the labels that each got.

#1961 Fixes broken Hyperengage Unit Test
  packages/destination-actions/src/destinations/hyperengage/__tests__/validateInput.test.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#1956 [STRATCONN-3673] - Fetch all commits in publish workflow
  .github/workflows/publish.yml
Labels: partner-eng-review (cloud), team:segment-core

#1964 Set intercom destination installation_type to 's' (segment) to identify custom install
  packages/browser-destinations/destinations/intercom/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/intercom/src/index.ts
  packages/browser-destinations/destinations/intercom/src/init-script.ts
Labels: partner-eng-review (device), team:external, mode:device

#1963 [STRATCONN-3673] - Fix release workflow
  .github/workflows/publish.yml
  package.json
  scripts/postversion.sh
  scripts/release.sh
Labels: partner-eng-review (cloud), team:segment-core

#1970 [STRATCONN-3673] - Minor fixes to github scripts and adds test instructions
  .github/workflows/label-prs.yml
  .github/workflows/publish.yml
  scripts/github-action/TESTING.md
  scripts/github-action/compute-labels.js
  scripts/github-action/create-github-release.js
  scripts/github-action/pr-event.json
Labels: not-partner-eng-review (cloud), team:segment-core

#1973 Publish from release branch
  .github/workflows/publish.yml
  lerna.json
  packages/destination-actions/package.json
  packages/destination-actions/src/destinations/1plusx/index.ts
  scripts/release.sh
Labels: team:segment-core, mode:cloud

#1969 retlOnMappingSave Hook
  packages/core/src/destination-kit/action.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/generated-types.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/constants.ts
  packages/destination-actions/src/destinations/marketo-static-lists/functions.ts
  packages/destination-actions/src/destinations/marketo-static-lists/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/properties.ts
  packages/destination-actions/src/destinations/marketo-static-lists/removeFromList/generated-types.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push, actions:core

#1972 Fix NPM URL link in changelog
  scripts/github-action/create-github-release.js
  scripts/postversion.sh
Labels: not-partner-eng-review (cloud), team:segment-core

#1980 Trim AdvertiserID values
  packages/destination-actions/src/destinations/display-video-360/__tests__/index.test.ts
  packages/destination-actions/src/destinations/display-video-360/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#1978 Update action name
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/index.ts
Labels: Ready for Release, mode:cloud, team:segment

#1985 [Braze] Add US-09 Endpoint
  packages/browser-destinations/destinations/braze/src/index.ts
  packages/destination-actions/src/destinations/braze/index.ts
Labels: mode:cloud, team:external, mode:device

#1983 Pass along context to all Ripe methods
  packages/browser-destinations/destinations/ripe/src/group/__tests__/index.test.ts
  packages/browser-destinations/destinations/ripe/src/group/generated-types.ts
  packages/browser-destinations/destinations/ripe/src/group/index.ts
  packages/browser-destinations/destinations/ripe/src/identify/__tests__/index.test.ts
  packages/browser-destinations/destinations/ripe/src/identify/generated-types.ts
  packages/browser-destinations/destinations/ripe/src/identify/index.ts
  packages/browser-destinations/destinations/ripe/src/page/__tests__/index.test.ts
  packages/browser-destinations/destinations/ripe/src/page/generated-types.ts
  packages/browser-destinations/destinations/ripe/src/page/index.ts
  packages/browser-destinations/destinations/ripe/src/track/__tests__/index.test.ts
  packages/browser-destinations/destinations/ripe/src/track/generated-types.ts
  packages/browser-destinations/destinations/ripe/src/track/index.ts
  packages/browser-destinations/destinations/ripe/src/types.ts
Labels: deploy:push, team:external, mode:device

#1937 Update TikTok Pixel Destination
  packages/browser-destinations/destinations/tiktok-pixel/src/common_fields.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/generated-types.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/index.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/init-script.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/formatter.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/generated-types.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/index.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/types.ts
Labels: Ready for Release, partner-eng-review (device), deploy:push, team:external, mode:device

#1991 Fix build by updating types for tiktok and increasing web bundle size limit
  packages/browser-destinations/destinations/tiktok-pixel/src/generated-types.ts
  packages/browser-destinations/package.json
Labels: team:segment-core, deploy:push, mode:device

#1981 [FIX] Timeout errors are not being retried
  packages/destination-actions/src/destinations/engage/utils/EngageActionPerformer.ts
  packages/destination-actions/src/destinations/engage/utils/ResponseError.ts
Labels: partner-eng-review (cloud), mode:cloud, team:segment

#1962 [STRATCONN-3588] | Fixed Hubspot Action destination reauthorisation issue
  packages/destination-actions/src/destinations/hubspot/upsertCustomObjectRecord/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertCustomObjectRecord/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#1982 [Stratconn 3726 ]- Fixed re-authorisation issue in Google Ads Conversion.
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/functions.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#1979 Allow builders to conditionally show settings + implementation for Kafka
  packages/core/src/destination-kit/types.ts
  packages/destination-actions/src/destinations/kafka/index.ts
  packages/destination-actions/src/destinations/kafka/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push, actions:core

#1953 [Moloco-RMP] Rename RMP to MCM, Restoring test cases
  packages/destination-actions/src/destinations/moloco-rmp/__tests__/convert.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/addToCart/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/moloco-rmp/addToCart/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/addToCart/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/addToWishlist/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/common/convert.ts
  packages/destination-actions/src/destinations/moloco-rmp/common/payload/moloco.ts
  packages/destination-actions/src/destinations/moloco-rmp/home/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/moloco-rmp/home/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/home/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/index.ts
  packages/destination-actions/src/destinations/moloco-rmp/itemPageView/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/moloco-rmp/itemPageView/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/itemPageView/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/land/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/moloco-rmp/land/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/land/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/pageView/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/moloco-rmp/pageView/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/pageView/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/purchase/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/moloco-rmp/purchase/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/purchase/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/search/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/moloco-rmp/search/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/search/__tests__/snapshot.test.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#1988 Move event name field, update required fields for StackAdapt destination
  packages/destination-actions/src/destinations/stackadapt/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/stackadapt/forwardEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/stackadapt/forwardEvent/generated-types.ts
  packages/destination-actions/src/destinations/stackadapt/forwardEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#1977 Xtremepush Actions Destination
  packages/destination-actions/src/destinations/xtremepush/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/xtremepush/__tests__/index.test.ts
  packages/destination-actions/src/destinations/xtremepush/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/xtremepush/generated-types.ts
  packages/destination-actions/src/destinations/xtremepush/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/xtremepush/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/xtremepush/identify/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/xtremepush/identify/generated-types.ts
  packages/destination-actions/src/destinations/xtremepush/identify/index.ts
  packages/destination-actions/src/destinations/xtremepush/index.ts
  packages/destination-actions/src/destinations/xtremepush/track/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/xtremepush/track/__tests__/index.test.ts
  packages/destination-actions/src/destinations/xtremepush/track/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/xtremepush/track/generated-types.ts
  packages/destination-actions/src/destinations/xtremepush/track/index.ts
Labels: partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#1975 Spiffy.AI destination
  packages/destination-actions/src/destinations/spiffy/__tests__/index.test.ts
  packages/destination-actions/src/destinations/spiffy/generated-types.ts
  packages/destination-actions/src/destinations/spiffy/index.ts
  packages/destination-actions/src/destinations/spiffy/send/__tests__/index.test.ts
  packages/destination-actions/src/destinations/spiffy/send/generated-types.ts
  packages/destination-actions/src/destinations/spiffy/send/index.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#1943 [Snap] v3 additional fields
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
  packages/destination-actions/src/destinations/snap-conversions-api/index.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/generated-types.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-input-fields-deprecated.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-input-fields-v3.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-v3.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/utils.ts
  packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
Labels: partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#1993 [STRATCONN] 3634 - Klaviyo orderComplete Action Bug Fixed
  packages/browser-destinations/destinations/tiktok-pixel/src/common_fields.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/generated-types.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/index.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/init-script.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/formatter.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/generated-types.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/index.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/types.ts
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/index.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/index.ts
  packages/destination-actions/src/destinations/klaviyo/types.ts
Labels: mode:cloud, deploy:push, team:segment, mode:device

#2002 Adding 'Segment' to TT Pixel change
  packages/browser-destinations/destinations/tiktok-pixel/src/init-script.ts
Labels: team:segment-core, mode:device

#1998 Wisepops - Support for new goal tracking function
  packages/browser-destinations/destinations/wisepops/src/index.ts
  packages/browser-destinations/destinations/wisepops/src/trackGoal/__tests__/index.test.ts
  packages/browser-destinations/destinations/wisepops/src/trackGoal/generated-types.ts
  packages/browser-destinations/destinations/wisepops/src/trackGoal/index.ts
Labels: partner-eng-review (cloud), deploy:push, team:external, mode:device

#1990 feat(screeb): identify on init
  packages/browser-destinations/destinations/screeb/src/index.ts
Labels: Ready for Release, team:external, mode:device

#1957 Update user_hash mapping
  packages/browser-destinations/destinations/intercom/src/identifyUser/index.ts
Labels: partner-eng-review (device), team:segment, mode:device, KCS

#2004 [STRATCONN-3725] - Fixes request-client tests by upgrading dependency
  yarn.lock
Labels: team:segment-core

#1999 [KAMELEOON] added type property for every event
  packages/destination-actions/src/destinations/kameleoon/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/kameleoon/group/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/kameleoon/group/generated-types.ts
  packages/destination-actions/src/destinations/kameleoon/group/index.ts
  packages/destination-actions/src/destinations/kameleoon/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/kameleoon/identify/generated-types.ts
  packages/destination-actions/src/destinations/kameleoon/identify/index.ts
  packages/destination-actions/src/destinations/kameleoon/page/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/kameleoon/page/generated-types.ts
  packages/destination-actions/src/destinations/kameleoon/page/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2001 Update name to remove the space
  packages/destination-actions/src/destinations/chartmogul/index.ts
Labels: partner-eng-review (cloud), mode:cloud, team:segment

#1994 [Stratconn 3718] Add Remove Profile
  packages/destination-actions/src/destinations/klaviyo/index.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#1966 [STRATCONN-3621] - Updated Liveramp's audience key label and description
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/generated-types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/generated-types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#1939 [STRATCONN- 3664] Add mapping for messageId
  packages/destination-actions/src/destinations/segment/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/segment-properties.ts
  packages/destination-actions/src/destinations/segment/sendGroup/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendGroup/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendGroup/index.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendIdentify/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/index.ts
  packages/destination-actions/src/destinations/segment/sendPage/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendPage/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendPage/index.ts
  packages/destination-actions/src/destinations/segment/sendScreen/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendScreen/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendScreen/index.ts
  packages/destination-actions/src/destinations/segment/sendTrack/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendTrack/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendTrack/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2003 TikTok Conversions API migration
  packages/destination-actions/src/destinations/tiktok-conversions/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-conversions/common_fields.ts
  packages/destination-actions/src/destinations/tiktok-conversions/formatter.ts
  packages/destination-actions/src/destinations/tiktok-conversions/index.ts
  packages/destination-actions/src/destinations/tiktok-conversions/reportWebEvent/formatter.ts
  packages/destination-actions/src/destinations/tiktok-conversions/reportWebEvent/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-conversions/reportWebEvent/index.ts
  packages/destination-actions/src/destinations/tiktok-conversions/utils.ts
Labels: partner-eng-review (cloud)

#1992 Enhancements
  packages/destination-actions/src/destinations/responsys/generated-types.ts
  packages/destination-actions/src/destinations/responsys/index.ts
  packages/destination-actions/src/destinations/responsys/sendAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/responsys/sendAudience/generated-types.ts
  packages/destination-actions/src/destinations/responsys/sendAudience/index.ts
  packages/destination-actions/src/destinations/responsys/sendCustomTraits/generated-types.ts
  packages/destination-actions/src/destinations/responsys/sendCustomTraits/index.ts
  packages/destination-actions/src/destinations/responsys/utils.ts
Labels: partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2014 CHANNELS-1125 - Bypass SendGrid IP block
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2009 [EN-1017] Adds transform directives
  packages/core/src/mapping-kit/README.md
  packages/core/src/mapping-kit/__tests__/index.iso.test.ts
  packages/core/src/mapping-kit/index.ts
  packages/core/src/mapping-kit/validate.ts
  packages/core/src/mapping-kit/value-keys.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, actions:core

#2007 [marketo-static-lists] Improved error handling for the List Creation Hook
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/functions.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#1987 Dynamic Yield: turning Destination into Audience Destination
  packages/destination-actions/src/destinations/dynamic-yield-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/constants.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/generated-types.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/helpers.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/types.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/types.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#1971 Add Subscribe Profile Action to Klaviyo destination
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/index.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/types.ts
  packages/destination-actions/src/destinations/klaviyo/unsubscribeProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/unsubscribeProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/unsubscribeProfile/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2017 Reduce the browser bundle limit to 151 kb from 160 kb
  packages/browser-destinations/package.json
Labels: team:segment-core
