Repository segmentio/action-destinations, pull requests merged in 2024-10, with the labels that each got.

#2462 [STRATCONN-4208] - Updates PR template with instructions for backward compatibility and regression testing
  .github/PULL_REQUEST_TEMPLATE.md
Labels: not-partner-eng-review (cloud), team:segment-core

#2467 Reddit Audiences - refreshAccessToken fix
  packages/destination-actions/src/destinations/postscript/const.ts
  packages/destination-actions/src/destinations/postscript/types.ts
  packages/destination-actions/src/destinations/reddit-audiences/index.ts
Labels: partner-eng-review (cloud), mode:cloud, team:external

#2464 Allow mailingLists in traits
  packages/destination-actions/src/destinations/loops/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/loops/createOrUpdateContact/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/loops/createOrUpdateContact/__tests__/index.test.ts
  packages/destination-actions/src/destinations/loops/createOrUpdateContact/generated-types.ts
  packages/destination-actions/src/destinations/loops/createOrUpdateContact/index.ts
Labels: partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2463 Export Multi-status Result type
  packages/core/src/destination-kit/index.ts
  packages/core/src/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, actions:core

#2465 [Pinterest Audiences] Fix testAuthentication method sample payload.
  packages/destination-actions/src/destinations/pinterest-conversions/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2457 [STRATCONN-4203] Add new operator "number_not_equals" for number
  packages/destination-subscriptions/src/__tests__/generate-fql.test.ts
  packages/destination-subscriptions/src/__tests__/validate.test.ts
  packages/destination-subscriptions/src/generate-fql.ts
  packages/destination-subscriptions/src/parse-fql.ts
  packages/destination-subscriptions/src/types.ts
  packages/destination-subscriptions/src/validate.ts
Labels: Ready for Release, not-partner-eng-review (cloud), actions:core, team:segment

#2471 Remove checkout PR branch from required-field-check
  .github/workflows/required-field-check.yml
Labels: not-partner-eng-review (cloud), team:segment-core

#2468 Reddit-CAPI: hashing conversion_id & separating hashEmail function
  packages/destination-actions/src/destinations/reddit-conversions-api/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/reddit-conversions-api/__tests__/index.test.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/customEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/reddit-conversions-api/standardEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/reddit-conversions-api/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2461 Iterable Lists bugfix: cloned response hangs operations between this Destination and Iterable
  packages/destination-actions/src/destinations/iterable-lists/__tests__/index.test.ts
  packages/destination-actions/src/destinations/iterable-lists/index.ts
  packages/destination-actions/src/destinations/iterable-lists/syncAudience/iterable-client.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#2456 Remove the track event subscribe
  packages/destination-actions/src/destinations/customerio/index.ts
  packages/destination-actions/src/destinations/customerio/trackEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2407 STRATCONN-4169 | Events to Klaviyo destination is failing for delivery
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/index.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2422 Update type of content id to string from number
  packages/destination-actions/src/destinations/pinterest-conversions/pinterest-capi-custom-data.ts
  packages/destination-actions/src/destinations/pinterest-conversions/reportConversionEvent/generated-types.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2459 [Marketo] Reduce batch_size for remove action
  packages/destination-actions/src/destinations/marketo-static-lists/removeFromList/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2460 [Google Enhanced Conversions] Bump default API version from v15 to v17.
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2472 [S3] - Bug fix and tests
  packages/destination-actions/src/destinations/s3/functions.ts
  packages/destination-actions/src/destinations/s3/syncToS3/__tests__/index.test.ts
  packages/destination-actions/src/destinations/s3/types.ts
Labels: team:segment-core, mode:cloud

#2475 add batch_size column name
  packages/destination-actions/src/destinations/s3/fields.ts
  packages/destination-actions/src/destinations/s3/functions.ts
  packages/destination-actions/src/destinations/s3/syncToS3/__tests__/index.test.ts
  packages/destination-actions/src/destinations/s3/syncToS3/generated-types.ts
Labels: partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2423 [Braze] Add MultiStatus Response support
  packages/destination-actions/src/destinations/braze/__tests__/multistatus.test.ts
  packages/destination-actions/src/destinations/braze/trackEvent2/index.ts
  packages/destination-actions/src/destinations/braze/trackPurchase2/index.ts
  packages/destination-actions/src/destinations/braze/updateUserProfile2/index.ts
  packages/destination-actions/src/destinations/braze/utils.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2483 fix gitleaks-rules.toml
  .husky/gitleaks-rules.toml
Labels: team:segment

#2486 Remove mention of RETL from Sync Mode description
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2478 [MAIN] [STRATCONN] 4146 Facebook Anon_id and MadId added in Action Field
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/addToCart.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/addToCart2.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/app-data.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/addToCart/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/addToCart2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/custom/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/custom2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-app-data.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-user-data.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/initiateCheckout/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/initiateCheckout2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/pageView/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/pageView2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/purchase/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/purchase2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/search/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/search2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/viewContent/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/viewContent2/generated-types.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2482 [s3] bump max batch size to 10_000
  packages/destination-actions/src/destinations/s3/fields.ts
  packages/destination-actions/src/destinations/s3/functions.ts
  packages/destination-actions/src/destinations/s3/index.ts
  packages/destination-actions/src/destinations/s3/syncToS3/generated-types.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2332 [Optimizely Web] - New Destination
  packages/destination-actions/src/destinations/optimizely-web/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-web/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/optimizely-web/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-web/index.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/__tests__/page.test.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/__tests__/track.test.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/client.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/constants.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/fields.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/index.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/types.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, team:segment-core, mode:cloud, deploy:push

#2480 AAD-427 Fix group call: pass through userId and anonymousId
  packages/destination-actions/src/destinations/accoil-analytics/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/group/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/group/__tests__/index.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/group/generated-types.ts
  packages/destination-actions/src/destinations/accoil-analytics/group/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2487 renaming optimizely web so it can be registered
  packages/destination-actions/src/destinations/optimizely-web/index.ts
Labels: team:segment-core, mode:cloud

#2488 registering 2 new destinations
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2334 Add oauth2 for webhook2.0
  packages/core/src/__tests__/schema-validation.test.ts
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/index.ts
  packages/core/src/schema-validation.ts
  packages/destination-actions/src/destinations/webhook-extensible/__test__/webhook.test.ts
  packages/destination-actions/src/destinations/webhook-extensible/index.ts
  packages/destination-actions/src/destinations/webhook-extensible/send/index.ts
  packages/destination-actions/src/destinations/webhook-extensible/types.ts
  yarn.lock
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, actions:core, team:segment

#2491 fixing personas reference in createAudience
  packages/destination-actions/src/destinations/dynamic-yield-audiences/index.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#2496 Add supports_conversions flag to Google Enhanced conversions
  packages/destination-actions/src/destinations/google-enhanced-conversions/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/types.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2379 [STRATCONN-4133] Add batch_size to actions-mixpanel
  packages/destination-actions/src/destinations/mixpanel/mixpanel-properties.ts
  packages/destination-actions/src/destinations/mixpanel/trackEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/mixpanel/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/mixpanel/trackPurchase/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/mixpanel/trackPurchase/generated-types.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2504 [Required Field Check] Fixes syntax error while printing out required field changes
  .github/workflows/required-field-check.yml
Labels: team:segment-core

#2499 Add flagon support to Audience methods
  packages/core/src/destination-kit/index.ts
Labels: Ready for Release, team:segment-core, actions:core

#2494 [linkedin-audiences] Update version of linkedin APIs
  packages/destination-actions/src/destinations/linkedin-audiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/linkedin-audiences/api/index.ts
  packages/destination-actions/src/destinations/linkedin-audiences/constants.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/__tests__/index.test.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2481 [Klaviyo] Convert Phone Numbers to E.164
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
  packages/destination-actions/src/destinations/klaviyo/config.ts
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/index.ts
  packages/destination-actions/src/destinations/klaviyo/properties.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/index.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/index.ts
  packages/destination-actions/src/destinations/klaviyo/unsubscribeProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/unsubscribeProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/unsubscribeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2502 Mantle: add platform plan name option to identify
  packages/destination-actions/src/destinations/mantle/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/mantle/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/mantle/identify/generated-types.ts
  packages/destination-actions/src/destinations/mantle/identify/index.ts
Labels: partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2477 Add API versioning to Customer Match User List
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2466 [Recombee (Actions)] Fix bugs, improve descriptions
  packages/destination-actions/src/destinations/recombee/deleteBookmark/index.ts
  packages/destination-actions/src/destinations/recombee/deleteCartAddition/generated-types.ts
  packages/destination-actions/src/destinations/recombee/deleteCartAddition/index.ts
  packages/destination-actions/src/destinations/recombee/setViewPortion/generated-types.ts
  packages/destination-actions/src/destinations/recombee/setViewPortion/index.ts
  packages/destination-actions/src/destinations/recombee/setViewPortionFromWatchTime/generated-types.ts
  packages/destination-actions/src/destinations/recombee/setViewPortionFromWatchTime/index.ts
Labels: partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2507 Upgrade lerna and nx
  .github/workflows/ext.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish.yml
  .github/workflows/version-packages.yml
  .gitignore
  lerna.json
  nx.json
  package.json
  yarn.lock
Labels: team:segment-core

#2509 Fix version packages workflow
  .github/workflows/version-packages.yml
Labels: team:segment-core

#2512 Fixes failing browser tests by mocking intercom script
  .github/workflows/ext.yml
  packages/browser-destinations/destinations/intercom/src/__tests__/index.test.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:device

#2517 [Hubspot] Custom Object V2 - bug fix for textarea field type
  packages/destination-actions/src/destinations/hubspot/upsertObject/types.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2500 [PE-103] Update group action to use created_at as a reserved key
  packages/destination-actions/src/destinations/mixpanel/groupIdentifyUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/mixpanel/groupIdentifyUser/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#2497 [MAIN] [STRATCONN] Change condition in braze web destinations
  packages/browser-destinations/destinations/braze/src/__tests__/trackPurchase.test.ts
  packages/browser-destinations/destinations/braze/src/trackPurchase/index.ts
Labels: Ready for Release, not-partner-eng-review (device), team:segment, mode:device

#2522 [DO NOT PUSH TO PROD] - S3 batch id settings
  packages/destination-actions/src/destinations/s3/functions.ts
  packages/destination-actions/src/destinations/s3/syncToS3/index.ts
Labels: mode:cloud, team:segment

#2524 [DO NOT PUSH TO PROD] - syncId as new field
  packages/destination-actions/src/destinations/klaviyo/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/s3/fields.ts
  packages/destination-actions/src/destinations/s3/functions.ts
  packages/destination-actions/src/destinations/s3/syncToS3/generated-types.ts
  packages/destination-actions/src/destinations/s3/syncToS3/index.ts
Labels: mode:cloud, deploy:push, team:segment

#2521 [STRATCONN-4282] Braze validation and multi-status fix
  packages/destination-actions/src/destinations/braze/__tests__/__snapshots__/braze.test.ts.snap
  packages/destination-actions/src/destinations/braze/__tests__/multistatus.test.ts
  packages/destination-actions/src/destinations/braze/utils.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2527 Updated error types in Framework and Braze
  packages/browser-destinations/package.json
  packages/core/src/__tests__/batching.test.ts
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/types.ts
  packages/core/src/errors.ts
  packages/core/src/index.ts
  packages/destination-actions/src/destinations/braze/__tests__/multistatus.test.ts
  packages/destination-actions/src/destinations/braze/utils.ts
Labels: team:segment-core, mode:cloud, actions:core

#2538 Fix Faulty Test cases
  packages/destination-actions/src/destinations/hyperengage/__tests__/validateInput.test.ts
Labels: team:segment-core, mode:cloud

#2534 [Podscribe] - Update destination fields
  packages/destination-actions/src/destinations/podscribe/track/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/podscribe/track/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2402 First Party DV360 Actions PR
  packages/destination-actions/src/destinations/first-party-dv360/_tests_/index.test.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToAudContactInfo/generated-types.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToAudContactInfo/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToAudMobileDeviceId/generated-types.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToAudMobileDeviceId/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToList/generated-types.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToList/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/functions.ts
  packages/destination-actions/src/destinations/first-party-dv360/generated-types.ts
  packages/destination-actions/src/destinations/first-party-dv360/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/properties.ts
  packages/destination-actions/src/destinations/first-party-dv360/removeFromAudContactInfo/generated-types.ts
  packages/destination-actions/src/destinations/first-party-dv360/removeFromAudContactInfo/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/removeFromAudMobileDeviceId/generated-types.ts
  packages/destination-actions/src/destinations/first-party-dv360/removeFromAudMobileDeviceId/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2531 [Hubspot] - stratconn 4288 - handle empty string and null properties
  packages/destination-actions/src/destinations/hubspot/customEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/__tests__/validate.test.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/functions/cache-functions.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/functions/dynamic-field-functions.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/functions/event-completion-functions.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/functions/hubspot-event-schema-functions.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/functions/schema-functions.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/functions/validation-functions.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/index.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/update-no-matching-object.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/update-no-matching-record.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/update-some-properties-matching.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/upsert-all-properties-matching-with-cache.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/upsert-all-properties-matching.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/upsert-no-matching-object.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/upsert-property-mismatch.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/validate.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/client.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/cache-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/dynamic-field-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/hubspot-association-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/hubspot-properties-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/hubspot-record-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/schema-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/validation-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/index.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/types.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2529 [SingleStore] - adding new Singlestore Destination
  packages/destination-actions/src/destinations/singlestore/const.ts
  packages/destination-actions/src/destinations/singlestore/generated-types.ts
  packages/destination-actions/src/destinations/singlestore/index.ts
  packages/destination-actions/src/destinations/singlestore/send/__tests__/index.test.ts
  packages/destination-actions/src/destinations/singlestore/send/generated-types.ts
  packages/destination-actions/src/destinations/singlestore/send/index.ts
  packages/destination-actions/src/destinations/singlestore/types.ts
  packages/destination-actions/src/destinations/singlestore/util.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, team:segment-core, mode:cloud, deploy:push

#2511 [Iterable Lists] Adding logic to not create an audience if an existing audience already exists with the same name.
  packages/destination-actions/src/destinations/iterable-lists/__tests__/index.test.ts
  packages/destination-actions/src/destinations/iterable-lists/index.ts
  packages/destination-actions/src/destinations/iterable-lists/types.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#2533 [Sendgrid] - sendgrid new email action
  packages/destination-actions/src/destinations/sendgrid/index.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/sendgrid/sendEmail/__tests__/index.test.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/constants.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/dynamic-fields.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/fields.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/generated-types.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/index.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/types.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2542 Update getAuthToken for First Party DV360
  packages/destination-actions/src/destinations/first-party-dv360/_tests_/index.test.ts
  packages/destination-actions/src/destinations/first-party-dv360/functions.ts
Labels: team:segment-core, mode:cloud

#2544 Update LiveRamp generateFile
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/operations.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/operations.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud
