Repository segmentio/action-destinations, pull requests merged in 2024-01, with the labels that each got.

#1785 Updated the unit test case for linkedin-conversion
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/index.test.ts
Labels: not-partner-eng-review (cloud)

#1778 [STRATCONN] 3312 added event parameter in set Configuration fields
  packages/browser-destinations/destinations/google-analytics-4-web/package.json
  packages/browser-destinations/destinations/google-analytics-4-web/src/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
  packages/destination-actions/src/destinations/engage-messaging-sendgrid/previewApiLookup.types.ts
  packages/destination-actions/src/destinations/engage-messaging-sendgrid/sendEmail.types.ts
Labels: Ready for Release, not-partner-eng-review (device)

#1775 STRATCONN-3322 added condition on config of setConfiguratioField file
  packages/browser-destinations/destinations/google-analytics-4-web/src/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
Labels: Ready for Release, not-partner-eng-review (device)

#1732 Add computation id and audience id to engage stats
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/actionDefinition.ts
  packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/actionDefinition.ts
  packages/destination-actions/src/destinations/engage/twilio/sendSms/actionDefinition.ts
  packages/destination-actions/src/destinations/engage/twilio/sendWhatsApp/actionDefinition.ts
  packages/destination-actions/src/destinations/engage/utils/EngageStats.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1784 New Cloud Destination for Kevel
  packages/destination-actions/src/destinations/kevel/generated-types.ts
  packages/destination-actions/src/destinations/kevel/index.ts
  packages/destination-actions/src/destinations/kevel/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/kevel/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/kevel/syncAudience/index.ts
  packages/destination-actions/src/destinations/kevel/syncTraits/__tests__/index.test.ts
  packages/destination-actions/src/destinations/kevel/syncTraits/generated-types.ts
  packages/destination-actions/src/destinations/kevel/syncTraits/index.ts
Labels: Ready for Release

#1781 Add additional field for update_users_from_events
  packages/destination-actions/src/destinations/moengage/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/moengage/identifyUser/index.ts
  packages/destination-actions/src/destinations/moengage/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/moengage/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/moengage/trackEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1773 [Marketo Static Lists] Enhancements
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/generated-types.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/functions.ts
  packages/destination-actions/src/destinations/marketo-static-lists/properties.ts
  packages/destination-actions/src/destinations/marketo-static-lists/removeFromList/generated-types.ts
  packages/destination-actions/src/destinations/marketo-static-lists/removeFromList/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1789 Add Aggregations.io Destination
  packages/destination-actions/src/destinations/aggregations-io/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/aggregations-io/__tests__/index.test.ts
  packages/destination-actions/src/destinations/aggregations-io/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/aggregations-io/generated-types.ts
  packages/destination-actions/src/destinations/aggregations-io/index.ts
  packages/destination-actions/src/destinations/aggregations-io/send/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/aggregations-io/send/__tests__/index.test.ts
  packages/destination-actions/src/destinations/aggregations-io/send/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/aggregations-io/send/generated-types.ts
  packages/destination-actions/src/destinations/aggregations-io/send/index.ts
Labels: partner-eng-review (cloud)

#1787 Display and Video 360 Enhancements
  packages/destination-actions/src/destinations/display-video-360/addToAudience/generated-types.ts
  packages/destination-actions/src/destinations/display-video-360/properties.ts
  packages/destination-actions/src/destinations/display-video-360/proto/protofile.ts
  packages/destination-actions/src/destinations/display-video-360/removeFromAudience/generated-types.ts
  packages/destination-actions/src/destinations/display-video-360/shared.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1788 [STRATCONN-3091] - [Segment] - Cleanup flagon from internal TAPI rollout
  packages/destination-actions/src/destinations/segment/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/segment/generated-types.ts
  packages/destination-actions/src/destinations/segment/index.ts
  packages/destination-actions/src/destinations/segment/properties.ts
  packages/destination-actions/src/destinations/segment/sendGroup/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendGroup/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendGroup/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/segment/sendGroup/index.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendIdentify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/index.ts
  packages/destination-actions/src/destinations/segment/sendPage/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendPage/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendPage/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/segment/sendPage/index.ts
  packages/destination-actions/src/destinations/segment/sendScreen/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendScreen/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendScreen/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/segment/sendScreen/index.ts
  packages/destination-actions/src/destinations/segment/sendTrack/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendTrack/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendTrack/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/segment/sendTrack/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1799 Marketo Access Token Expired
  packages/destination-actions/src/destinations/marketo-static-lists/functions.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1798 [LinkedIn CAPI] Addresses socket hangup issues
  packages/destination-actions/src/destinations/aggregations-io/send/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1792 [STRATCONN-3091] - [Segment Profiles] - Feature gate Cleanup
  packages/destination-actions/src/destinations/segment-profiles/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/segment-profiles/generated-types.ts
  packages/destination-actions/src/destinations/segment-profiles/index.ts
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/index.ts
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/index.ts
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1780 Update linkedin API version to 202311
  packages/destination-actions/src/destinations/linkedin-audiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/linkedin-audiences/constants.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/__tests__/__snapshots__/snapshot.test.ts.snap
Labels: Ready for Release, not-partner-eng-review (cloud)

#1722 Added preset for braze journeyStep
  packages/core/package.json
  packages/destination-actions/src/destinations/braze/__tests__/braze.test.ts
  packages/destination-actions/src/destinations/braze/index.ts
  yarn.lock
Labels: Ready for Release, not-partner-eng-review (cloud)

#1802 adding new Action for Mixpanel
  packages/destination-actions/src/destinations/mixpanel/incrementProperties/__test__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/mixpanel/incrementProperties/__test__/index.test.ts
  packages/destination-actions/src/destinations/mixpanel/incrementProperties/__test__/snapshot.test.ts
  packages/destination-actions/src/destinations/mixpanel/incrementProperties/generated-types.ts
  packages/destination-actions/src/destinations/mixpanel/incrementProperties/index.ts
  packages/destination-actions/src/destinations/mixpanel/index.ts
  packages/destination-actions/src/destinations/mixpanel/mixpanel-types.ts
Labels: partner-eng-review (cloud)

#1786 [PINT-2052_2] - Add SMS registration and named user association
  packages/destination-actions/src/destinations/airship/registerAndAssociate/generated-types.ts
  packages/destination-actions/src/destinations/airship/registerAndAssociate/index.ts
  packages/destination-actions/src/destinations/airship/utilities.ts
Labels: partner-eng-review (cloud)

#1731 Updated Criteo API version (2023-01 -> 2023-10)
  packages/destination-actions/src/destinations/criteo-audiences/addUserToAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/criteo-audiences/addUserToAudience/index.ts
  packages/destination-actions/src/destinations/criteo-audiences/criteo-audiences.ts
  packages/destination-actions/src/destinations/criteo-audiences/removeUserFromAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/criteo-audiences/removeUserFromAudience/index.ts
Labels: partner-eng-review (cloud)

#1791 Algolia Hybrid Plugin
  packages/browser-destinations/destinations/algolia-plugins/README.md
  packages/browser-destinations/destinations/algolia-plugins/package.json
  packages/browser-destinations/destinations/algolia-plugins/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/algolia-plugins/src/algoliaPlugin/generated-types.ts
  packages/browser-destinations/destinations/algolia-plugins/src/algoliaPlugin/index.ts
  packages/browser-destinations/destinations/algolia-plugins/src/generated-types.ts
  packages/browser-destinations/destinations/algolia-plugins/src/index.ts
  packages/browser-destinations/destinations/algolia-plugins/src/utils.ts
  packages/browser-destinations/destinations/algolia-plugins/tsconfig.json
  packages/destination-actions/src/destinations/algolia-insights/conversionEvents/index.ts
  packages/destination-actions/src/destinations/algolia-insights/index.ts
  packages/destination-actions/src/destinations/algolia-insights/productAddedEvents/index.ts
  packages/destination-actions/src/destinations/algolia-insights/productClickedEvents/index.ts
  packages/destination-actions/src/destinations/algolia-insights/productListFilteredEvents/index.ts
  packages/destination-actions/src/destinations/algolia-insights/productViewedEvents/index.ts
  packages/destinations-manifest/package.json
  packages/destinations-manifest/src/index.ts
Labels: partner-eng-review (cloud), partner-eng-review (device)

#1795 Acoustic - Improve Error Messaging
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/__tests__/index.test.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/__tests__/preCheck.test.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/eventprocessing.ts
  packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/preCheck.ts
Labels: partner-eng-review (cloud)

#1793 Add Survicate
  packages/browser-destinations/destinations/survicate/README.md
  packages/browser-destinations/destinations/survicate/package.json
  packages/browser-destinations/destinations/survicate/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/survicate/src/generated-types.ts
  packages/browser-destinations/destinations/survicate/src/identifyGroup/generated-types.ts
  packages/browser-destinations/destinations/survicate/src/identifyGroup/index.ts
  packages/browser-destinations/destinations/survicate/src/identifyUser/generated-types.ts
  packages/browser-destinations/destinations/survicate/src/identifyUser/index.ts
  packages/browser-destinations/destinations/survicate/src/index.ts
  packages/browser-destinations/destinations/survicate/src/trackEvent/generated-types.ts
  packages/browser-destinations/destinations/survicate/src/trackEvent/index.ts
  packages/browser-destinations/destinations/survicate/src/types.ts
  packages/browser-destinations/destinations/survicate/tsconfig.json
Labels: partner-eng-review (device)

#1804 [STRATCONN-3328] [GA4] Added additionalProperties in GA4
  packages/browser-destinations/destinations/google-analytics-4-web/src/addPaymentInfo/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/addToCart/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/addToWishlist/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/beginCheckout/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/ga4-properties.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/purchase/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/refund/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/removeFromCart/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/selectItem/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/selectPromotion/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/viewCart/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/viewItem/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/viewItemList/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/viewPromotion/generated-types.ts
Labels: Ready for Release, not-partner-eng-review (device)

#1808 Add size check to browser destination CI
  .github/workflows/ci.yml
  packages/browser-destinations/package.json
  yarn.lock
Labels: not-partner-eng-review (cloud)

#1797 [ACT-1049] Update action-destinations copyright from 2023 to 2024
  README.md
  packages/actions-shared/README.md
  packages/ajv-human-errors/README.md
  packages/browser-destinations/README.md
  packages/browser-destinations/destinations/1flow/README.md
  packages/browser-destinations/destinations/cdpresolution/README.md
  packages/browser-destinations/destinations/devrev/README.md
  packages/browser-destinations/destinations/google-campaign-manager/README.md
  packages/browser-destinations/destinations/hubble-web/README.md
  packages/browser-destinations/destinations/jimo/README.md
  packages/browser-destinations/destinations/pendo-web-actions/README.md
  packages/browser-destinations/destinations/replaybird/README.md
  packages/browser-destinations/destinations/rupt/README.md
  packages/browser-destinations/destinations/snap-plugins/README.md
  packages/cli/README.md
  packages/cli/templates/destinations/browser/README.md
  packages/core/README.md
  packages/destination-actions/README.md
  packages/destination-subscriptions/README.md
Labels: not-partner-eng-review (cloud)

#1807 [STRATCONN] [GA4] added user properties in all event
  packages/browser-destinations/destinations/google-analytics-4-web/src/addPaymentInfo/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/addToCart/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/addToWishlist/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/beginCheckout/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/customEvent/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/ga4-functions.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/generateLead/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/login/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/purchase/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/refund/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/removeFromCart/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/search/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/selectItem/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/selectPromotion/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/signUp/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/viewCart/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/viewItem/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/viewItemList/index.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/viewPromotion/index.ts
Labels: Ready for Release, not-partner-eng-review (device)

#1820 [stratconn-2993] [Braze] Adds email as a user identification field
  packages/destination-actions/src/destinations/braze/__tests__/__snapshots__/braze.test.ts.snap
  packages/destination-actions/src/destinations/braze/__tests__/braze.test.ts
  packages/destination-actions/src/destinations/braze/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/braze/trackEvent/index.ts
  packages/destination-actions/src/destinations/braze/trackPurchase/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/braze/trackPurchase/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/braze/trackPurchase/generated-types.ts
  packages/destination-actions/src/destinations/braze/trackPurchase/index.ts
  packages/destination-actions/src/destinations/braze/utils.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1819 Disable full syncs for DV360
  packages/destination-actions/src/destinations/display-video-360/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1814 [LinkedIn CAPI] Update the adAccountId dynamic field to return account name as the label
  packages/destination-actions/src/destinations/linkedin-conversions/api/api.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/api/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/types.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1812 [Aggregations.io] Add error handling for auth
  packages/destination-actions/src/destinations/aggregations-io/index.ts
  packages/destination-actions/src/destinations/aggregations-io/types.ts
Labels: enhancement, Ready for Release, partner-eng-review (cloud)

#1824 Criteo-Audiences unhandled error fix
  packages/destination-actions/src/destinations/criteo-audiences/criteo-audiences.ts
Labels: partner-eng-review (cloud)

#1815 add @json directive + tests
  packages/core/src/mapping-kit/__tests__/index.iso.test.ts
  packages/core/src/mapping-kit/index.ts
  packages/core/src/mapping-kit/validate.ts
Labels: not-partner-eng-review (cloud)

#1830 Fix SMS/MMS and email with <nil> traits to display default
  packages/destination-actions/src/destinations/engage/sendgrid/__tests__/send-email.test.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-sms.test.ts
  packages/destination-actions/src/destinations/engage/twilio/utils/TwilioMessageSender.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1840 [LinkedIn CAPI] - Multiple campaign conversions (temporary workaround)
  packages/destination-actions/src/destinations/linkedin-conversions/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/api/api.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/api/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/types.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1836 Adding new SurveySparrow Integration
  packages/destination-actions/src/destinations/surveysparrow/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/surveysparrow/__tests__/index.test.ts
  packages/destination-actions/src/destinations/surveysparrow/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/surveysparrow/createContact/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/surveysparrow/createContact/__tests__/index.test.ts
  packages/destination-actions/src/destinations/surveysparrow/createContact/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/surveysparrow/createContact/generated-types.ts
  packages/destination-actions/src/destinations/surveysparrow/createContact/index.ts
  packages/destination-actions/src/destinations/surveysparrow/generated-types.ts
  packages/destination-actions/src/destinations/surveysparrow/index.ts
  packages/destination-actions/src/destinations/surveysparrow/triggerSurvey/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/surveysparrow/triggerSurvey/__tests__/index.test.ts
  packages/destination-actions/src/destinations/surveysparrow/triggerSurvey/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/surveysparrow/triggerSurvey/generated-types.ts
  packages/destination-actions/src/destinations/surveysparrow/triggerSurvey/index.ts
Labels: Ready for Release, partner-eng-review (cloud)

#1832 renaming kameleoon
  packages/destination-actions/src/destinations/kameleoon/index.ts
Labels: partner-eng-review (cloud)

#1833 remove partner slack call out
  CONTRIBUTING.md
Labels: Ready for Release, partner-eng-review (cloud)

#1826 New Integration - Schematic
  packages/destination-actions/src/destinations/schematic/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/__tests__/index.test.ts
  packages/destination-actions/src/destinations/schematic/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/schematic/generated-types.ts
  packages/destination-actions/src/destinations/schematic/identifyUser/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/identifyUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/schematic/identifyUser/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/schematic/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/schematic/identifyUser/index.ts
  packages/destination-actions/src/destinations/schematic/index.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/index.ts
Labels: partner-eng-review (cloud)

#1835 TikTok Conversions Sandbox - API migration
  packages/destination-actions/src/destinations/tiktok-conversions-sandbox/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-conversions-sandbox/common_fields.ts
  packages/destination-actions/src/destinations/tiktok-conversions-sandbox/formatter.ts
  packages/destination-actions/src/destinations/tiktok-conversions-sandbox/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-conversions-sandbox/index.ts
  packages/destination-actions/src/destinations/tiktok-conversions-sandbox/reportWebEvent/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-conversions-sandbox/reportWebEvent/index.ts
  packages/destination-actions/src/destinations/tiktok-conversions-sandbox/utils.ts
Labels: partner-eng-review (cloud)

#1827 TikTok Offline Conversions API migration
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/common_fields.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/formatter.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/index.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/reportOfflineEvent/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/reportOfflineEvent/index.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/trackNonPaymentOfflineConversion/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/trackNonPaymentOfflineConversion/index.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/trackPaymentOfflineConversion/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/trackPaymentOfflineConversion/index.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/utils.ts
Labels: partner-eng-review (cloud)

#1837 Adding new Destination: Courier
  packages/destination-actions/src/destinations/courier/generated-types.ts
  packages/destination-actions/src/destinations/courier/index.ts
  packages/destination-actions/src/destinations/courier/postToCourier/__tests__/index.test.ts
  packages/destination-actions/src/destinations/courier/postToCourier/generated-types.ts
  packages/destination-actions/src/destinations/courier/postToCourier/index.ts
Labels: partner-eng-review (cloud)

#1821 [Facebook Conversions API]-Updated Default API Version to v18
  packages/destination-actions/src/destinations/facebook-conversions-api/constants.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1846 Revert "Fix SMS/MMS and email with <nil> traits to display default"
  packages/destination-actions/src/destinations/engage/sendgrid/__tests__/send-email.test.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-sms.test.ts
  packages/destination-actions/src/destinations/engage/twilio/utils/TwilioMessageSender.ts
Labels: Ready for Release, not-partner-eng-review (cloud)
