Repository segmentio/action-destinations, pull requests merged in 2024-08, with the labels that each got.

#2236 Include optional fields in the condition
  packages/core/src/destination-kit/action.ts
Labels: team:segment-core, actions:core

#2235 Updating comp key to avoid gitleaks clash
  packages/destination-actions/src/destinations/iterable-lists/syncAudience/__tests__/index.test.ts
Labels: Ready for Release, partner-eng-review (cloud)

#2233 [Facebook Custom Audiences] Sync users to an audience
  packages/destination-actions/src/destinations/facebook-custom-audiences/__tests__/fb-operations.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/constants.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/fbca-operations.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/fbca-properties.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/__tests__/index.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/generated-types.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/index.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2197 [FB Custom Audiences] Audience Selection/Creation RETL Hook
  packages/destination-actions/src/destinations/facebook-custom-audiences/__tests__/fb-operations.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/add/__tests__/index.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/add/generated-types.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/add/index.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/constants.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/fbca-operations.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/fbca-properties.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/generated-types.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/index.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/remove/__tests__/index.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/remove/generated-types.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/remove/index.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/__tests__/index.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/generated-types.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/index.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2215 [TikTok Audiences] Remove id_type from createAudience call
  packages/destination-actions/src/destinations/tiktok-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/api/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/createAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/createAudience/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-audiences/createAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-audiences/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/properties.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2109 Customer Match User List Action
  packages/browser-destinations/webpack.config.js
  packages/core/src/hashing-utils.ts
  packages/core/src/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/userList.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push, actions:core

#2199 Add simplified mappings version of "UploadCallConversion" action
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadCallConversion2.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion2/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2201 Add simplified mappings "UploadClickConversion" action
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion2.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2202 Add simplified mappings "UploadConversionAdjustment" action
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadConversionAdjustment2.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment2/index.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2234 Register extensible Destinations
  packages/destination-actions/src/destinations/webook-extensible/__test__/webhook.test.ts
  packages/destination-actions/src/destinations/webook-extensible/generated-types.ts
  packages/destination-actions/src/destinations/webook-extensible/index.ts
  packages/destination-actions/src/destinations/webook-extensible/send/generated-types.ts
  packages/destination-actions/src/destinations/webook-extensible/send/index.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:segment

#2231 export excludeWhenNull directive check
  packages/core/src/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, actions:core

#2223 REGION: add support for vwo data region
  packages/destination-actions/src/destinations/vwo/__tests__/index.test.ts
  packages/destination-actions/src/destinations/vwo/generated-types.ts
  packages/destination-actions/src/destinations/vwo/identifyUser/index.ts
  packages/destination-actions/src/destinations/vwo/index.ts
  packages/destination-actions/src/destinations/vwo/pageVisit/index.ts
  packages/destination-actions/src/destinations/vwo/syncAudience/index.ts
  packages/destination-actions/src/destinations/vwo/trackEvent/index.ts
  packages/destination-actions/src/destinations/vwo/utility.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2136 [STRAT-3865] | Re-authentication Flow for CreateAudience and GetAudience to handle 401
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/destination-kit/index.ts
  packages/destination-actions/src/destinations/amazon-amc/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, actions:core, team:segment

#2232 restricting additional_identifiers_and_traits_columns field entry method
  packages/destination-actions/src/destinations/aws-s3/syncAudienceToCSV/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2238 removing setting for datacenter
  packages/destination-actions/src/destinations/dynamic-yield-audiences/generated-types.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/helpers.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2242 renaming extensible webhook
  packages/destination-actions/src/destinations/webook-extensible/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#2244 registering webhook-extensions
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2246 correcting folder name for webhook extensible destination
  packages/destination-actions/src/destinations/webhook-extensible/__test__/webhook.test.ts
  packages/destination-actions/src/destinations/webhook-extensible/generated-types.ts
  packages/destination-actions/src/destinations/webhook-extensible/index.ts
  packages/destination-actions/src/destinations/webhook-extensible/send/generated-types.ts
  packages/destination-actions/src/destinations/webhook-extensible/send/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2251 [Facebook Custom Audience] final touches
  packages/core/src/__tests__/hashing-utils.test.ts
  packages/core/src/hashing-utils.ts
  packages/core/src/index.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/__tests__/fb-operations.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/fbca-operations.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/index.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/__tests__/index.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/generated-types.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/index.ts
Labels: team:segment-core, mode:cloud, deploy:push, actions:core

#2262 Revert "[STRAT-3865] | Re-authentication Flow for CreateAudience and GetAudience to handle 401"
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/destination-kit/index.ts
  packages/destination-actions/src/destinations/amazon-amc/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/index.ts
Labels: team:segment-core, mode:cloud, actions:core

#2239 [STRATCONN-3888]: Reduce batch size of salesforce marketing cloud to 10
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-properties.ts
Labels: not-partner-eng-review (cloud), mode:cloud, team:segment

#2241 [Hubspot] Custom Event Action
  packages/destination-actions/src/destinations/hubspot/customEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/common-fields.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/constants.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/dynamic-fields.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/generated-types.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/hubspot-api.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/index.ts
  packages/destination-actions/src/destinations/hubspot/index.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/common-fields.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/generated-types.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/hubspot-api.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2186 Add phone number as identifier
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/properties.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/index.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/lib/test-data.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2252 schematic destination - fix company key bug
  packages/destination-actions/src/destinations/schematic/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/identifyUser/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/schematic/identifyUser/index.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2253 [MAIN] [STRATCONN-3905] Klaviyo Actions order completed.
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2268 [TOPSORT] Action destination for Topsort Events
  packages/destination-actions/src/destinations/topsort/click/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/topsort/click/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/topsort/click/__tests__/index.test.ts
  packages/destination-actions/src/destinations/topsort/click/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/topsort/click/generated-types.ts
  packages/destination-actions/src/destinations/topsort/click/index.ts
  packages/destination-actions/src/destinations/topsort/client.ts
  packages/destination-actions/src/destinations/topsort/generated-types.ts
  packages/destination-actions/src/destinations/topsort/impression/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/topsort/impression/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/topsort/impression/__tests__/index.test.ts
  packages/destination-actions/src/destinations/topsort/impression/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/topsort/impression/generated-types.ts
  packages/destination-actions/src/destinations/topsort/impression/index.ts
  packages/destination-actions/src/destinations/topsort/index.ts
  packages/destination-actions/src/destinations/topsort/purchase/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/topsort/purchase/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/topsort/purchase/__tests__/index.test.ts
  packages/destination-actions/src/destinations/topsort/purchase/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/topsort/purchase/generated-types.ts
  packages/destination-actions/src/destinations/topsort/purchase/index.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#2277 fixing hubspot tests
  packages/destination-actions/src/destinations/hubspot/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/hubspot/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/hubspot-api.ts
Labels: team:segment-core, mode:cloud

#2278 registering dawn and topsort
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2249 [STRATCONN-4075] - Enable codecov
  .github/workflows/ci.yml
  codecov.yml
Labels: not-partner-eng-review (cloud), team:segment-core

#2273 [Linkedin Conversions API] Add batching implementation
  packages/destination-actions/src/destinations/linkedin-conversions/api/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
Labels: team:segment-core, mode:cloud, deploy:push

#2283 [LinkedIn Conversions] Hidden batching fields are not required
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
Labels: team:segment-core, mode:cloud, deploy:push

#2214 [Google Sheets] Add SyncMode support
  packages/destination-actions/src/destinations/google-sheets/__tests__/postSheet2.operations.test.ts
  packages/destination-actions/src/destinations/google-sheets/index.ts
  packages/destination-actions/src/destinations/google-sheets/postSheet2/generated-types.ts
  packages/destination-actions/src/destinations/google-sheets/postSheet2/index.ts
  packages/destination-actions/src/destinations/google-sheets/postSheet2/operations2.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2306 [SEV] Remove logic to update status Pardot Actions
  packages/destination-actions/src/destinations/actions-pardot/prospects/index.ts
Labels: team:segment-core, mode:cloud

#2307 [SEV] Add type checking to statusCode
  packages/destination-actions/src/destinations/actions-pardot/prospects/index.ts
Labels: team:segment-core, mode:cloud

#2271 fix: updates the account mappings for dynamic yield destination
  packages/destination-actions/src/destinations/dynamic-yield-audiences/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2289 fix: update dynamic yield destination name
  packages/destination-actions/src/destinations/dynamic-yield-audiences/generated-types.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2281 schematic - remove locked property name for userId
  packages/destination-actions/src/destinations/schematic/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/identifyUser/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/schematic/identifyUser/index.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2211 Adding batch to events
  packages/destination-actions/src/destinations/optimizely-data-platform/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/customEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/customEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/customEvent/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/customEvent/index.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/emailEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/emailEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/emailEvent/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/emailEvent/index.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/fields.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/nonEcommCustomEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/nonEcommCustomEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/nonEcommCustomEvent/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/nonEcommCustomEvent/index.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/upsertContact/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/upsertContact/__tests__/index.test.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/upsertContact/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/upsertContact/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2290 fixing bug for sensitive props
  packages/destination-actions/src/destinations/hubspot/upsertObject/hubspot-api.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2304 bug fix
  packages/destination-actions/src/destinations/iterable-lists/__tests__/index.test.ts
  packages/destination-actions/src/destinations/iterable-lists/generated-types.ts
  packages/destination-actions/src/destinations/iterable-lists/index.ts
  packages/destination-actions/src/destinations/iterable-lists/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/iterable-lists/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/iterable-lists/syncAudience/index.ts
  packages/destination-actions/src/destinations/iterable-lists/syncAudience/iterable-client.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2302 Google Ads Customer Lists Enhancements
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2300 [STRATCONN-4058] [Salesforce] - Handle concurrent token refresh error
  packages/destination-actions/src/destinations/salesforce/__tests__/index.test.ts
  packages/destination-actions/src/destinations/salesforce/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2299 Add E.164 phone number validation to all Klaviyo actions
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/index.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/index.ts
  packages/destination-actions/src/destinations/klaviyo/unsubscribeProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/unsubscribeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2296 [Google Sheets] Remove (Simplified) from action name
  packages/destination-actions/src/destinations/google-sheets/postSheet2/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2274 [STRATCONN-3925] Set DEFAULT_VERSION to 20.0 on for Facebook Conversions API
  packages/destination-actions/src/destinations/facebook-conversions-api/constants.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2158 Updated delivr ai activate action destination from AWS S3 and SFTP server to delivr ai REST API
  packages/destination-actions/src/destinations/delivrai-activate/__tests__/index.test.ts
  packages/destination-actions/src/destinations/delivrai-activate/constants.ts
  packages/destination-actions/src/destinations/delivrai-activate/generated-types.ts
  packages/destination-actions/src/destinations/delivrai-activate/index.ts
  packages/destination-actions/src/destinations/delivrai-activate/types.ts
  packages/destination-actions/src/destinations/delivrai-activate/updateSegment/__tests__/index.test.ts
  packages/destination-actions/src/destinations/delivrai-activate/updateSegment/generated-types.ts
  packages/destination-actions/src/destinations/delivrai-activate/updateSegment/index.ts
  packages/destination-actions/src/destinations/delivrai-activate/utils-rt.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#2301 Fixing TikTok Conversions payload regarding `test_event_code`
  packages/destination-actions/src/destinations/tiktok-conversions/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-conversions/types.ts
  packages/destination-actions/src/destinations/tiktok-conversions/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#2309 Hubspot bug fixes for new Actions
  packages/destination-actions/src/destinations/hubspot/customEvent/common-fields.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/dynamic-fields.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/generated-types.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/hubspot-api.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/index.ts
  packages/destination-actions/src/destinations/hubspot/sendCustomBehavioralEvent/index.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/common-fields.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/dynamic-fields.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/hubspot-api.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/index.ts
Labels: team:segment-core, mode:cloud, deploy:push

#2311 registering delivrai-activate destination
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2316 channels-1200 fixing stats for Channels-1094
  packages/actions-shared/src/engage/utils/EngageActionPerformer.ts
  packages/actions-shared/src/engage/utils/EngageStats.ts
  packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
  packages/actions-shared/src/engage/utils/operationTracking/OperationStats.ts
Labels: team:segment

#2319 Remove hyphens from customer id in create/get Audience calls
  packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
Labels: team:segment-core, mode:cloud

#2314 fix(Jimo): update manual init label & types
  packages/browser-destinations/destinations/jimo/src/generated-types.ts
  packages/browser-destinations/destinations/jimo/src/index.ts
  packages/browser-destinations/destinations/jimo/src/sendUserData/index.ts
Labels: deploy:push, team:external, mode:device

#2321 v2 Fix for Iterable date format bug
  packages/destination-actions/src/destinations/actions-pardot/prospects/index.ts
  packages/destination-actions/src/destinations/iterable/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/iterable/utils.ts
Labels: mode:cloud, team:external

#2326 Channels-1094-refactored => staging (action-destinations)
  packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
  packages/destination-actions/package.json
  packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
Labels: mode:cloud, team:segment

#2287 [STRAT-3865] | Re-authentication Flow for CreateAudience and GetAudience to handle 401
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/destination-kit/index.ts
Labels: not-partner-eng-review (cloud), actions:core, team:segment

#2286 [STRAT-3865] | Removed getAuthToken from Amazon-amc createAudience and getAudience
  packages/destination-actions/src/destinations/amazon-amc/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/index.ts
Labels: not-partner-eng-review (cloud), mode:cloud, team:segment

#2305 fix for iterable date format bug
  packages/destination-actions/src/destinations/iterable/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/iterable/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2318 Add option for groupId in identify
  packages/browser-destinations/destinations/pendo-web-actions/src/identify/generated-types.ts
  packages/browser-destinations/destinations/pendo-web-actions/src/identify/index.ts
Labels: Ready for Release, partner-eng-review (device), deploy:push, team:external, mode:device

#2256 Reddit integration
  packages/browser-destinations/destinations/reddit-plugins/README.md
  packages/browser-destinations/destinations/reddit-plugins/package.json
  packages/browser-destinations/destinations/reddit-plugins/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/reddit-plugins/src/generated-types.ts
  packages/browser-destinations/destinations/reddit-plugins/src/index.ts
  packages/browser-destinations/destinations/reddit-plugins/src/redditPlugin/__tests__/index.test.ts
  packages/browser-destinations/destinations/reddit-plugins/src/redditPlugin/generated-types.ts
  packages/browser-destinations/destinations/reddit-plugins/src/redditPlugin/index.ts
  packages/browser-destinations/destinations/reddit-plugins/src/utils.ts
  packages/browser-destinations/destinations/reddit-plugins/tsconfig.json
  packages/destination-actions/src/destinations/reddit-conversions-api/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/reddit-conversions-api/__tests__/index.test.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/customEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/reddit-conversions-api/customEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/customEvent/generated-types.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/customEvent/index.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/fields.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/generated-types.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/index.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/standardEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/reddit-conversions-api/standardEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/standardEvent/generated-types.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/standardEvent/index.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/types.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external, mode:device

#2328 New Destination - Nextdoor
  packages/browser-destinations/destinations/nextdoor-plugins/README.md
  packages/browser-destinations/destinations/nextdoor-plugins/package.json
  packages/browser-destinations/destinations/nextdoor-plugins/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/nextdoor-plugins/src/generated-types.ts
  packages/browser-destinations/destinations/nextdoor-plugins/src/index.ts
  packages/browser-destinations/destinations/nextdoor-plugins/src/nextdoorPlugin/generated-types.ts
  packages/browser-destinations/destinations/nextdoor-plugins/src/nextdoorPlugin/index.ts
  packages/browser-destinations/destinations/nextdoor-plugins/src/utils.ts
  packages/browser-destinations/destinations/nextdoor-plugins/tsconfig.json
  packages/destination-actions/src/destinations/nextdoor-capi/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/nextdoor-capi/__tests__/index.test.ts
  packages/destination-actions/src/destinations/nextdoor-capi/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/nextdoor-capi/generated-types.ts
  packages/destination-actions/src/destinations/nextdoor-capi/index.ts
  packages/destination-actions/src/destinations/nextdoor-capi/sendConversion/generated-types.ts
  packages/destination-actions/src/destinations/nextdoor-capi/sendConversion/index.ts
  packages/destination-actions/src/destinations/nextdoor-capi/sendConversion/types.ts
  packages/destination-actions/src/destinations/nextdoor-capi/sendConversion/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), partner-eng-review (device), deploy:registration, team:segment-core, mode:cloud, deploy:push, mode:device

#2310 changing loading for jimo
  packages/browser-destinations/destinations/jimo/src/generated-types.ts
  packages/browser-destinations/destinations/jimo/src/index.ts
  packages/browser-destinations/destinations/jimo/src/init-script.ts
  packages/browser-destinations/destinations/jimo/src/sendUserData/index.ts
Labels: Ready for Release, partner-eng-review (device), team:segment-core, deploy:push, mode:device

#2335 updating snapshots for reddit
  packages/browser-destinations/destinations/pendo-web-actions/src/identify/index.ts
  packages/browser-destinations/destinations/reddit-plugins/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/reddit-plugins/src/redditPlugin/__tests__/index.test.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/reddit-conversions-api/customEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/reddit-conversions-api/standardEvent/__tests__/__snapshots__/snapshot.test.ts.snap
Labels: team:segment-core, mode:cloud, mode:device

#2336 [Evolvai] - new Web Destination
  packages/browser-destinations/destinations/evolv-ai/README.md
  packages/browser-destinations/destinations/evolv-ai/package.json
  packages/browser-destinations/destinations/evolv-ai/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/evolv-ai/src/generated-types.ts
  packages/browser-destinations/destinations/evolv-ai/src/identifyUser/__tests__/index.test.ts
  packages/browser-destinations/destinations/evolv-ai/src/identifyUser/generated-types.ts
  packages/browser-destinations/destinations/evolv-ai/src/identifyUser/index.ts
  packages/browser-destinations/destinations/evolv-ai/src/index.ts
  packages/browser-destinations/destinations/evolv-ai/src/proxy.ts
  packages/browser-destinations/destinations/evolv-ai/src/source/__tests__/indext.test.ts
  packages/browser-destinations/destinations/evolv-ai/src/source/allocations.ts
  packages/browser-destinations/destinations/evolv-ai/src/source/eventTracking.ts
  packages/browser-destinations/destinations/evolv-ai/src/source/events.ts
  packages/browser-destinations/destinations/evolv-ai/src/source/index.ts
  packages/browser-destinations/destinations/evolv-ai/src/trackEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/evolv-ai/src/trackEvent/generated-types.ts
  packages/browser-destinations/destinations/evolv-ai/src/trackEvent/index.ts
  packages/browser-destinations/destinations/evolv-ai/src/types.ts
  packages/browser-destinations/destinations/evolv-ai/src/utility.ts
  packages/browser-destinations/destinations/evolv-ai/src/wrapper.ts
  packages/browser-destinations/destinations/evolv-ai/tsconfig.json
  packages/browser-destinations/package.json
Labels: partner-eng-review (device), deploy:registration, team:segment-core, deploy:push, mode:device

#2327 update test auth to lower latency endpoint
  packages/destination-actions/src/destinations/schematic/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2339 fixing auth for contentstack cloud
  packages/browser-destinations/destinations/contentstack-web/package.json
  packages/destination-actions/src/destinations/contentstack/index.ts
  packages/destinations-manifest/package.json
Labels: team:segment-core, mode:cloud, mode:device

#2330 [MAIN] [STRATCONN] added new braze sdk verion 5.4
  packages/browser-destinations/destinations/braze/src/index.ts
Labels: Ready for Release, not-partner-eng-review (device), team:segment, mode:device

#2340 register new destination
  packages/destination-actions/src/destinations/index.ts
  packages/destinations-manifest/src/index.ts
Labels: partner-eng-review (cloud), partner-eng-review (device), team:segment-core, mode:cloud

#2265 [STRATCONN-4071] Add batching support to Google Enhanced Conversions
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadCallConversion.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadCallConversion2.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion2.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadConversionAdjustment.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadConversionAdjustment2.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/constants.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment2/index.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2285 Add batch_size fields for braze actions
  packages/destination-actions/src/destinations/braze/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/braze/trackEvent/index.ts
  packages/destination-actions/src/destinations/braze/trackPurchase/generated-types.ts
  packages/destination-actions/src/destinations/braze/trackPurchase/index.ts
  packages/destination-actions/src/destinations/braze/updateUserProfile/generated-types.ts
  packages/destination-actions/src/destinations/braze/updateUserProfile/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2315 Handle concurrent token refresh error for salesforce pardot
  packages/destination-actions/src/destinations/actions-pardot/__tests__/index.test.ts
  packages/destination-actions/src/destinations/actions-pardot/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2329 [salesforce] Removes outdated warning from 'enable_batching' field description
  packages/destination-actions/src/destinations/salesforce/account/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/cases/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/contact/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/customObject/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/lead/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/opportunity/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/sf-properties.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2344 Hubspot update 7
  packages/destination-actions/src/destinations/hubspot/upsertObject/constants.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/dynamic-fields.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/hubspot-api.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2341 Angler AI - Add saveOrder preset + bugfixes
  packages/destination-actions/src/destinations/angler-ai/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/fields/addressFields.ts
  packages/destination-actions/src/destinations/angler-ai/fields/checkoutFields.ts
  packages/destination-actions/src/destinations/angler-ai/presets.ts
  packages/destination-actions/src/destinations/angler-ai/routes.ts
  packages/destination-actions/src/destinations/angler-ai/saveCheckoutEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveCheckoutEvent/generated-types.ts
  packages/destination-actions/src/destinations/angler-ai/saveCustomEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveCustomEvent/generated-types.ts
  packages/destination-actions/src/destinations/angler-ai/saveOrder/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveOrder/__tests__/index.test.ts
  packages/destination-actions/src/destinations/angler-ai/saveOrder/generated-types.ts
  packages/destination-actions/src/destinations/angler-ai/saveOrder/index.ts
  packages/destination-actions/src/destinations/angler-ai/saveUser/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveUser/generated-types.ts
  packages/destination-actions/src/destinations/angler-ai/transformFields/transformCheckout.ts
Labels: partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2294 Refactored re-authentication flow for all execute blocks
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/destination-kit/index.ts
Labels: not-partner-eng-review (cloud), actions:core, team:segment
