Repository segmentio/action-destinations, pull requests merged in 2024-05, with the labels that each got.

#2018 Patch for UI issue with Klaviyo Subscribe
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/index.ts
Labels: Ready for Release, mode:cloud, deploy:push, team:segment

#2008 Add Magellan AI (Action) Destination
  packages/destination-actions/src/destinations/magellan-ai/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/magellan-ai/__tests__/index.test.ts
  packages/destination-actions/src/destinations/magellan-ai/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/magellan-ai/addToCart/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/magellan-ai/addToCart/__tests__/index.test.ts
  packages/destination-actions/src/destinations/magellan-ai/addToCart/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/magellan-ai/addToCart/generated-types.ts
  packages/destination-actions/src/destinations/magellan-ai/addToCart/index.ts
  packages/destination-actions/src/destinations/magellan-ai/checkout/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/magellan-ai/checkout/__tests__/index.test.ts
  packages/destination-actions/src/destinations/magellan-ai/checkout/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/magellan-ai/checkout/generated-types.ts
  packages/destination-actions/src/destinations/magellan-ai/checkout/index.ts
  packages/destination-actions/src/destinations/magellan-ai/code/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/magellan-ai/code/__tests__/index.test.ts
  packages/destination-actions/src/destinations/magellan-ai/code/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/magellan-ai/code/generated-types.ts
  packages/destination-actions/src/destinations/magellan-ai/code/index.ts
  packages/destination-actions/src/destinations/magellan-ai/generated-types.ts
  packages/destination-actions/src/destinations/magellan-ai/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/magellan-ai/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/magellan-ai/identify/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/magellan-ai/identify/generated-types.ts
  packages/destination-actions/src/destinations/magellan-ai/identify/index.ts
  packages/destination-actions/src/destinations/magellan-ai/index.ts
  packages/destination-actions/src/destinations/magellan-ai/install/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/magellan-ai/install/__tests__/index.test.ts
  packages/destination-actions/src/destinations/magellan-ai/install/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/magellan-ai/install/generated-types.ts
  packages/destination-actions/src/destinations/magellan-ai/install/index.ts
  packages/destination-actions/src/destinations/magellan-ai/lead/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/magellan-ai/lead/__tests__/index.test.ts
  packages/destination-actions/src/destinations/magellan-ai/lead/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/magellan-ai/lead/generated-types.ts
  packages/destination-actions/src/destinations/magellan-ai/lead/index.ts
  packages/destination-actions/src/destinations/magellan-ai/product/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/magellan-ai/product/__tests__/index.test.ts
  packages/destination-actions/src/destinations/magellan-ai/product/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/magellan-ai/product/generated-types.ts
  packages/destination-actions/src/destinations/magellan-ai/product/index.ts
  packages/destination-actions/src/destinations/magellan-ai/purchase/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/magellan-ai/purchase/__tests__/index.test.ts
  packages/destination-actions/src/destinations/magellan-ai/purchase/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/magellan-ai/purchase/generated-types.ts
  packages/destination-actions/src/destinations/magellan-ai/purchase/index.ts
  packages/destination-actions/src/destinations/magellan-ai/schema.ts
  packages/destination-actions/src/destinations/magellan-ai/thirdPartyEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/magellan-ai/thirdPartyEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/magellan-ai/thirdPartyEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/magellan-ai/thirdPartyEvent/generated-types.ts
  packages/destination-actions/src/destinations/magellan-ai/thirdPartyEvent/index.ts
  packages/destination-actions/src/destinations/magellan-ai/utils.ts
  packages/destination-actions/src/destinations/magellan-ai/view/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/magellan-ai/view/__tests__/index.test.ts
  packages/destination-actions/src/destinations/magellan-ai/view/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/magellan-ai/view/generated-types.ts
  packages/destination-actions/src/destinations/magellan-ai/view/index.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#2013 channels-1084: LiquidJS dependency update.
  packages/actions-shared/package.json
  packages/destination-actions/package.json
  yarn.lock
Labels: Ready for Release, partner-eng-review (cloud), team:segment

#1770 Also not double-hashing the phone for TikTok Audiences
  packages/destination-actions/src/destinations/tiktok-audiences/__tests__/functions.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/functions.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#2022 Facebook Conversions API double hashing prevention
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/user-data.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-user-data.ts
Labels: mode:cloud, team:segment

#2026 [EN-1033] Handle root level mapping
  packages/core/src/mapping-kit/__tests__/flatten.test.ts
  packages/core/src/mapping-kit/__tests__/index.iso.test.ts
  packages/core/src/mapping-kit/flatten.ts
  packages/core/src/mapping-kit/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, actions:core

#2031 Bug/stratconn 3772 - Staging
  packages/destination-subscriptions/src/__tests__/generate-fql.test.ts
  packages/destination-subscriptions/src/__tests__/validate.test.ts
  packages/destination-subscriptions/src/generate-fql.ts
  packages/destination-subscriptions/src/parse-fql.ts
  packages/destination-subscriptions/src/types.ts
  packages/destination-subscriptions/src/validate.ts
Labels: actions:core, team:segment

#2039 Bucket destination: trackingKey -> publishableKey
  packages/browser-destinations/destinations/bucket/src/index.ts
Labels: Ready for Release, partner-eng-review (device), team:external, mode:device

#2035 Map full event context in Ripe Cloud Mode
  packages/destination-actions/src/destinations/ripe/group/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/ripe/group/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/ripe/group/generated-types.ts
  packages/destination-actions/src/destinations/ripe/group/index.ts
  packages/destination-actions/src/destinations/ripe/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/ripe/identify/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/ripe/identify/generated-types.ts
  packages/destination-actions/src/destinations/ripe/identify/index.ts
  packages/destination-actions/src/destinations/ripe/page/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/ripe/page/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/ripe/page/generated-types.ts
  packages/destination-actions/src/destinations/ripe/page/index.ts
  packages/destination-actions/src/destinations/ripe/track/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/ripe/track/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/ripe/track/generated-types.ts
  packages/destination-actions/src/destinations/ripe/track/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2029 [UserMotion] Improvements
  packages/destination-actions/src/destinations/usermotion/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/usermotion/group/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/usermotion/group/__tests__/index.test.ts
  packages/destination-actions/src/destinations/usermotion/group/generated-types.ts
  packages/destination-actions/src/destinations/usermotion/group/index.ts
  packages/destination-actions/src/destinations/usermotion/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/usermotion/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/usermotion/identify/index.ts
  packages/destination-actions/src/destinations/usermotion/index.ts
  packages/destination-actions/src/destinations/usermotion/track/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/usermotion/track/__tests__/index.test.ts
  packages/destination-actions/src/destinations/usermotion/track/generated-types.ts
  packages/destination-actions/src/destinations/usermotion/track/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2027 [STRATCONN-3559] Add more states in data processing states
  packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-properties.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2025 [Amplitude] add device_manufacturer from user agent
  packages/destination-actions/src/destinations/amplitude/__tests__/amplitude.test.ts
  packages/destination-actions/src/destinations/amplitude/__tests__/user-agent.test.ts
  packages/destination-actions/src/destinations/amplitude/user-agent.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2021 [MAIN] [STRATCONN] added consent for google campaign manager
  packages/browser-destinations/destinations/google-campaign-manager/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/google-campaign-manager/src/generated-types.ts
  packages/browser-destinations/destinations/google-campaign-manager/src/index.ts
  packages/browser-destinations/package.json
Labels: Ready for Release, not-partner-eng-review (cloud), deploy:push, team:segment, mode:device

#2016 feat: added Contentstack's destination-action.
  packages/destination-actions/src/destinations/contentstack/constants.ts
  packages/destination-actions/src/destinations/contentstack/customAttributesSync/generated-types.ts
  packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
  packages/destination-actions/src/destinations/contentstack/customAttributesSync/types.ts
  packages/destination-actions/src/destinations/contentstack/customAttributesSync/utils.ts
  packages/destination-actions/src/destinations/contentstack/generated-types.ts
  packages/destination-actions/src/destinations/contentstack/index.ts
  packages/destination-actions/src/destinations/contentstack/types.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#2010 hide event context field for mixpanel
  packages/destination-actions/src/destinations/mixpanel/mixpanel-properties.ts
Labels: partner-eng-review (cloud), mode:cloud, team:segment

#2028 Heap - update property flattening on browserArrayLimit in track call
  packages/browser-destinations/destinations/heap/src/trackEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/heap/src/trackEvent/index.ts
  packages/browser-destinations/destinations/heap/src/utils.ts
Labels: partner-eng-review (device), team:external, mode:device

#2042 trubrics initial integration
  packages/destination-actions/src/destinations/trubrics/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/trubrics/__tests__/index.test.ts
  packages/destination-actions/src/destinations/trubrics/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/trubrics/generated-types.ts
  packages/destination-actions/src/destinations/trubrics/index.ts
  packages/destination-actions/src/destinations/trubrics/track/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/trubrics/track/__tests__/index.test.ts
  packages/destination-actions/src/destinations/trubrics/track/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/trubrics/track/generated-types.ts
  packages/destination-actions/src/destinations/trubrics/track/index.ts
Labels: partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#2047 SD-102706 | Segment Authentication Update
  packages/destination-actions/src/destinations/insider/index.ts
  packages/destination-actions/src/destinations/insider/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
Labels: partner-eng-review (cloud), mode:cloud, team:external

#2023 [Salesforce] Alternative authentication flow
  packages/core/src/index.ts
  packages/destination-actions/src/destinations/salesforce/__tests__/sf-operations.test.ts
  packages/destination-actions/src/destinations/salesforce/account/index.ts
  packages/destination-actions/src/destinations/salesforce/cases/index.ts
  packages/destination-actions/src/destinations/salesforce/contact/index.ts
  packages/destination-actions/src/destinations/salesforce/customObject/index.ts
  packages/destination-actions/src/destinations/salesforce/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/index.ts
  packages/destination-actions/src/destinations/salesforce/lead/index.ts
  packages/destination-actions/src/destinations/salesforce/opportunity/index.ts
  packages/destination-actions/src/destinations/salesforce/sf-operations.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, actions:core

#2050 Add script for action-cli shared
  package.json
Labels: team:segment

#2056 [snyk] bump jscodeshift from 0.13.0 to 0.14.0
  packages/cli-internal/package.json
  packages/cli/package.json
  yarn.lock
Labels: team:segment-core

#2036 [STRATCONN-3468] | Introduce 'Amazon AMC' Audience Destination
  packages/destination-actions/src/destinations/amazon-ads/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/amazon-ads/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/amazon-ads/generated-types.ts
  packages/destination-actions/src/destinations/amazon-ads/index.ts
  packages/destination-actions/src/destinations/amazon-ads/syncAudiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/amazon-ads/syncAudiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-ads/syncAudiences/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/amazon-ads/syncAudiences/generated-types.ts
  packages/destination-actions/src/destinations/amazon-ads/syncAudiences/index.ts
  packages/destination-actions/src/destinations/amazon-ads/types.ts
  packages/destination-actions/src/destinations/amazon-amc/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/amazon-amc/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/generated-types.ts
  packages/destination-actions/src/destinations/amazon-amc/index.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/generated-types.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/index.ts
  packages/destination-actions/src/destinations/amazon-amc/types.ts
  packages/destination-actions/src/destinations/amazon-amc/utils.ts
  packages/destination-actions/src/destinations/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2057 Implement batch support for Attio Actions
  packages/destination-actions/src/destinations/attio/api/index.ts
  packages/destination-actions/src/destinations/attio/assertRecord/__tests__/index.test.ts
  packages/destination-actions/src/destinations/attio/assertRecord/generated-types.ts
  packages/destination-actions/src/destinations/attio/assertRecord/index.ts
  packages/destination-actions/src/destinations/attio/common-fields.ts
  packages/destination-actions/src/destinations/attio/groupWorkspace/__tests__/index.test.ts
  packages/destination-actions/src/destinations/attio/groupWorkspace/generated-types.ts
  packages/destination-actions/src/destinations/attio/groupWorkspace/index.ts
  packages/destination-actions/src/destinations/attio/identifyUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/attio/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/attio/identifyUser/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2033 Preventing double-hashing for TikTok Conversions.
  packages/destination-actions/src/destinations/tiktok-conversions/__tests__/formatter.test.ts
  packages/destination-actions/src/destinations/tiktok-conversions/formatter.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#2034 Preventing double-hashing for TikTok Offline Conversions.
  packages/destination-actions/src/destinations/tiktok-offline-conversions/__tests__/formatter.test.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/formatter.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#2046 Add override_list_id mapping in upsert Profile
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/types.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2040 add new excludeWhenNull directive and update tests
  packages/core/src/__tests__/remove-empty-values.test.ts
  packages/core/src/mapping-kit/README.md
  packages/core/src/mapping-kit/__tests__/index.iso.test.ts
  packages/core/src/mapping-kit/index.ts
  packages/core/src/mapping-kit/validate.ts
  packages/core/src/mapping-kit/value-keys.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, actions:core
