Repository segmentio/action-destinations, pull requests merged in 2024-11, with the labels that each got.

#2566 [Facebook Conversions API] Properly pass madid and anonid, remove those from extinfo array
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/addToCart.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/addToCart2.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/app-data.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-app-data.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#2577 [STRATCONN-3911] GEC - Fix for retryable errors
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/userList.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2578 [Iterable Lists] - STRATCONN-4358 - fix iterable-lists Audience Settings
  packages/destination-actions/src/destinations/iterable-lists/generated-types.ts
  packages/destination-actions/src/destinations/iterable-lists/index.ts
  packages/destination-actions/src/destinations/iterable-lists/syncAudience/iterable-client.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2571 [Klaviyo] Update Properties in Ordered Product Call
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2569 [Iterable] - STRATCONN-3861 - enabling batching by default for batch enabled Actions
  packages/destination-actions/src/destinations/iterable/trackEvent/index.ts
  packages/destination-actions/src/destinations/iterable/updateUser/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2568 Typo in the destination_id creation
  packages/destination-actions/src/destinations/singlestore/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2565 [Snap Audiences] Add error tracking for create audience
  packages/destination-actions/src/destinations/snap-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/snap-audiences/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#2564 [Recombee (Actions)] Fix bugs
  packages/destination-actions/src/destinations/recombee/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/recombee/addBookmark/index.ts
  packages/destination-actions/src/destinations/recombee/addCartAddition/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/recombee/addCartAddition/__tests__/index.test.ts
  packages/destination-actions/src/destinations/recombee/addCartAddition/generated-types.ts
  packages/destination-actions/src/destinations/recombee/addCartAddition/index.ts
  packages/destination-actions/src/destinations/recombee/commonFields.ts
  packages/destination-actions/src/destinations/recombee/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2516 [Facebook Conversions] Adding Test Event Code to all mappings.
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/addToCart.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/addToCart2.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/custom.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/custom2.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/initiateCheckout.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/initiateCheckout2.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/pageView.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/pageView2.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/purchase.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/purchase2.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/search.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/search2.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/viewContent.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/viewContent2.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/addToCart/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/addToCart/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/addToCart2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/addToCart2/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/custom/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/custom/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/custom2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/custom2/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-properties.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/initiateCheckout/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/initiateCheckout/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/initiateCheckout2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/initiateCheckout2/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/pageView/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/pageView/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/pageView2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/pageView2/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/purchase/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/purchase/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/purchase2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/purchase2/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/search/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/search/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/search2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/search2/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/viewContent/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/viewContent/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/viewContent2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/viewContent2/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2572 [Sendgrid Audiences] - New Sendgrid Audiences Destination
  packages/destination-actions/src/destinations/sendgrid-audiences/constants.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/generated-types.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/index.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/fields.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/utils.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/types.ts
Labels: partner-eng-review (cloud), deploy:registration, team:segment-core, mode:cloud, deploy:push

#2580 [Hubspot] - STRATCONN-4331 - trim white space from string properties
  packages/destination-actions/src/destinations/hubspot/upsertCompany/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertCompany/index.ts
  packages/destination-actions/src/destinations/hubspot/upsertContact/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertContact/index.ts
  packages/destination-actions/src/destinations/hubspot/upsertCustomObjectRecord/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2582 [Sendgrid] - bug fixes for sendEmail Action
  packages/destination-actions/src/destinations/sendgrid/sendEmail/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/sendgrid/sendEmail/__tests__/index.test.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/constants.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/dynamic-fields.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/fields.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/generated-types.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/index.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/types.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/utils.ts
Labels: Ready for Release, partner-eng-review (cloud)

#2574 [Sprig] - New Destination - Sprig
  packages/destination-actions/src/destinations/sprig/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/sprig/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/sprig/generated-types.ts
  packages/destination-actions/src/destinations/sprig/identifyUser/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/sprig/identifyUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/sprig/identifyUser/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/sprig/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/sprig/identifyUser/index.ts
  packages/destination-actions/src/destinations/sprig/identifyUser/utils.ts
  packages/destination-actions/src/destinations/sprig/index.ts
  packages/destination-actions/src/destinations/sprig/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/sprig/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/sprig/trackEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/sprig/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/sprig/trackEvent/index.ts
  packages/destination-actions/src/destinations/sprig/trackEvent/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, team:segment-core, mode:cloud, deploy:push

#2583 [Sendgrid Audience] - renaming sendgrid lists destination to avoid clash
  packages/destination-actions/src/destinations/sendgrid-audiences/index.ts
  packages/destination-actions/src/destinations/sprig/index.ts
Labels: team:segment-core, mode:cloud

#2584 renaming sprig due to clash
  packages/destination-actions/src/destinations/sprig/index.ts
Labels: team:segment-core, mode:cloud

#2585 registering new destinations in actions
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2589 [Taboola] - making email field visible
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#2576 LR enhancements for non-uniform payloads
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/__fixtures__/liveramp-good-example.csv
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/operations.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/operations.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2545 Adds scripts and configurations to support hotfix release workflows
  .github/workflows/publish.yml
  .github/workflows/version-packages.yml
  lerna.json
  scripts/generate-package-tags.sh
  scripts/generate-release-tags.sh
  scripts/github-action/create-github-release.js
Labels: not-partner-eng-review (cloud), team:segment-core

#2595 [Sendgrid-Audiences] - adding email format filtering
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/fields.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/utils.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/types.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#2591 [Sendgrid] - minor bug preventing dynamic field from working
  packages/destination-actions/src/destinations/sendgrid/sendEmail/dynamic-fields.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2594 [Drip] - new Destination - Drip
  packages/destination-actions/src/destinations/drip/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/drip/__tests__/index.test.ts
  packages/destination-actions/src/destinations/drip/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/drip/generated-types.ts
  packages/destination-actions/src/destinations/drip/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/drip/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/drip/identify/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/drip/identify/generated-types.ts
  packages/destination-actions/src/destinations/drip/identify/index.ts
  packages/destination-actions/src/destinations/drip/index.ts
  packages/destination-actions/src/destinations/drip/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/drip/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/drip/trackEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/drip/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/drip/trackEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, team:segment-core, mode:cloud, deploy:push

#1154 fixing Amplitude Platform field and added tests - HGI-247
  packages/destination-actions/src/destinations/amplitude/__tests__/amplitude.test.ts
  packages/destination-actions/src/destinations/amplitude/event-schema.ts
  packages/destination-actions/src/destinations/amplitude/identifyUser/index.ts
  packages/destination-actions/src/destinations/amplitude/logEvent/generated-types.ts
  packages/destination-actions/src/destinations/amplitude/logEvent/index.ts
  packages/destination-actions/src/destinations/amplitude/logEventV2/generated-types.ts
  packages/destination-actions/src/destinations/amplitude/logEventV2/index.ts
  packages/destination-actions/src/destinations/amplitude/logPurchase/generated-types.ts
  packages/destination-actions/src/destinations/amplitude/logPurchase/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2505 Feature parity between InputField and GlobalSetting
  packages/cli/src/commands/generate/types.ts
  packages/cli/src/commands/scaffold.ts
  packages/core/src/destination-kit/types.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, actions:core

#2597 [Drip] - Register new Destination drip
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2601 [Drip] - drip bug fix
  packages/destination-actions/src/destinations/drip/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/drip/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/drip/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/drip/identify/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2603 Hotfix - nov19deploy
  packages/destination-actions/package.json
  packages/destination-actions/src/destinations/drip/index.ts
Labels: team:segment-core, mode:cloud

#2613 [Multistatus] Fix error reporter
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/destination-kit/action.ts
  packages/destination-actions/src/destinations/braze/__tests__/multistatus.test.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud, actions:core

#2609 Stackadapt audience destination: update the field mapping #2605
  packages/destination-actions/src/destinations/stackadapt-audiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/functions.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardProfile/functions.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2606 Migrate rokt-audiences to new authentication method
  packages/destination-actions/src/destinations/rokt-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/rokt-audiences/constants.ts
  packages/destination-actions/src/destinations/rokt-audiences/generated-types.ts
  packages/destination-actions/src/destinations/rokt-audiences/index.ts
  packages/destination-actions/src/destinations/rokt-audiences/upsertCustomAudiences/custom-audience-operations.ts
  packages/destination-actions/src/destinations/rokt-audiences/upsertCustomAudiences/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2570 First push with CustomEvents Destination Action
  packages/destination-actions/src/destinations/attentive/customEvents/__tests__/index.test.ts
  packages/destination-actions/src/destinations/attentive/customEvents/generated-types.ts
  packages/destination-actions/src/destinations/attentive/customEvents/index.ts
  packages/destination-actions/src/destinations/attentive/customEvents/types.ts
  packages/destination-actions/src/destinations/attentive/generated-types.ts
  packages/destination-actions/src/destinations/attentive/index.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#2599 Stackadapt (ITE-146) Update Segment Engage Destination to handle onDelete events
  packages/destination-actions/src/destinations/stackadapt-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/index.ts
Labels: partner-eng-review (cloud), mode:cloud, team:external

#2604 [Sendgrid Audiences] - adding user attribute and custom field support
  packages/destination-actions/src/destinations/sendgrid-audiences/constants.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/dynamic-fields.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/fields.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/utils.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/types.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2608 [Hubspot] [STRATCONN-4366] - correcting custom object reference to use canonical identifier
  packages/destination-actions/src/destinations/hubspot/customEvent/functions/dynamic-field-functions.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud
