Repository segmentio/action-destinations, pull requests merged in 2024-06, with the labels that each got.

#2030 [STRATCONN-3772] Add new operator "number_equals" for number
  packages/destination-subscriptions/src/__tests__/generate-fql.test.ts
  packages/destination-subscriptions/src/__tests__/validate.test.ts
  packages/destination-subscriptions/src/generate-fql.ts
  packages/destination-subscriptions/src/parse-fql.ts
  packages/destination-subscriptions/src/types.ts
  packages/destination-subscriptions/src/validate.ts
Labels: Ready for Release, not-partner-eng-review (cloud), actions:core, team:segment

#2067 Fix to show request headers in Action's Tester UI
  packages/cli/src/lib/summarize-http.ts
Labels: Ready for Release, team:segment

#2044 STRATCONN-3173: Add dropdown to region setting
  packages/destination-actions/src/destinations/the-trade-desk-crm/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2069 [AMAZON-AMC] | Fixed "415 Unsupported Media Type" issue while doing testAuthentication.
  packages/destination-actions/src/destinations/amazon-amc/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/index.ts
Labels: Ready for Release, mode:cloud, team:segment

#2032 Update MC contacts upsert to handle multiple identifiers
  packages/destination-actions/src/destinations/sendgrid/__tests__/sendgrid-properties.test.ts
  packages/destination-actions/src/destinations/sendgrid/sendgrid-properties.ts
  packages/destination-actions/src/destinations/sendgrid/updateUserProfile/generated-types.ts
  packages/destination-actions/src/destinations/sendgrid/updateUserProfile/index.ts
Labels: enhancement, Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2062 Contentstack's destination enhancement.
  packages/destination-actions/src/destinations/contentstack/constants.ts
  packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
  packages/destination-actions/src/destinations/contentstack/customAttributesSync/utils.ts
  packages/destination-actions/src/destinations/contentstack/generated-types.ts
  packages/destination-actions/src/destinations/contentstack/index.ts
Labels: partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2065 [DC-789] adds subscription sync modes support in destination-kit
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/types.ts
Labels: not-partner-eng-review (cloud), actions:core, team:segment

#2073 Fcm payload update
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-mobile-push.test.ts
  packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/PushSender.ts
Labels: Ready for Release, mode:cloud, team:segment

#2058 Change name of browser destination
  packages/browser-destinations/destinations/stackadapt/src/index.ts
Labels: Ready for Release, partner-eng-review (device)

#2079 Rename Amazon Ads | Fixed the refresh access token issue and some minor improvments.
  packages/destination-actions/src/destinations/amazon-amc/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/generated-types.ts
  packages/destination-actions/src/destinations/amazon-amc/index.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/index.ts
Labels: mode:cloud, deploy:push, team:segment

#2076 Remove (Actions) from StackAdapt destination names
  packages/browser-destinations/destinations/stackadapt/src/index.ts
  packages/destination-actions/src/destinations/stackadapt/index.ts
Labels: Ready for Release, partner-eng-review (cloud), partner-eng-review (device), mode:cloud, team:external, mode:device

#2084 disabling iam until it is fixed
  packages/destination-actions/src/destinations/kafka/index.ts
Labels: partner-eng-review (cloud)

#2087 update labels, no-op change
  packages/destination-actions/src/destinations/koala/identify/index.ts
  packages/destination-actions/src/destinations/koala/track/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2089 TikTok Destinations - fixing value field to handle 0 value
  packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/index.ts
  packages/destination-actions/src/destinations/tiktok-conversions/utils.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/utils.ts
Labels: team:segment-core, mode:cloud, mode:device

#2083 [Klaviyo] Update profile identifiers for track and order completed events.
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/index.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/index.ts
  packages/destination-actions/src/destinations/klaviyo/types.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2072 Taboola actions implementation
  packages/destination-actions/src/destinations/taboola-actions/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taboola-actions/generated-types.ts
  packages/destination-actions/src/destinations/taboola-actions/index.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/client.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/index.ts
Labels: partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#2086 [MAIN] [STRATCONN] Added conditional fields for Blackbaud Raiser's Edge NXT
  packages/destination-actions/src/destinations/blackbaud-raisers-edge-nxt/createGift/index.ts
Labels: partner-eng-review (cloud), mode:cloud, team:segment

#2093 update InputField type definition to allow field category
  packages/core/src/destination-kit/types.ts
Labels: team:segment-core, actions:core

#2090 [Amazon AMC] - Revamp Refresh Token Flow for createAudience and getAudience
  packages/destination-actions/src/destinations/amazon-amc/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/index.ts
  packages/destination-actions/src/destinations/amazon-amc/utils.ts
Labels: Ready for Release, mode:cloud, team:segment

#2070 CONSENT-309: Ensure consent data is copied for Segment Connections + Profiles
  packages/destination-actions/src/destinations/segment-profiles/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/segment-properties.ts
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/generated-types.ts
  packages/destination-actions/src/destinations/segment-profiles/sendGroup/index.ts
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/generated-types.ts
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/index.ts
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/generated-types.ts
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
  packages/destination-actions/src/destinations/segment-profiles/sendSubscription/subscription-properties.ts
  packages/destination-actions/src/destinations/segment-profiles/sendTrack/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendTrack/generated-types.ts
  packages/destination-actions/src/destinations/segment-profiles/sendTrack/index.ts
  packages/destination-actions/src/destinations/segment/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/segment-properties.ts
  packages/destination-actions/src/destinations/segment/sendGroup/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendGroup/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendGroup/index.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendIdentify/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/index.ts
  packages/destination-actions/src/destinations/segment/sendPage/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendPage/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendPage/index.ts
  packages/destination-actions/src/destinations/segment/sendScreen/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendScreen/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendScreen/index.ts
  packages/destination-actions/src/destinations/segment/sendTrack/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendTrack/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendTrack/index.ts
  packages/destination-actions/src/lib/test-data.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2088 GA4 - Cloud - Enabling button to add additional item params to product arrays
  packages/destination-actions/src/destinations/google-analytics-4/addPaymentInfo/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/addToCart/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/addToWishlist/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/beginCheckout/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/ga4-properties.ts
  packages/destination-actions/src/destinations/google-analytics-4/purchase/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/refund/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/removeFromCart/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/selectItem/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/selectPromotion/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/viewCart/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/viewItem/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/viewItemList/generated-types.ts
  packages/destination-actions/src/destinations/google-analytics-4/viewPromotion/generated-types.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2080 [Main] [STRATCONN] Applied depends_on condition on enableConsentMode field GCM
  packages/browser-destinations/destinations/google-campaign-manager/src/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment, mode:device

#2075 [MAIN] [STRATCONN] Updated conditions for phone number format
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2097 [Segment Profiles] fix consent object in sendIdentify action
  packages/destination-actions/src/destinations/segment-profiles/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendIdentify/index.ts
Labels: team:segment-core, mode:cloud

#2106 Support for dynamic objects
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/types.ts
Labels: team:segment-core, actions:core

#2107 fixing auth for taboola
  packages/destination-actions/src/destinations/taboola-actions/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taboola-actions/index.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/client.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2052 [Release Scripts] Fix changelog formatting and bump checkout/setup-node github action versions
  .github/workflows/ci.yml
  .github/workflows/ext.yml
  .github/workflows/publish.yml
  scripts/github-action/create-github-release.js
Labels: not-partner-eng-review (cloud), team:segment-core

#2043 STRATCONN-3719: Add retlOnMappingSave
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2105 fix @segment/ajv-human-errors README.md error
  packages/ajv-human-errors/README.md
Labels: Ready for Release, partner-eng-review (cloud), team:external

#2102 HubSpot Actions | Fixed Hubspot Action destination reauthorisation issue
  packages/destination-actions/src/destinations/hubspot/sendCustomBehavioralEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/sendCustomBehavioralEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#2096 Add depends on condition in revenue field
  packages/destination-actions/src/destinations/amplitude/logPurchase/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2094 Add Event Properties to Loops Destination
  packages/destination-actions/src/destinations/loops/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/loops/sendEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/loops/sendEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/loops/sendEvent/generated-types.ts
  packages/destination-actions/src/destinations/loops/sendEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2077 Bryan/audience to list
  packages/destination-actions/src/destinations/courier/audienceToList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/courier/audienceToList/generated-types.ts
  packages/destination-actions/src/destinations/courier/audienceToList/index.ts
  packages/destination-actions/src/destinations/courier/index.ts
  packages/destination-actions/src/destinations/courier/postToCourier/generated-types.ts
  packages/destination-actions/src/destinations/courier/postToCourier/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2112 Updates readme for action hooks to reflect present state of the feature
  README.md
Labels: team:segment-core

#2115 Dy changes
  packages/destination-actions/src/destinations/dynamic-yield-audiences/generated-types.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2108 [STRATCONN-3874]: Allowing Pinterest Actions to add additional fields
  packages/destination-actions/src/destinations/pinterest-conversions/pinterset-capi-user-data.ts
  packages/destination-actions/src/destinations/pinterest-conversions/reportConversionEvent/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/pinterest-conversions/reportConversionEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/pinterest-conversions/reportConversionEvent/generated-types.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2119 [DC-792] injects matchingKey in the perform block
  packages/browser-destinations/package.json
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/types.ts
Labels: not-partner-eng-review (cloud), actions:core, team:segment
