Repository segmentio/action-destinations, pull requests merged in 2024-07, with the labels that each got.

#2118 fix: remove use of polyfill.io
  packages/browser-destinations/destinations/commandbar/src/init-script.ts
Labels: Ready for Release, partner-eng-review (cloud), team:external, mode:device

#2121 [STRATCONN-3905] [OrderComplete] Add features to bring parity with klaviyo classic
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/formatter.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/formatters.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/index.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/types.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/index.ts
Labels: Ready for Release, team:segment-core, mode:cloud, deploy:push

#2100 [STRATCONN-3832] Validate Audience Field inputs while creating Audience
  packages/core/src/destination-kit/index.ts
  packages/destination-actions/src/destinations/amazon-amc/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/index.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taboola-actions/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, actions:core, team:segment

#2085 [MAIN] [STRATCONN] Added conditional fields on Intercom
  packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2122 Improve flexibility of dynamic objects
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/types.ts
Labels: Ready for Release, team:segment-core, actions:core

#2125 Register First Party DV360
  packages/destination-actions/src/destinations/first-party-dv360/addToList/generated-types.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToList/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/generated-types.ts
  packages/destination-actions/src/destinations/first-party-dv360/index.ts
  packages/destination-actions/src/destinations/index.ts
Labels: Ready for Release, deploy:registration, team:segment-core, mode:cloud, deploy:push

#2127 Publish
  .github/workflows/publish.yml
  packages/actions-shared/package.json
  packages/browser-destination-runtime/package.json
  packages/browser-destinations/destinations/1flow/package.json
  packages/browser-destinations/destinations/adobe-target/package.json
  packages/browser-destinations/destinations/algolia-plugins/package.json
  packages/browser-destinations/destinations/amplitude-plugins/package.json
  packages/browser-destinations/destinations/braze-cloud-plugins/package.json
  packages/browser-destinations/destinations/braze/package.json
  packages/browser-destinations/destinations/bucket/package.json
  packages/browser-destinations/destinations/cdpresolution/package.json
  packages/browser-destinations/destinations/commandbar/package.json
  packages/browser-destinations/destinations/devrev/package.json
  packages/browser-destinations/destinations/friendbuy/package.json
  packages/browser-destinations/destinations/fullstory/package.json
  packages/browser-destinations/destinations/google-analytics-4-web/package.json
  packages/browser-destinations/destinations/google-campaign-manager/package.json
  packages/browser-destinations/destinations/heap/package.json
  packages/browser-destinations/destinations/hubble-web/package.json
  packages/browser-destinations/destinations/hubspot-web/package.json
  packages/browser-destinations/destinations/intercom/package.json
  packages/browser-destinations/destinations/iterate/package.json
  packages/browser-destinations/destinations/jimo/package.json
  packages/browser-destinations/destinations/koala/package.json
  packages/browser-destinations/destinations/logrocket/package.json
  packages/browser-destinations/destinations/pendo-web-actions/package.json
  packages/browser-destinations/destinations/playerzero-web/package.json
  packages/browser-destinations/destinations/replaybird/package.json
  packages/browser-destinations/destinations/ripe/package.json
  packages/browser-destinations/destinations/rupt/package.json
  packages/browser-destinations/destinations/screeb/package.json
  packages/browser-destinations/destinations/segment-utilities-web/package.json
  packages/browser-destinations/destinations/snap-plugins/package.json
  packages/browser-destinations/destinations/sprig-web/package.json
  packages/browser-destinations/destinations/stackadapt/package.json
  packages/browser-destinations/destinations/survicate/package.json
  packages/browser-destinations/destinations/tiktok-pixel/package.json
  packages/browser-destinations/destinations/upollo/package.json
  packages/browser-destinations/destinations/userpilot/package.json
  packages/browser-destinations/destinations/vwo/package.json
  packages/browser-destinations/destinations/wisepops/package.json
  packages/core/package.json
  packages/destination-actions/package.json
  packages/destinations-manifest/package.json
Labels: team:segment-core, actions:core, mode:device

#2123 Dynamic Yield Destination - fix audience Id
  packages/destination-actions/src/destinations/dynamic-yield-audiences/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#2129 Revert "[STRATCONN-3832] Validate Audience Field inputs while creating Audience"
  packages/core/src/destination-kit/index.ts
  packages/destination-actions/src/destinations/amazon-amc/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/index.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taboola-actions/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/index.ts
Labels: team:segment-core, mode:cloud, actions:core

#2130 Taboola - upating device id field
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/index.ts
Labels: team:segment-core, mode:cloud, deploy:push

#2131 Manual Publish 2jul24
  packages/actions-shared/package.json
  packages/browser-destination-runtime/package.json
  packages/browser-destinations/destinations/1flow/package.json
  packages/browser-destinations/destinations/adobe-target/package.json
  packages/browser-destinations/destinations/algolia-plugins/package.json
  packages/browser-destinations/destinations/amplitude-plugins/package.json
  packages/browser-destinations/destinations/braze-cloud-plugins/package.json
  packages/browser-destinations/destinations/braze/package.json
  packages/browser-destinations/destinations/bucket/package.json
  packages/browser-destinations/destinations/cdpresolution/package.json
  packages/browser-destinations/destinations/commandbar/package.json
  packages/browser-destinations/destinations/devrev/package.json
  packages/browser-destinations/destinations/friendbuy/package.json
  packages/browser-destinations/destinations/fullstory/package.json
  packages/browser-destinations/destinations/google-analytics-4-web/package.json
  packages/browser-destinations/destinations/google-campaign-manager/package.json
  packages/browser-destinations/destinations/heap/package.json
  packages/browser-destinations/destinations/hubble-web/package.json
  packages/browser-destinations/destinations/hubspot-web/package.json
  packages/browser-destinations/destinations/intercom/package.json
  packages/browser-destinations/destinations/iterate/package.json
  packages/browser-destinations/destinations/jimo/package.json
  packages/browser-destinations/destinations/koala/package.json
  packages/browser-destinations/destinations/logrocket/package.json
  packages/browser-destinations/destinations/pendo-web-actions/package.json
  packages/browser-destinations/destinations/playerzero-web/package.json
  packages/browser-destinations/destinations/replaybird/package.json
  packages/browser-destinations/destinations/ripe/package.json
  packages/browser-destinations/destinations/rupt/package.json
  packages/browser-destinations/destinations/screeb/package.json
  packages/browser-destinations/destinations/segment-utilities-web/package.json
  packages/browser-destinations/destinations/snap-plugins/package.json
  packages/browser-destinations/destinations/sprig-web/package.json
  packages/browser-destinations/destinations/stackadapt/package.json
  packages/browser-destinations/destinations/survicate/package.json
  packages/browser-destinations/destinations/tiktok-pixel/package.json
  packages/browser-destinations/destinations/upollo/package.json
  packages/browser-destinations/destinations/userpilot/package.json
  packages/browser-destinations/destinations/vwo/package.json
  packages/browser-destinations/destinations/wisepops/package.json
  packages/cli-internal/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/destination-actions/README.md
  packages/destination-actions/package.json
  packages/destinations-manifest/package.json
Labels: team:segment-core, actions:core, mode:device

#2133 Add array editor option for defaultObjectUI
  packages/core/src/destination-kit/types.ts
Labels: team:segment-core, actions:core

#2134 Revert "Add features to bring parity with klaviyo classic"
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/formatter.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/formatters.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/index.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/types.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/index.ts
Labels: team:segment-core, mode:cloud, deploy:push

#2135 Manual Publish
  packages/actions-shared/package.json
  packages/browser-destination-runtime/package.json
  packages/browser-destinations/destinations/1flow/package.json
  packages/browser-destinations/destinations/adobe-target/package.json
  packages/browser-destinations/destinations/algolia-plugins/package.json
  packages/browser-destinations/destinations/amplitude-plugins/package.json
  packages/browser-destinations/destinations/braze-cloud-plugins/package.json
  packages/browser-destinations/destinations/braze/package.json
  packages/browser-destinations/destinations/bucket/package.json
  packages/browser-destinations/destinations/cdpresolution/package.json
  packages/browser-destinations/destinations/commandbar/package.json
  packages/browser-destinations/destinations/devrev/package.json
  packages/browser-destinations/destinations/friendbuy/package.json
  packages/browser-destinations/destinations/fullstory/package.json
  packages/browser-destinations/destinations/google-analytics-4-web/package.json
  packages/browser-destinations/destinations/google-campaign-manager/package.json
  packages/browser-destinations/destinations/heap/package.json
  packages/browser-destinations/destinations/hubble-web/package.json
  packages/browser-destinations/destinations/hubspot-web/package.json
  packages/browser-destinations/destinations/intercom/package.json
  packages/browser-destinations/destinations/iterate/package.json
  packages/browser-destinations/destinations/jimo/package.json
  packages/browser-destinations/destinations/koala/package.json
  packages/browser-destinations/destinations/logrocket/package.json
  packages/browser-destinations/destinations/pendo-web-actions/package.json
  packages/browser-destinations/destinations/playerzero-web/package.json
  packages/browser-destinations/destinations/replaybird/package.json
  packages/browser-destinations/destinations/ripe/package.json
  packages/browser-destinations/destinations/rupt/package.json
  packages/browser-destinations/destinations/screeb/package.json
  packages/browser-destinations/destinations/segment-utilities-web/package.json
  packages/browser-destinations/destinations/snap-plugins/package.json
  packages/browser-destinations/destinations/sprig-web/package.json
  packages/browser-destinations/destinations/stackadapt/package.json
  packages/browser-destinations/destinations/survicate/package.json
  packages/browser-destinations/destinations/tiktok-pixel/package.json
  packages/browser-destinations/destinations/upollo/package.json
  packages/browser-destinations/destinations/userpilot/package.json
  packages/browser-destinations/destinations/vwo/package.json
  packages/browser-destinations/destinations/wisepops/package.json
  packages/browser-destinations/package.json
  packages/cli-internal/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/destination-actions/package.json
  packages/destinations-manifest/package.json
Labels: team:segment-core, actions:core, mode:device

#2143 Introduce new release flow - Part 1
  .github/workflows/publish.yml
  .github/workflows/version-packages.yml
  scripts/generate-release-tags.sh
  scripts/release.sh
Labels: team:segment-core

#2081 [MAIN] [STRATCONN] added depends_on conditions on salesforce actions
  packages/destination-actions/src/destinations/salesforce/account/index.ts
  packages/destination-actions/src/destinations/salesforce/cases/index.ts
  packages/destination-actions/src/destinations/salesforce/contact/index.ts
  packages/destination-actions/src/destinations/salesforce/lead/index.ts
  packages/destination-actions/src/destinations/salesforce/opportunity/index.ts
  packages/destination-actions/src/destinations/salesforce/sf-properties.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2132 Hide legacy postConversion action that is no longer supported
  packages/destination-actions/src/destinations/google-enhanced-conversions/postConversion/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2114 [MOLOCO] Add a new field `Platform Name` in settings
  packages/destination-actions/src/destinations/moloco-rmp/__tests__/convert.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/addToCart/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/addToWishlist/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/common/request-client.ts
  packages/destination-actions/src/destinations/moloco-rmp/common/settings.ts
  packages/destination-actions/src/destinations/moloco-rmp/generated-types.ts
  packages/destination-actions/src/destinations/moloco-rmp/home/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/index.ts
  packages/destination-actions/src/destinations/moloco-rmp/itemPageView/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/land/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/pageView/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/purchase/__tests__/index.test.ts
  packages/destination-actions/src/destinations/moloco-rmp/search/__tests__/index.test.ts
Labels: partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2146 fixing Moloco - breaking build
  packages/destination-actions/src/destinations/moloco-rmp/common/request-client.ts
Labels: team:segment-core, mode:cloud

#2111 Update Customer.io destination with new mapping
  packages/destination-actions/src/destinations/customerio/__tests__/createUpdatePerson.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/deleteObject.test.ts
  packages/destination-actions/src/destinations/customerio/__tests__/deleteRelationship.test.ts
  packages/destination-actions/src/destinations/customerio/createUpdateObject/index.ts
  packages/destination-actions/src/destinations/customerio/createUpdatePerson/index.ts
  packages/destination-actions/src/destinations/customerio/deleteDevice/index.ts
  packages/destination-actions/src/destinations/customerio/deleteObject/index.ts
  packages/destination-actions/src/destinations/customerio/deleteRelationship/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2150 Introduce new release flow - Part 2
  .github/workflows/version-packages.yml
Labels: team:segment-core

#2152 Revert "Publish"
  packages/actions-shared/package.json
  packages/browser-destination-runtime/package.json
  packages/browser-destinations/destinations/1flow/package.json
  packages/browser-destinations/destinations/adobe-target/package.json
  packages/browser-destinations/destinations/algolia-plugins/package.json
  packages/browser-destinations/destinations/amplitude-plugins/package.json
  packages/browser-destinations/destinations/braze-cloud-plugins/package.json
  packages/browser-destinations/destinations/braze/package.json
  packages/browser-destinations/destinations/bucket/package.json
  packages/browser-destinations/destinations/cdpresolution/package.json
  packages/browser-destinations/destinations/commandbar/package.json
  packages/browser-destinations/destinations/devrev/package.json
  packages/browser-destinations/destinations/friendbuy/package.json
  packages/browser-destinations/destinations/fullstory/package.json
  packages/browser-destinations/destinations/google-analytics-4-web/package.json
  packages/browser-destinations/destinations/google-campaign-manager/package.json
  packages/browser-destinations/destinations/heap/package.json
  packages/browser-destinations/destinations/hubble-web/package.json
  packages/browser-destinations/destinations/hubspot-web/package.json
  packages/browser-destinations/destinations/intercom/package.json
  packages/browser-destinations/destinations/iterate/package.json
  packages/browser-destinations/destinations/jimo/package.json
  packages/browser-destinations/destinations/koala/package.json
  packages/browser-destinations/destinations/logrocket/package.json
  packages/browser-destinations/destinations/pendo-web-actions/package.json
  packages/browser-destinations/destinations/playerzero-web/package.json
  packages/browser-destinations/destinations/replaybird/package.json
  packages/browser-destinations/destinations/ripe/package.json
  packages/browser-destinations/destinations/rupt/package.json
  packages/browser-destinations/destinations/screeb/package.json
  packages/browser-destinations/destinations/segment-utilities-web/package.json
  packages/browser-destinations/destinations/snap-plugins/package.json
  packages/browser-destinations/destinations/sprig-web/package.json
  packages/browser-destinations/destinations/stackadapt/package.json
  packages/browser-destinations/destinations/survicate/package.json
  packages/browser-destinations/destinations/tiktok-pixel/package.json
  packages/browser-destinations/destinations/upollo/package.json
  packages/browser-destinations/destinations/userpilot/package.json
  packages/browser-destinations/destinations/vwo/package.json
  packages/browser-destinations/destinations/wisepops/package.json
  packages/core/package.json
  packages/destination-actions/package.json
  packages/destinations-manifest/package.json
Labels: team:segment-core, actions:core, mode:device

#2159 adding default subscription to Taboola Action
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/index.ts
Labels: team:segment-core, mode:cloud

#2160 Fix generate:types lint-staged hook
  package.json
Labels: team:segment-core

#2168 Update dynamic field types to support dynamic array of objects
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/destination-kit/action.ts
  packages/destination-actions/src/destinations/webhook-audiences/index.ts
Labels: team:segment-core, mode:cloud, actions:core

#2165 fix(action-tester): update readme
  docs/actions_tester.md
Labels: Ready for Release, partner-eng-review (cloud), team:external

#2166 feat(Package/Script): add test:clear-cache
  package.json
Labels: Ready for Release, partner-eng-review (cloud), team:external

#2164 Jimo action destination
  packages/browser-destinations/destinations/jimo/src/generated-types.ts
  packages/browser-destinations/destinations/jimo/src/index.ts
  packages/browser-destinations/destinations/jimo/src/sendUserData/__tests__/index.test.ts
  packages/browser-destinations/destinations/jimo/src/sendUserData/index.ts
  packages/browser-destinations/destinations/jimo/src/types.ts
Labels: Ready for Release, partner-eng-review (device), deploy:push, team:external, mode:device

#2170 Taboola device id fix
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2148 Insider | SD-107645 | Products ingesting incorrectly
  packages/destination-actions/src/destinations/insider/insider-helpers.ts
  packages/destination-actions/src/destinations/insider/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/insider/trackEvent/__tests__/snapshot.test.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2179 Update Sendgrid c action destination field labels and descriptions
  packages/destination-actions/src/destinations/sendgrid/updateUserProfile/generated-types.ts
  packages/destination-actions/src/destinations/sendgrid/updateUserProfile/index.ts
Labels: mode:cloud, deploy:push, team:segment

#2180 move version field to top level
  packages/destination-actions/src/destinations/app-fit/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/app-fit/track/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/app-fit/track/__tests__/index.test.ts
  packages/destination-actions/src/destinations/app-fit/track/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2175 Angler AI - Fix payload structure
  packages/destination-actions/src/destinations/angler-ai/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveCheckoutEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveCheckoutEvent/index.ts
  packages/destination-actions/src/destinations/angler-ai/saveUser/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveUser/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2162 Dynamic Yield: fix for non standard identifiers
  packages/destination-actions/src/destinations/dynamic-yield-audiences/generated-types.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2181 Taboola actions - add alphabetic account id description
  packages/destination-actions/src/destinations/taboola-actions/generated-types.ts
  packages/destination-actions/src/destinations/taboola-actions/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2117 Add S3 Destination
  packages/destination-actions/package.json
  packages/destination-actions/src/destinations/aws-s3/__tests__/index.test.ts
  packages/destination-actions/src/destinations/aws-s3/generated-types.ts
  packages/destination-actions/src/destinations/aws-s3/index.ts
  packages/destination-actions/src/destinations/aws-s3/operations.ts
  packages/destination-actions/src/destinations/aws-s3/properties.ts
  packages/destination-actions/src/destinations/aws-s3/syncAudienceToCSV/__tests__/index.test.ts
  packages/destination-actions/src/destinations/aws-s3/syncAudienceToCSV/generated-types.ts
  packages/destination-actions/src/destinations/aws-s3/syncAudienceToCSV/index.ts
  packages/destination-actions/src/destinations/aws-s3/syncAudienceToCSV/s3.ts
  yarn.lock
Labels: partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:segment

#2191 registering aws-s3 destination
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2184 [version-packages] add support for versioning packages and merging to release branch
  .github/workflows/version-packages.yml
Labels: team:segment-core

#2193 [S3 Action] Updates get credentials to assume intermediary role
  packages/destination-actions/src/destinations/aws-s3/generated-types.ts
  packages/destination-actions/src/destinations/aws-s3/index.ts
  packages/destination-actions/src/destinations/aws-s3/syncAudienceToCSV/index.ts
  packages/destination-actions/src/destinations/aws-s3/syncAudienceToCSV/s3.ts
Labels: team:segment-core, mode:cloud, deploy:push

#2194 [S3 Actions] rename env variable
  packages/destination-actions/src/destinations/aws-s3/syncAudienceToCSV/s3.ts
Labels: team:segment-core, mode:cloud

#2195 fixing non null assertion
  packages/destination-actions/src/destinations/aws-s3/syncAudienceToCSV/s3.ts
Labels: team:segment-core, mode:cloud

#2187 Adding support for FieldDisplayModes & disabling certain input methods
  packages/core/src/destination-kit/types.ts
Labels: not-partner-eng-review (cloud), team:segment-core, actions:core

#2204 Update name to proper casing
  packages/destination-actions/src/destinations/taboola-actions/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#2198 [CHANNELS-1156] remove email unsub link when unsubcribe tag not present
  packages/destination-actions/src/destinations/engage-messaging-sendgrid/__tests__/send-email.test.ts
  packages/destination-actions/src/destinations/engage-messaging-sendgrid/sendEmail/SendEmailPerformer.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#2203 [Github Actions] Adds publish-canary workflow and minor update to version-packages
  .github/workflows/publish-canary.yml
  .github/workflows/version-packages.yml
Labels: not-partner-eng-review (cloud), team:segment-core

#2182 Angler AI - Fix typo
  packages/destination-actions/src/destinations/angler-ai/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveBaseEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveCartEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveCheckoutEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveCollectionEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveCustomEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveFormEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveProductEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveSearchEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/transformFields/transformCommonFields.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2167 Updates to DevRev Destination - Contacts (RevUsers) no longer require accounts and tags are properly applied
  packages/destination-actions/src/destinations/devrev/createRevUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/devrev/createRevUser/generated-types.ts
  packages/destination-actions/src/destinations/devrev/createRevUser/index.ts
  packages/destination-actions/src/destinations/devrev/mocks/index.ts
  packages/destination-actions/src/destinations/devrev/utils/constants.ts
  packages/destination-actions/src/destinations/devrev/utils/types.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2144 Adjust Action Destination: First implementation + unit tests.
  packages/destination-actions/src/destinations/adjust/functions.ts
  packages/destination-actions/src/destinations/adjust/generated-types.ts
  packages/destination-actions/src/destinations/adjust/index.ts
  packages/destination-actions/src/destinations/adjust/sendEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/adjust/sendEvent/generated-types.ts
  packages/destination-actions/src/destinations/adjust/sendEvent/index.ts
  packages/destination-actions/src/destinations/adjust/types.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:segment

#2206 Registering new adjust Destination
  packages/destination-actions/src/destinations/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2208 Release
  packages/destination-actions/package.json
  packages/destination-actions/src/destinations/aws-s3/__tests__/index.test.ts
  packages/destination-actions/src/destinations/aws-s3/operations.ts
  packages/destination-actions/src/destinations/index.ts
  yarn.lock
Labels: team:segment-core, mode:cloud

#2188 Revert [Stratconn 3257] Add batching to segment connections (#1859)
  packages/core/src/__tests__/batching.test.ts
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/index.ts
  packages/destination-actions/src/destinations/segment/segment-properties.ts
  packages/destination-actions/src/destinations/segment/sendGroup/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendGroup/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendGroup/index.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/index.ts
  packages/destination-actions/src/destinations/segment/sendPage/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendPage/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendPage/index.ts
  packages/destination-actions/src/destinations/segment/sendScreen/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendScreen/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendScreen/index.ts
  packages/destination-actions/src/destinations/segment/sendTrack/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendTrack/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendTrack/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, actions:core, team:segment

#2169 [STRATCONN-3948][Segment Connections] | Made Address as separate key and send under traits in SendIdentify
  packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
  packages/destination-actions/src/destinations/index.ts
  packages/destination-actions/src/destinations/segment/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/segment-properties.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendIdentify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment/sendIdentify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2213 bug fixes for aws-s3-csv destination
  packages/destination-actions/src/destinations/aws-s3/generated-types.ts
  packages/destination-actions/src/destinations/aws-s3/index.ts
  packages/destination-actions/src/destinations/aws-s3/operations.ts
  packages/destination-actions/src/destinations/aws-s3/syncAudienceToCSV/index.ts
  packages/destination-actions/src/destinations/aws-s3/syncAudienceToCSV/s3.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2220 additional props traits changes
  packages/destination-actions/src/destinations/aws-s3/operations.ts
  packages/destination-actions/src/destinations/aws-s3/syncAudienceToCSV/generated-types.ts
  packages/destination-actions/src/destinations/aws-s3/syncAudienceToCSV/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2189 Partner: blend ai: Add authorization header
  packages/destination-actions/README.md
  packages/destination-actions/src/destinations/blend-ai/consts.ts
  packages/destination-actions/src/destinations/blend-ai/index.ts
  packages/destination-actions/src/destinations/blend-ai/sendData/index.ts
  packages/destination-actions/src/destinations/blend-ai/trackEvents/generated-types.ts
  packages/destination-actions/src/destinations/blend-ai/trackEvents/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2225 fix broken test
  packages/destination-actions/src/destinations/blend-ai/__tests__/index.test.ts
  packages/destination-actions/src/destinations/blend-ai/index.ts
Labels: team:segment-core, mode:cloud

#2177 [STRATCONN-3963] Allow for dynamic profile field values based on audience key value
  packages/destination-actions/src/destinations/listrak/__tests__/updateEmailContactProfileFields.test.ts
  packages/destination-actions/src/destinations/listrak/updateEmailContactProfileFields/generated-types.ts
  packages/destination-actions/src/destinations/listrak/updateEmailContactProfileFields/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2221 Braze regions
  packages/browser-destinations/destinations/braze/src/index.ts
  packages/destination-actions/src/destinations/braze/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external, mode:device

#2192 adding batch support
  packages/destination-actions/src/destinations/optimizely-advanced-audience-targeting/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/optimizely-advanced-audience-targeting/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-advanced-audience-targeting/syncAudience/index.ts
  packages/destination-actions/src/destinations/optimizely-advanced-audience-targeting/syncAudience/optimizely-client.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2226 fixing build - unclosed literal
  packages/browser-destinations/destinations/braze/src/index.ts
Labels: team:segment-core, mode:device

#2227 fixing braze device mode test
  packages/browser-destinations/destinations/braze/src/__tests__/__snapshots__/integration.test.ts.snap
Labels: partner-eng-review (device), team:segment-core, mode:device

#2190 Upgrade FBCAPI version to v20
  packages/destination-actions/src/destinations/facebook-conversions-api/constants.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2228 new Hubspot Action
  packages/destination-actions/src/destinations/hubspot/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/hubspot/index.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/common-fields.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/constants.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/dynamic-fields.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/generated-types.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/hubspot-api.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2229 registering iterable lists
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2224 RIP: @segment/actions-cli-internal
  .eslintrc.js
  .github/CODEOWNERS
  .github/workflows/ci.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish.yml
  .nxignore
  package.json
  packages/cli-internal/bin/run
  packages/cli-internal/bin/run.cmd
  packages/cli-internal/package.json
  packages/cli-internal/src/commands/push-browser-destinations.ts
  packages/cli-internal/src/commands/register.ts
  packages/cli-internal/src/config.ts
  packages/cli-internal/src/constants.ts
  packages/cli-internal/src/index.ts
  packages/cli-internal/src/lib/control-plane-client.ts
  packages/cli-internal/src/lib/control-plane-service.ts
  packages/cli-internal/src/lib/warning.ts
  packages/cli-internal/tsconfig.build.json
  packages/cli-internal/tsconfig.json
  packages/cli/package.json
  packages/cli/src/hooks/init.ts
  packages/cli/tsconfig.json
  yarn.lock
Labels: not-partner-eng-review (cloud), team:segment-core
