Repository segmentio/action-destinations, pull requests merged in 2024-03, with the labels that each got.

#1904 [MAIN] [STRATCONN] 3313 add page view field in setConfigurationFields
  packages/browser-destinations/destinations/google-analytics-4-web/src/__tests__/setConfigurationFields.test.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
Labels: Ready for Release, not-partner-eng-review (device)

#1905 [STRATCONN-3623] - Adds github actions workflow to label PRs
  .github/workflows/label-prs.yml
  scripts/compute-labels.js
Labels: not-partner-eng-review (cloud), team:segment-core

#1859 [Stratconn 3257] Add batching to segment connections
  packages/core/src/__tests__/batching.test.ts
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/index.ts
  packages/destination-actions/src/destinations/segment/segment-properties.ts
  packages/destination-actions/src/destinations/segment/sendGroup/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendGroup/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendGroup/index.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/index.ts
  packages/destination-actions/src/destinations/segment/sendPage/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendPage/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendPage/index.ts
  packages/destination-actions/src/destinations/segment/sendScreen/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendScreen/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendScreen/index.ts
  packages/destination-actions/src/destinations/segment/sendTrack/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment/sendTrack/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendTrack/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1909 Added encoding to username & password
  packages/destination-actions/src/destinations/responsys/index.ts
Labels: partner-eng-review (cloud)

#1908 Kafka Destination - Adding basic SSL config options
  packages/destination-actions/src/destinations/kafka/generated-types.ts
  packages/destination-actions/src/destinations/kafka/index.ts
  packages/destination-actions/src/destinations/kafka/utils.ts
Labels: partner-eng-review (cloud)

#1883 Channels-1034 Set google Api version for Push
  packages/destination-actions/src/destinations/engage-messaging-twilio/sendMobilePush.types.ts
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-mobile-push.test.ts
  packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/PushSender.ts
  packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/actionDefinition.ts
Labels: Ready for Release, not-partner-eng-review (cloud)

#1906 Optimizely data platform changes
  packages/destination-actions/src/destinations/optimizely-data-platform/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/customEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/customEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/customEvent/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/customEvent/index.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/emailEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/emailEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/emailEvent/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/emailEvent/index.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/fields.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/index.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/nonEcommCustomEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/nonEcommCustomEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/nonEcommCustomEvent/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/nonEcommCustomEvent/index.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/upsertContact/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/upsertContact/__tests__/index.test.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/upsertContact/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/upsertContact/index.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/utils.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#1912 DV360 - Update Chamber Variable
  packages/destination-actions/src/destinations/display-video-360/shared.ts
Labels: team:segment-core, mode:cloud

#1922 [GA4 Web] Page View defaults
  packages/browser-destinations/destinations/google-analytics-4-web/src/__tests__/setConfigurationFields.test.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
Labels: not-partner-eng-review (device), team:segment-core, deploy:push, mode:device

#1920 Additional responsys validation
  packages/destination-actions/src/destinations/responsys/index.ts
  packages/destination-actions/src/destinations/responsys/sendAudience/generated-types.ts
  packages/destination-actions/src/destinations/responsys/sendAudience/index.ts
  packages/destination-actions/src/destinations/responsys/sendCustomTraits/generated-types.ts
  packages/destination-actions/src/destinations/responsys/sendCustomTraits/index.ts
  packages/destination-actions/src/destinations/responsys/utils.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#1911 SD-98474 | [Madeira Madeira] Custom Identifier Improvement
  packages/destination-actions/src/destinations/insider/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/cartViewedEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/cartViewedEvent/generated-types.ts
  packages/destination-actions/src/destinations/insider/cartViewedEvent/index.ts
  packages/destination-actions/src/destinations/insider/checkoutEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/checkoutEvent/generated-types.ts
  packages/destination-actions/src/destinations/insider/checkoutEvent/index.ts
  packages/destination-actions/src/destinations/insider/insider-helpers.ts
  packages/destination-actions/src/destinations/insider/insider-properties.ts
  packages/destination-actions/src/destinations/insider/orderCompletedEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/orderCompletedEvent/generated-types.ts
  packages/destination-actions/src/destinations/insider/orderCompletedEvent/index.ts
  packages/destination-actions/src/destinations/insider/productAddedEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/productAddedEvent/generated-types.ts
  packages/destination-actions/src/destinations/insider/productAddedEvent/index.ts
  packages/destination-actions/src/destinations/insider/productListViewedEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/productListViewedEvent/generated-types.ts
  packages/destination-actions/src/destinations/insider/productListViewedEvent/index.ts
  packages/destination-actions/src/destinations/insider/productRemovedEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/productRemovedEvent/generated-types.ts
  packages/destination-actions/src/destinations/insider/productRemovedEvent/index.ts
  packages/destination-actions/src/destinations/insider/productViewedEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/productViewedEvent/generated-types.ts
  packages/destination-actions/src/destinations/insider/productViewedEvent/index.ts
  packages/destination-actions/src/destinations/insider/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/insider/trackEvent/index.ts
  packages/destination-actions/src/destinations/insider/updateUserProfile/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/updateUserProfile/generated-types.ts
  packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
  packages/destination-actions/src/destinations/insider/userRegisteredEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/insider/userRegisteredEvent/generated-types.ts
  packages/destination-actions/src/destinations/insider/userRegisteredEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#1913 [Snap v3 CAPI] Additional SnapV3 connector tweaks
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/capiV3tests.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-v3.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#1914 Add error handling in get Audience
  packages/destination-actions/src/destinations/klaviyo/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#1923 [linkedin conversions] Adds lookback window fields to hook inputs + adds new conversion type options
  packages/destination-actions/src/destinations/linkedin-conversions/api/api.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/api/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/constants.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/types.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#1901 Enhance @replace directive
  packages/core/src/mapping-kit/__tests__/index.iso.test.ts
  packages/core/src/mapping-kit/index.ts
  packages/core/src/mapping-kit/value-keys.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, actions:core

#1930 [segment connections] Enable_batching: hides field and defaults to false
  packages/destination-actions/src/destinations/segment/segment-properties.ts
  packages/destination-actions/src/destinations/segment/sendGroup/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendIdentify/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendPage/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendScreen/generated-types.ts
  packages/destination-actions/src/destinations/segment/sendTrack/generated-types.ts
Labels: team:segment-core, mode:cloud, deploy:push

#1932 adding yotpo for auth testing
  packages/destination-actions/src/destinations/yotpo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/yotpo/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yotpo/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/yotpo/generated-types.ts
  packages/destination-actions/src/destinations/yotpo/index.ts
  packages/destination-actions/src/destinations/yotpo/sendData/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/yotpo/sendData/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yotpo/sendData/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/yotpo/sendData/generated-types.ts
  packages/destination-actions/src/destinations/yotpo/sendData/index.ts
Labels: deploy:registration, team:segment-core, mode:cloud, deploy:push

#1929 [Snap V3 CAPI] use pixel id for offline events
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/capiV3tests.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-v3.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#1926 [LinkedIn Conversions] Move Ad Account ID & Campaign ID to hook inputs
  packages/core/src/destination-kit/action.ts
  packages/destination-actions/src/destinations/linkedin-conversions/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/linkedin-conversions/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/api/api.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/api/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push, actions:core

#1924 Add mantle action destination
  packages/destination-actions/src/destinations/mantle/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/mantle/__tests__/index.test.ts
  packages/destination-actions/src/destinations/mantle/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/mantle/config.ts
  packages/destination-actions/src/destinations/mantle/generated-types.ts
  packages/destination-actions/src/destinations/mantle/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/mantle/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/mantle/identify/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/mantle/identify/generated-types.ts
  packages/destination-actions/src/destinations/mantle/identify/index.ts
  packages/destination-actions/src/destinations/mantle/index.ts
  packages/destination-actions/src/destinations/mantle/pushEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/mantle/pushEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/mantle/pushEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/mantle/pushEvent/generated-types.ts
  packages/destination-actions/src/destinations/mantle/pushEvent/index.ts
Labels: partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#1934 Channels-1075: fix partially formatted E164 numbers failing to send
  packages/destination-actions/src/destinations/engage/twilio/__tests__/send-whatsapp.test.ts
  packages/destination-actions/src/destinations/engage/twilio/sendWhatsApp/WhatsAppMessageSender.ts
Labels: partner-eng-review (cloud), mode:cloud, team:segment

#1935 Update default Ripe cloud mode endpoint
  packages/destination-actions/src/destinations/ripe/group/__tests__/index.test.ts
  packages/destination-actions/src/destinations/ripe/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/ripe/index.ts
  packages/destination-actions/src/destinations/ripe/page/__tests__/index.test.ts
  packages/destination-actions/src/destinations/ripe/track/__tests__/index.test.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#1938 adding ChartMogul Destination
  packages/destination-actions/src/destinations/chartmogul/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/chartmogul/__tests__/index.test.ts
  packages/destination-actions/src/destinations/chartmogul/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/chartmogul/common_fields.ts
  packages/destination-actions/src/destinations/chartmogul/generated-types.ts
  packages/destination-actions/src/destinations/chartmogul/index.ts
  packages/destination-actions/src/destinations/chartmogul/sendContact/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/chartmogul/sendContact/__tests__/index.test.ts
  packages/destination-actions/src/destinations/chartmogul/sendContact/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/chartmogul/sendContact/generated-types.ts
  packages/destination-actions/src/destinations/chartmogul/sendContact/index.ts
  packages/destination-actions/src/destinations/chartmogul/sendCustomer/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/chartmogul/sendCustomer/__tests__/index.test.ts
  packages/destination-actions/src/destinations/chartmogul/sendCustomer/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/chartmogul/sendCustomer/generated-types.ts
  packages/destination-actions/src/destinations/chartmogul/sendCustomer/index.ts
Labels: deploy:registration, team:segment-core, mode:cloud, deploy:push

#1907 240226 schematic
  packages/destination-actions/src/destinations/schematic/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/__tests__/index.test.ts
  packages/destination-actions/src/destinations/schematic/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/schematic/identifyUser/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/identifyUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/schematic/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/schematic/identifyUser/index.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/schematic/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#1919 Update request based on latest data contract
  packages/destination-actions/src/destinations/stackadapt/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt/forwardEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#1947 [STRATCONN-3673] Adds github release workflow
  .eslintrc.js
  .github/workflows/publish.yml
  scripts/compute-labels.js
  scripts/create-github-release.js
  tsconfig.json
Labels: team:segment-core

#1886 Heap - update property flattening in track call
  packages/browser-destinations/destinations/heap/src/trackEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/heap/src/trackEvent/index.ts
  packages/browser-destinations/destinations/heap/src/utils.ts
Labels: Ready for Release, partner-eng-review (device)

#1950 Add @flatten directive
  packages/core/src/index.ts
  packages/core/src/mapping-kit/__tests__/flatten.test.ts
  packages/core/src/mapping-kit/__tests__/index.iso.test.ts
  packages/core/src/mapping-kit/flatten.ts
  packages/core/src/mapping-kit/index.ts
  packages/core/src/mapping-kit/validate.ts
  packages/core/src/mapping-kit/value-keys.ts
Labels: not-partner-eng-review (cloud), team:segment-core, actions:core

#1949 Add list unsubscribe headers
  packages/destination-actions/src/destinations/engage/sendgrid/__tests__/send-email.test.ts
  packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#1946 [Segment Profiles] Add SendTrack action
  packages/destination-actions/src/destinations/segment-profiles/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/index.ts
  packages/destination-actions/src/destinations/segment-profiles/segment-properties.ts
  packages/destination-actions/src/destinations/segment-profiles/sendTrack/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/segment-profiles/sendTrack/__tests__/index.test.ts
  packages/destination-actions/src/destinations/segment-profiles/sendTrack/generated-types.ts
  packages/destination-actions/src/destinations/segment-profiles/sendTrack/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#1941 Update Request Headers to Include DMP-ID
  packages/destination-actions/src/destinations/display-video-360/__tests__/shared.test.ts
  packages/destination-actions/src/destinations/display-video-360/constants.ts
  packages/destination-actions/src/destinations/display-video-360/errors.ts
  packages/destination-actions/src/destinations/display-video-360/shared.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#1928 [Snap Conversion API] Remove the V2 implementation
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/capiV2tests.ts
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/capiV3tests.ts
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-v2.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-v3.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/utils.ts
Labels: partner-eng-review (cloud), mode:cloud, team:external
