Repository segmentio/action-destinations, pull requests merged in 2024-09, with the labels that each got.

#2359 [STRATCONN-4130]- skip response cloning for google sheet api requests
  packages/destination-actions/src/destinations/google-sheets/__tests__/__snapshots__/googleapis.snapshot.test.ts.snap
  packages/destination-actions/src/destinations/google-sheets/googleapis/index.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2216 Mailing list support for Loops
  packages/destination-actions/src/destinations/loops/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/loops/createOrUpdateContact/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/loops/createOrUpdateContact/__tests__/index.test.ts
  packages/destination-actions/src/destinations/loops/createOrUpdateContact/generated-types.ts
  packages/destination-actions/src/destinations/loops/createOrUpdateContact/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2355 [LinkedIn CAPI] Uses client ID and client secret from chamber for refreshing tokens
  packages/destination-actions/src/destinations/linkedin-conversions/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2356 [Facebook Conversions] Adds `anon_id` parameter to `user_data`
  packages/destination-actions/src/destinations/facebook-conversions-api/addToCart/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/custom/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-user-data.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/initiateCheckout/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/pageView/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/purchase/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/search/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/viewContent/generated-types.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2322 Upgrade google api version to v17
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/functions.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2331 upgrade lerna and nx to the latest
  .github/workflows/ext.yml
  .gitignore
  lerna.json
  nx.json
  package.json
  yarn.lock
Labels: not-partner-eng-review (cloud), team:segment-core

#2362 [Hubspot] - bug fixes
  packages/destination-actions/src/destinations/hubspot/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/hubspot/customEvent/client.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/common-fields.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/types.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/utils.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/common-fields.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#2368 Publish
  packages/destination-actions/package.json
Labels: team:segment-core

#2369 revert upgrade lerna and nx to the latest
  .github/workflows/ext.yml
  .gitignore
  lerna.json
  nx.json
  package.json
  yarn.lock
Labels: team:segment-core

#2370 Enable bulk_batching for Iterable updateUser action
  packages/destination-actions/src/destinations/iterable/updateUser/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#2372 [snyk] bump jsdom
  packages/cli/package.json
  yarn.lock
Labels: team:segment-core

#2364 `excludeWhenNull` is applied to nested values in object
  packages/core/src/mapping-kit/__tests__/index.iso.test.ts
  packages/core/src/mapping-kit/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, actions:core

#2374 [Hubspot] - Bug fixes
  packages/destination-actions/src/destinations/hubspot/customEvent/client.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/types.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/utils.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/client.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/constants.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/index.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/types.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/utils.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#2363 Default batching to true on Dawn AI destination
  packages/destination-actions/src/destinations/dawn/identifyUser/index.ts
  packages/destination-actions/src/destinations/dawn/track/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2376 [Google Sheets] Update syncMode Action name to have V2
  packages/destination-actions/src/destinations/google-sheets/postSheet2/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2292 [STRATCONN-3932][STRATCONN-3933] First Party DV360 Create and Get Audience
  packages/destination-actions/src/destinations/first-party-dv360/functions.ts
  packages/destination-actions/src/destinations/first-party-dv360/generated-types.ts
  packages/destination-actions/src/destinations/first-party-dv360/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2346 [FACEBOOK] Add Sync Mode Support to "Page View" Action
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/pageView2.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/pageView2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/pageView2/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2345 [FACEBOOK] Add Sync Mode Support to "Add to Cart" Action
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/addToCart2.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/addToCart2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/addToCart2/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2361 [Reddit CAPI] - bugfix
  packages/destination-actions/src/destinations/reddit-conversions-api/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/reddit-conversions-api/__tests__/index.test.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/customEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/reddit-conversions-api/customEvent/generated-types.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/fields.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/index.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/standardEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/reddit-conversions-api/standardEvent/generated-types.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/types.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/utils.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2366 fix(Jimo): return a intermediary object to prevent mutation of object…
  packages/browser-destinations/destinations/jimo/src/index.ts
  packages/browser-destinations/destinations/jimo/src/init-script.ts
  packages/browser-destinations/destinations/jimo/src/sendTrackEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/jimo/src/sendTrackEvent/index.ts
  packages/browser-destinations/destinations/jimo/src/sendUserData/__tests__/index.test.ts
  packages/browser-destinations/destinations/jimo/src/sendUserData/index.ts
  packages/browser-destinations/destinations/jimo/src/types.ts
Labels: Ready for Release, partner-eng-review (device), team:external, mode:device

#2380 fixing breaking reddit tests
  packages/destination-actions/src/destinations/reddit-conversions-api/__tests__/index.test.ts
Labels: team:segment-core, mode:cloud

#2352 [FACEBOOK] Add Sync Mode Support to "Initiate Checkout" Action
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/initiateCheckout2.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/initiateCheckout2/generated-types.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/initiateCheckout2/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2387 [Hubspot] - bug fixes for new Actions
  packages/destination-actions/src/destinations/hubspot/customEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/client.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/index.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/utils.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/common-fields.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/generated-types.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/index.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/utils.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2384 [Google Ads Conversions] Update Action Names with V2
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment2/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2391 [STRATCONN-4149][Braze] - updates default trackevent mapping for email
  packages/destination-actions/src/destinations/braze/trackEvent/index.ts
Labels: team:segment-core, mode:cloud

#2248 [STRATCONN-3832] Validate Audience Field inputs while creating Audience
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/destination-kit/index.ts
  packages/destination-actions/src/destinations/amazon-amc/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/index.ts
  packages/destination-actions/src/destinations/aws-s3/index.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/iterable-lists/__tests__/index.test.ts
  packages/destination-actions/src/destinations/iterable-lists/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/index.ts
Labels: not-partner-eng-review (cloud), mode:cloud, actions:core, team:segment

#2378 [STRATCONN-4130]- google sheets increase timeout
  packages/destination-actions/src/destinations/google-sheets-dev/postSheet.types.ts
  packages/destination-actions/src/destinations/google-sheets/__tests__/postSheet.operations.test.ts
  packages/destination-actions/src/destinations/google-sheets/constants.ts
  packages/destination-actions/src/destinations/google-sheets/index.ts
  packages/destination-actions/src/destinations/google-sheets/postSheet/generated-types.ts
  packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
  packages/destination-actions/src/destinations/google-sheets/postSheet2/generated-types.ts
  packages/destination-actions/src/destinations/google-sheets/postSheet2/index.ts
  packages/destination-actions/src/destinations/google-sheets/postSheet2/operations2.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2254 Multi Status support for Actions Framework
  packages/core/src/__tests__/batching.test.ts
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/create-test-integration.ts
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/index.ts
  packages/core/src/destination-kit/types.ts
  packages/core/src/errors.ts
  packages/core/src/index.ts
Labels: not-partner-eng-review (cloud), team:segment-core, actions:core

#2257 [SALESFORCE] Add Sync Mode Support to "Lead" action
  packages/destination-actions/src/destinations/salesforce/__tests__/lead2.test.ts
  packages/destination-actions/src/destinations/salesforce/__tests__/sf-operations.test.ts
  packages/destination-actions/src/destinations/salesforce/__tests__/sf-utils.test.ts
  packages/destination-actions/src/destinations/salesforce/index.ts
  packages/destination-actions/src/destinations/salesforce/lead2/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/lead2/index.ts
  packages/destination-actions/src/destinations/salesforce/sf-operations.ts
  packages/destination-actions/src/destinations/salesforce/sf-properties.ts
  packages/destination-actions/src/destinations/salesforce/sf-types.ts
  packages/destination-actions/src/destinations/salesforce/sf-utils.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2399 Reddit CAPI integration fixes
  packages/destination-actions/src/destinations/reddit-conversions-api/customEvent/generated-types.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/fields.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/standardEvent/generated-types.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2377 add "autoPageView" setting & Pageview event preset
  packages/browser-destinations/destinations/tiktok-pixel/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/generated-types.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/index.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/init-script.ts
  packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/__tests__/index.test.ts
Labels: Ready for Release, partner-eng-review (device), deploy:push, team:external, mode:device

#2298 Google Campaign Manager 360
  .gitignore
  packages/destination-actions/src/destinations/campaign-manager-360/__tests__/index.test.ts
  packages/destination-actions/src/destinations/campaign-manager-360/__tests__/utils.test.ts
  packages/destination-actions/src/destinations/campaign-manager-360/common-fields.ts
  packages/destination-actions/src/destinations/campaign-manager-360/conversionAdjustmentUpload/__tests__/index.test.ts
  packages/destination-actions/src/destinations/campaign-manager-360/conversionAdjustmentUpload/generated-types.ts
  packages/destination-actions/src/destinations/campaign-manager-360/conversionAdjustmentUpload/index.ts
  packages/destination-actions/src/destinations/campaign-manager-360/conversionUpload/__tests__/index.test.ts
  packages/destination-actions/src/destinations/campaign-manager-360/conversionUpload/generated-types.ts
  packages/destination-actions/src/destinations/campaign-manager-360/conversionUpload/index.ts
  packages/destination-actions/src/destinations/campaign-manager-360/generated-types.ts
  packages/destination-actions/src/destinations/campaign-manager-360/index.ts
  packages/destination-actions/src/destinations/campaign-manager-360/types.ts
  packages/destination-actions/src/destinations/campaign-manager-360/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:segment

#2395 initial commit
  packages/destination-actions/src/destinations/s3/__tests__/index.test.ts
  packages/destination-actions/src/destinations/s3/client.ts
  packages/destination-actions/src/destinations/s3/fields.ts
  packages/destination-actions/src/destinations/s3/functions.ts
  packages/destination-actions/src/destinations/s3/generated-types.ts
  packages/destination-actions/src/destinations/s3/index.ts
  packages/destination-actions/src/destinations/s3/syncToS3/__tests__/index.test.ts
  packages/destination-actions/src/destinations/s3/syncToS3/generated-types.ts
  packages/destination-actions/src/destinations/s3/syncToS3/index.ts
  packages/destination-actions/src/destinations/s3/types.ts
Labels: deploy:registration, mode:cloud, deploy:push, team:segment

#2390 StackAdapt Audiences destination
  packages/destination-actions/src/destinations/stackadapt-audiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/stackadapt-audiences/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/functions.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/generated-types.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/index.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardProfile/functions.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardProfile/generated-types.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardProfile/index.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/functions.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/generated-types.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/index.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/types.ts
Labels: deploy:registration, mode:cloud, deploy:push, team:external

#2392 fix(Jimo): prevent losing ref of client
  packages/browser-destinations/destinations/jimo/src/init-script.ts
  packages/browser-destinations/destinations/jimo/src/sendTrackEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/jimo/src/sendTrackEvent/index.ts
  packages/browser-destinations/destinations/jimo/src/sendUserData/__tests__/index.test.ts
  packages/browser-destinations/destinations/jimo/src/sendUserData/index.ts
  packages/browser-destinations/destinations/jimo/src/types.ts
Labels: partner-eng-review (device), team:external, mode:device

#2408 registering stackadapt audiences
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2410 renaming google campaign manager destination
  packages/destination-actions/src/destinations/google-campaign-manager-360/__tests__/index.test.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/__tests__/utils.test.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/common-fields.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionAdjustmentUpload/__tests__/index.test.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionAdjustmentUpload/generated-types.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionAdjustmentUpload/index.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionUpload/__tests__/index.test.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionUpload/generated-types.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionUpload/index.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/generated-types.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/index.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/types.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/utils.ts
Labels: team:segment-core, mode:cloud, deploy:push

#2411 register google campaign manager 360
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2258 [SALESFORCE] Add Sync Mode Support for "Case" action
  packages/destination-actions/src/destinations/salesforce/__tests__/cases2.test.ts
  packages/destination-actions/src/destinations/salesforce/cases2/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/cases2/index.ts
  packages/destination-actions/src/destinations/salesforce/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2267 [SALESFORCE] Add SyncMode to "Contact" Action
  packages/destination-actions/src/destinations/salesforce/__tests__/contact2.test.ts
  packages/destination-actions/src/destinations/salesforce/contact2/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/contact2/index.ts
  packages/destination-actions/src/destinations/salesforce/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2266 [SALESFORCE] Add Sync Mode to "Opportunity" Action
  packages/destination-actions/src/destinations/salesforce/__tests__/opportunity2.test.ts
  packages/destination-actions/src/destinations/salesforce/index.ts
  packages/destination-actions/src/destinations/salesforce/opportunity2/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/opportunity2/index.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2264 [SALESFORCE] Add Sync Mode to "Account" action
  packages/destination-actions/src/destinations/salesforce/__tests__/account2.test.ts
  packages/destination-actions/src/destinations/salesforce/account2/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/account2/index.ts
  packages/destination-actions/src/destinations/salesforce/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2259 [SALESFORCE] Add Sync Mode Support to "CustomObject" Action
  packages/destination-actions/src/destinations/salesforce/__tests__/customObject2.test.ts
  packages/destination-actions/src/destinations/salesforce/customObject2/generated-types.ts
  packages/destination-actions/src/destinations/salesforce/customObject2/index.ts
  packages/destination-actions/src/destinations/salesforce/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2400 JLK Accoil Staging Endpoint Implementation
  packages/destination-actions/src/destinations/accoil-analytics/index.ts
  packages/destination-actions/src/destinations/accoil-analytics/postToAccoil/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2416 [S3] - renaming new s3 destination
  packages/destination-actions/src/destinations/s3/__tests__/index.test.ts
  packages/destination-actions/src/destinations/s3/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#2417 [S3] - registering s3 destination
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2425 [S3] - fixing s3 destination
  packages/destination-actions/src/destinations/s3/fields.ts
  packages/destination-actions/src/destinations/s3/functions.ts
  packages/destination-actions/src/destinations/s3/syncToS3/index.ts
  packages/destination-actions/src/destinations/s3/types.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#2427 [Fix Build] - committing types file
  packages/destination-actions/src/destinations/s3/syncToS3/generated-types.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2358 [STRATCONN-4162]:Add min/max validations for number type
  packages/core/src/__tests__/schema-validation.test.ts
  packages/core/src/destination-kit/fields-to-jsonschema.ts
  packages/core/src/destination-kit/types.ts
Labels: Ready for Release, not-partner-eng-review (cloud), actions:core, team:segment

#2437 Increase timeout for tests
  packages/cli/src/__tests__/init.test.ts
Labels: team:segment-core

#2397 Reddit Audience API Integration
  packages/destination-actions/src/destinations/reddit-audiences/const.ts
  packages/destination-actions/src/destinations/reddit-audiences/generated-types.ts
  packages/destination-actions/src/destinations/reddit-audiences/index.ts
  packages/destination-actions/src/destinations/reddit-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/reddit-audiences/syncAudience/functions.ts
  packages/destination-actions/src/destinations/reddit-audiences/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/reddit-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/reddit-audiences/syncAudience/types.ts
  packages/destination-actions/src/destinations/reddit-audiences/types.ts
  packages/destination-actions/src/destinations/s3/__tests__/index.test.ts
  packages/destination-actions/src/destinations/s3/functions.ts
  packages/destination-actions/src/destinations/s3/syncToS3/__tests__/index.test.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#2433 Rename data_type to type
  packages/destination-actions/src/destinations/stackadapt-audiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/functions.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardProfile/functions.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2420 Add Postscript Integration
  packages/destination-actions/src/destinations/postscript/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/postscript/__tests__/index.test.ts
  packages/destination-actions/src/destinations/postscript/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/postscript/const.ts
  packages/destination-actions/src/destinations/postscript/generated-types.ts
  packages/destination-actions/src/destinations/postscript/index.ts
  packages/destination-actions/src/destinations/postscript/syncAudiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/postscript/syncAudiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/postscript/syncAudiences/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/postscript/syncAudiences/generated-types.ts
  packages/destination-actions/src/destinations/postscript/syncAudiences/index.ts
  packages/destination-actions/src/destinations/postscript/types.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#2429 Add "Recombee (Actions)" destination
  packages/destination-actions/src/destinations/recombee/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/recombee/__tests__/index.test.ts
  packages/destination-actions/src/destinations/recombee/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/recombee/addBookmark/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/recombee/addBookmark/__tests__/index.test.ts
  packages/destination-actions/src/destinations/recombee/addBookmark/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/recombee/addBookmark/generated-types.ts
  packages/destination-actions/src/destinations/recombee/addBookmark/index.ts
  packages/destination-actions/src/destinations/recombee/addCartAddition/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/recombee/addCartAddition/__tests__/index.test.ts
  packages/destination-actions/src/destinations/recombee/addCartAddition/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/recombee/addCartAddition/generated-types.ts
  packages/destination-actions/src/destinations/recombee/addCartAddition/index.ts
  packages/destination-actions/src/destinations/recombee/addDetailView/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/recombee/addDetailView/__tests__/index.test.ts
  packages/destination-actions/src/destinations/recombee/addDetailView/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/recombee/addDetailView/generated-types.ts
  packages/destination-actions/src/destinations/recombee/addDetailView/index.ts
  packages/destination-actions/src/destinations/recombee/addPurchase/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/recombee/addPurchase/__tests__/index.test.ts
  packages/destination-actions/src/destinations/recombee/addPurchase/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/recombee/addPurchase/generated-types.ts
  packages/destination-actions/src/destinations/recombee/addPurchase/index.ts
  packages/destination-actions/src/destinations/recombee/addRating/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/recombee/addRating/__tests__/index.test.ts
  packages/destination-actions/src/destinations/recombee/addRating/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/recombee/addRating/generated-types.ts
  packages/destination-actions/src/destinations/recombee/addRating/index.ts
  packages/destination-actions/src/destinations/recombee/commonFields.ts
  packages/destination-actions/src/destinations/recombee/deleteBookmark/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/recombee/deleteBookmark/__tests__/index.test.ts
  packages/destination-actions/src/destinations/recombee/deleteBookmark/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/recombee/deleteBookmark/generated-types.ts
  packages/destination-actions/src/destinations/recombee/deleteBookmark/index.ts
  packages/destination-actions/src/destinations/recombee/deleteCartAddition/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/recombee/deleteCartAddition/__tests__/index.test.ts
  packages/destination-actions/src/destinations/recombee/deleteCartAddition/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/recombee/deleteCartAddition/generated-types.ts
  packages/destination-actions/src/destinations/recombee/deleteCartAddition/index.ts
  packages/destination-actions/src/destinations/recombee/generated-types.ts
  packages/destination-actions/src/destinations/recombee/index.ts
  packages/destination-actions/src/destinations/recombee/mergeUsers/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/recombee/mergeUsers/__tests__/index.test.ts
  packages/destination-actions/src/destinations/recombee/mergeUsers/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/recombee/mergeUsers/generated-types.ts
  packages/destination-actions/src/destinations/recombee/mergeUsers/index.ts
  packages/destination-actions/src/destinations/recombee/recombeeApiClient.ts
  packages/destination-actions/src/destinations/recombee/setViewPortion/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/recombee/setViewPortion/__tests__/index.test.ts
  packages/destination-actions/src/destinations/recombee/setViewPortion/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/recombee/setViewPortion/generated-types.ts
  packages/destination-actions/src/destinations/recombee/setViewPortion/index.ts
  packages/destination-actions/src/destinations/recombee/setViewPortionFromWatchTime/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/recombee/setViewPortionFromWatchTime/__tests__/index.test.ts
  packages/destination-actions/src/destinations/recombee/setViewPortionFromWatchTime/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/recombee/setViewPortionFromWatchTime/generated-types.ts
  packages/destination-actions/src/destinations/recombee/setViewPortionFromWatchTime/index.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#2431 Update contentstack name
  packages/destination-actions/src/destinations/contentstack/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#2413 [Nextdoor] - moving pixel_id to settings
  packages/destination-actions/src/destinations/nextdoor-capi/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/nextdoor-capi/__tests__/index.test.ts
  packages/destination-actions/src/destinations/nextdoor-capi/generated-types.ts
  packages/destination-actions/src/destinations/nextdoor-capi/index.ts
  packages/destination-actions/src/destinations/nextdoor-capi/sendConversion/generated-types.ts
  packages/destination-actions/src/destinations/nextdoor-capi/sendConversion/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2393 [Hubspot] - unit tests and caching for new Actions
  README.md
  packages/cli/src/lib/server.ts
  packages/core/src/create-test-integration.ts
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/index.ts
  packages/core/src/destination-kit/types.ts
  packages/destination-actions/package.json
  packages/destination-actions/src/destinations/hubspot/customEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/client.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/dynamic-fields.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/event-completion.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/index.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/types.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/utils.ts
  packages/destination-actions/src/destinations/hubspot/customEvent/validation.ts
  yarn.lock
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, actions:core

#2385 [Braze Cloud] Adds sync mode to new createAlias V2 action
  packages/destination-actions/src/destinations/braze/createAlias2/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/braze/createAlias2/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/braze/createAlias2/generated-types.ts
  packages/destination-actions/src/destinations/braze/createAlias2/index.ts
  packages/destination-actions/src/destinations/braze/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2419 [MAIN] [STRATCONN] 4119 klaviyo fixed blank audience creation.
  packages/destination-actions/src/destinations/klaviyo/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/index.ts
Labels: Ready for Release, mode:cloud, deploy:push, team:segment

#2439 [MAIN] [STRATCONNN-3944] Adobe target skipResponseCloning added
  packages/destination-actions/src/destinations/adobe-target/adobeTarget_operations.ts
Labels: Ready for Release, mode:cloud, team:segment

#2440 [Braze Cloud] Add new Update User Profile V2 Action w/ syncMode support
  packages/destination-actions/src/destinations/braze/index.ts
  packages/destination-actions/src/destinations/braze/updateUserProfile2/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/braze/updateUserProfile2/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/braze/updateUserProfile2/generated-types.ts
  packages/destination-actions/src/destinations/braze/updateUserProfile2/index.ts
  packages/destination-actions/src/destinations/braze/utils.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2441 change batch size to 5000
  packages/destination-actions/src/destinations/s3/fields.ts
Labels: partner-eng-review (cloud), mode:cloud, team:segment

#2404 [Braze Cloud] Adds sync mode to new Track Purchase V2 action
  packages/destination-actions/src/destinations/braze/index.ts
  packages/destination-actions/src/destinations/braze/trackPurchase2/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/braze/trackPurchase2/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/braze/trackPurchase2/generated-types.ts
  packages/destination-actions/src/destinations/braze/trackPurchase2/index.ts
  packages/destination-actions/src/destinations/braze/utils.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2421 Accoil Analytics: Refactor postToAccoil into sub actions
  packages/destination-actions/src/destinations/accoil-analytics/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/__tests__/index.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/common-fields.ts
  packages/destination-actions/src/destinations/accoil-analytics/generated-types.ts
  packages/destination-actions/src/destinations/accoil-analytics/group/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/group/__tests__/index.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/group/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/group/generated-types.ts
  packages/destination-actions/src/destinations/accoil-analytics/group/index.ts
  packages/destination-actions/src/destinations/accoil-analytics/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/identify/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/identify/generated-types.ts
  packages/destination-actions/src/destinations/accoil-analytics/identify/index.ts
  packages/destination-actions/src/destinations/accoil-analytics/index.ts
  packages/destination-actions/src/destinations/accoil-analytics/page/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/page/__tests__/index.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/page/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/page/generated-types.ts
  packages/destination-actions/src/destinations/accoil-analytics/page/index.ts
  packages/destination-actions/src/destinations/accoil-analytics/postToAccoil/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/postToAccoil/__tests__/index.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/postToAccoil/generated-types.ts
  packages/destination-actions/src/destinations/accoil-analytics/postToAccoil/index.ts
  packages/destination-actions/src/destinations/accoil-analytics/screen/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/screen/__tests__/index.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/screen/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/screen/generated-types.ts
  packages/destination-actions/src/destinations/accoil-analytics/screen/index.ts
  packages/destination-actions/src/destinations/accoil-analytics/track/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/track/__tests__/index.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/track/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/track/generated-types.ts
  packages/destination-actions/src/destinations/accoil-analytics/track/index.ts
  packages/destination-actions/src/destinations/accoil-analytics/utils.ts
Labels: partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2403 [Braze Cloud] Adds sync mode to new trackEvent V2 action
  packages/destination-actions/src/destinations/braze/index.ts
  packages/destination-actions/src/destinations/braze/trackEvent2/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/braze/trackEvent2/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/braze/trackEvent2/generated-types.ts
  packages/destination-actions/src/destinations/braze/trackEvent2/index.ts
  packages/destination-actions/src/destinations/braze/utils.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2386 [Braze Cloud] Adds sync mode to new identifyUser V2 action
  packages/destination-actions/src/destinations/braze/identifyUser2/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/braze/identifyUser2/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/braze/identifyUser2/generated-types.ts
  packages/destination-actions/src/destinations/braze/identifyUser2/index.ts
  packages/destination-actions/src/destinations/braze/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2442 registering 3 new destinations
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2434 [Reddit CAPI Integration] Adding a small fix for hashing and device_type logic
  packages/destination-actions/src/destinations/reddit-conversions-api/utils.ts
Labels: mode:cloud, team:external

#2445 fixing build by removing breaking recombee preset
  packages/destination-actions/src/destinations/recombee/index.ts
Labels: team:segment-core, mode:cloud

#2446 fixing breaking snapshots for accoil
  packages/destination-actions/src/destinations/accoil-analytics/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/group/__tests__/__snapshots__/snapshot.test.ts.snap
Labels: team:segment-core, mode:cloud

#2447 [Accoil] Fix build snapshots
  packages/destination-actions/src/destinations/accoil-analytics/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/group/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/group/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/accoil-analytics/identify/__tests__/snapshot.test.ts
Labels: team:segment-core, mode:cloud

#2449 fixing data issue in accoil test
  packages/destination-actions/src/destinations/accoil-analytics/identify/__tests__/snapshot.test.ts
Labels: team:segment-core, mode:cloud

#2450 removing accoil snapshot test
  packages/destination-actions/src/destinations/accoil-analytics/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/accoil-analytics/identify/__tests__/snapshot.test.ts
Labels: team:segment-core, mode:cloud

#2453 [Reddit Audience] - correcting reddit oauth to managed
  packages/destination-actions/src/destinations/reddit-audiences/index.ts
Labels: team:segment-core, mode:cloud

#2438 Adds a new check for required field changes
  .github/REQUIRED_FIELD_WARNING_TEMPLATE.md
  .github/workflows/required-field-check.yml
  packages/cli/src/commands/list-required-fields.ts
Labels: not-partner-eng-review (cloud), team:segment-core
