Repository segmentio/action-destinations, pull requests merged in 2024-12, with the labels that each got.

#2611 [STRATCONN-4213] - Update hotfix release scripts
  .github/workflows/publish.yml
  scripts/generate-release-tags.sh
  scripts/github-action/create-github-release.js
Labels: not-partner-eng-review (cloud), team:segment-core

#2621 Remove error tracking logs for Snap Audiences
  packages/destination-actions/src/destinations/snap-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/snap-audiences/index.ts
Labels: partner-eng-review (cloud), mode:cloud, team:segment

#2616 [Klaviyo] | Added stats for listId to see the whether entire batch has same listId
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2617 [Taboola Audiences] - Supporting computation key to be used when creating Audiences
  packages/destination-actions/src/destinations/taboola-actions/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taboola-actions/generated-types.ts
  packages/destination-actions/src/destinations/taboola-actions/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2612 [Twilio Messaging] - new Twilio Messaging Destination
  packages/destination-actions/src/destinations/reddit-conversions-api/__tests__/index.test.ts
  packages/destination-actions/src/destinations/schematic/__tests__/index.test.ts
  packages/destination-actions/src/destinations/schematic/trackEvent/index.ts
  packages/destination-actions/src/destinations/twilio-messaging/__tests__/index.test.ts
  packages/destination-actions/src/destinations/twilio-messaging/generated-types.ts
  packages/destination-actions/src/destinations/twilio-messaging/index.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/__tests__/index.test.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/constants.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/dynamic-fields.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/fields.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/generated-types.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/index.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/types.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/utils.ts
Labels: partner-eng-review (cloud), deploy:registration, team:segment-core, mode:cloud, deploy:push

#2593 extend actions-s3 batch size max to 100k
  packages/destination-actions/src/destinations/s3/functions.ts
Labels: partner-eng-review (cloud), mode:cloud, team:segment

#2622 Registering Twilio Messaging and Attentive Destinations.
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2624 [Twilio Messages and Sendgrid] - Bug fixes
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/fields.ts
  packages/destination-actions/src/destinations/sendgrid/index.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/__tests__/index.test.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/dynamic-fields.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/fields.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/utils.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/constants.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/dynamic-fields.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/fields.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/generated-types.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/index.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2628 Update drip identify action phone field
  packages/destination-actions/src/destinations/drip/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/drip/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/drip/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/drip/identify/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2630 [FUNK-1504] actions-webhook-extensible - Make changes to oauth2 refresh token handler
  packages/destination-actions/src/destinations/webhook-extensible/index.ts
  packages/destination-actions/src/destinations/webhook-extensible/types.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#2618 [Amazon-AMC] | Added regex validation for externalUserId in Amazon AMC
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/index.ts
  packages/destination-actions/src/destinations/amazon-amc/utils.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2575 Add new India region for mixpanel
  packages/destination-actions/src/destinations/mixpanel/alias/__tests__/index.test.ts
  packages/destination-actions/src/destinations/mixpanel/common/utils.ts
  packages/destination-actions/src/destinations/mixpanel/generated-types.ts
  packages/destination-actions/src/destinations/mixpanel/groupIdentifyUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/mixpanel/identifyUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/mixpanel/incrementProperties/__test__/index.test.ts
  packages/destination-actions/src/destinations/mixpanel/index.ts
  packages/destination-actions/src/destinations/mixpanel/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/mixpanel/trackPurchase/__tests__/index.test.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2625 StackAdapt audience destination: fix the external provider and field mapping key in GQL API
  packages/destination-actions/src/destinations/stackadapt-audiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/functions.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardProfile/functions.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/functions.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2498 [Klaviyo Actions] | Added MultiStatus Batch Support on TrackEvent
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/__tests__/multistatus.test.ts
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/properties.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/trackEvent/index.ts
  packages/destination-actions/src/destinations/klaviyo/types.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2631 Add Unique ID and Key Tracking in SFMC Events
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/contactDataExtension/index.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/dataExtension/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2633 fix build
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/index.ts
Labels: team:segment-core, mode:cloud

#2637 [Sendgrid] - better template variable support
  packages/destination-actions/src/destinations/sendgrid/sendEmail/__tests__/template-variables.test.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/dynamic-fields.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/fields.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#2635 [STRATCONN-4060] - Add slugs of destinations changed to release notes
  .github/workflows/publish.yml
  scripts/github-action/create-github-release.js
Labels: not-partner-eng-review (cloud), team:segment-core

#2627 remove batch size limit and use buffers
  packages/destination-actions/src/destinations/s3/__tests__/client.test.ts
  packages/destination-actions/src/destinations/s3/client.ts
  packages/destination-actions/src/destinations/s3/fields.ts
  packages/destination-actions/src/destinations/s3/functions.ts
  packages/destination-actions/src/destinations/s3/index.ts
  packages/destination-actions/src/destinations/s3/syncToS3/__tests__/index.test.ts
  packages/destination-actions/src/destinations/s3/syncToS3/generated-types.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2641 [sendgrid] - updates based on customer feedback
  packages/destination-actions/src/destinations/sendgrid/sendEmail/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/sendgrid/sendEmail/fields.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/generated-types.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/utils.ts
Labels: team:segment-core, mode:cloud, deploy:push

#2640 TikTok - STRATCONN-5346 - changing default object UI view for content field
  packages/destination-actions/src/destinations/tiktok-conversions/common_fields.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/common_fields.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#2642 [Sendgrid[ - fixing variable parsing to handle text between "" and ''
  packages/destination-actions/src/destinations/sendgrid/sendEmail/__tests__/template-variables.test.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/dynamic-fields.ts
Labels: Ready for Release, partner-eng-review (cloud)

#2526 [STRATCONN-4294] | Add MultiStatusResponse to AddProfileToList of Klaviyo.
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/__tests__/multistatus.test.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/properties.ts
  packages/destination-actions/src/destinations/klaviyo/types.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2607 [Klaviyo] |Add MultistatusResponse to RemoveProfile and RemoveProfilefromList
  packages/destination-actions/src/destinations/klaviyo/__tests__/multistatus.test.ts
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2643 [SendGrid Lists] - Sendgrid lists changes
  packages/destination-actions/src/destinations/sendgrid-audiences/constants.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/index.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/utils.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/types.ts
  packages/destination-actions/src/destinations/twilio-messaging/sendMessage/constants.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#2629 [LinkedIn Audiences] Necessary fixes for `updateAudience` mapping.
  packages/destination-actions/src/destinations/linkedin-audiences/api/index.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2636 Update reddit capi destination name
  packages/destination-actions/src/destinations/reddit-conversions-api/index.ts
Labels: partner-eng-review (cloud), mode:cloud, team:segment

#2648 [Sendgrid Lists] - update to sendgrid lists destination
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/dynamic-fields.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/fields.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/utils.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/types.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2652 [Sendgrid Lists] - minor bug fixes
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/dynamic-fields.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/fields.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud
