Repository segmentio/action-destinations, pull requests merged in 2025-09, with the labels that each got.

#3219 [LinkedIn Audiences] Hide enable batching
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud

#3212 STRATCONN-4121: Customer.io timestamp fix to convert ISO-8601 timestamp to Unix
  packages/destination-actions/src/destinations/customerio/__tests__/utils.test.ts
  packages/destination-actions/src/destinations/customerio/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#3217 STRATCONN-5890 - [Epsilon] - Adding custom property to Epsilon Action
  packages/destination-actions/src/destinations/epsilon/sendEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/epsilon/sendEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/epsilon/sendEvent/fields.ts
  packages/destination-actions/src/destinations/epsilon/sendEvent/generated-types.ts
  packages/destination-actions/src/destinations/epsilon/sendEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#3014 STRATCONN-5946 - [Taguchi] - new Destination
  packages/destination-actions/src/destinations/taguchi/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/taguchi/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taguchi/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/taguchi/generated-types.ts
  packages/destination-actions/src/destinations/taguchi/index.ts
  packages/destination-actions/src/destinations/taguchi/syncEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/taguchi/syncEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taguchi/syncEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/taguchi/syncEvent/fields.ts
  packages/destination-actions/src/destinations/taguchi/syncEvent/generated-types.ts
  packages/destination-actions/src/destinations/taguchi/syncEvent/index.ts
  packages/destination-actions/src/destinations/taguchi/syncEvent/types.ts
  packages/destination-actions/src/destinations/taguchi/syncEvent/utils.ts
  packages/destination-actions/src/destinations/taguchi/syncUserProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taguchi/syncUserProfile/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/taguchi/syncUserProfile/fields.ts
  packages/destination-actions/src/destinations/taguchi/syncUserProfile/generated-types.ts
  packages/destination-actions/src/destinations/taguchi/syncUserProfile/index.ts
  packages/destination-actions/src/destinations/taguchi/syncUserProfile/types.ts
  packages/destination-actions/src/destinations/taguchi/syncUserProfile/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, team:segment-core, mode:cloud, deploy:push

#3223 [Taguchi] - Registering Taguchi destination
  packages/destination-actions/src/destinations/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#3197 STRATCONN-6146 - [Dynamic Yield] - Support different id name in Segment
  packages/destination-actions/src/destinations/dynamic-yield-audiences/generated-types.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/types.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#3206 PT-2186 Add specificEvent presets to the snowflake destination for Journeys
  packages/warehouse-destinations/src/destinations/snowflake/index.ts
  packages/warehouse-destinations/src/destinations/snowflake/sendCustomEvent/journeys-default-fields.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment

#3196 @segment/analytics browser actions fullsession@1.0.0
  packages/browser-destinations/destinations/fullsession/README.md
  packages/browser-destinations/destinations/fullsession/package.json
  packages/browser-destinations/destinations/fullsession/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/fullsession/src/generated-types.ts
  packages/browser-destinations/destinations/fullsession/src/identifyUser/__tests__/index.test.ts
  packages/browser-destinations/destinations/fullsession/src/identifyUser/generated-types.ts
  packages/browser-destinations/destinations/fullsession/src/identifyUser/index.ts
  packages/browser-destinations/destinations/fullsession/src/index.ts
  packages/browser-destinations/destinations/fullsession/src/recordEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/fullsession/src/recordEvent/generated-types.ts
  packages/browser-destinations/destinations/fullsession/src/recordEvent/index.ts
  packages/browser-destinations/destinations/fullsession/src/types.ts
  packages/browser-destinations/destinations/fullsession/src/visitPage/__tests__/index.test.ts
  packages/browser-destinations/destinations/fullsession/src/visitPage/generated-types.ts
  packages/browser-destinations/destinations/fullsession/src/visitPage/index.ts
  packages/browser-destinations/destinations/fullsession/tsconfig.json
  yarn.lock
Labels: Ready for Release, partner-eng-review (device), deploy:registration, deploy:push, team:external, mode:device

#3225 SECOPS-16392 Fix: update @aws-sdk/client-sts dependency version in package.json
  package.json
  packages/destination-actions/package.json
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core

#3201 Update kafka error handling
  packages/destination-actions/src/destinations/kafka/__tests__/utils.test.ts
  packages/destination-actions/src/destinations/kafka/constants.ts
  packages/destination-actions/src/destinations/kafka/generated-types.ts
  packages/destination-actions/src/destinations/kafka/index.ts
  packages/destination-actions/src/destinations/kafka/send/__tests__/index.test.ts
  packages/destination-actions/src/destinations/kafka/send/generated-types.ts
  packages/destination-actions/src/destinations/kafka/send/index.ts
  packages/destination-actions/src/destinations/kafka/utils.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#3245 [Action Tester] - Clearing responses after action incovation for actions tester
  packages/cli/src/lib/server.ts
Labels: partner-eng-review (cloud), team:segment-core

#3203 [Klaviyo] [Multistatus] Add Multistatus for Klaviyo upsertProfile action
  packages/destination-actions/src/destinations/klaviyo/__tests__/multistatus.test.ts
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/types.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#3218 [MAIN] [STRATCONN-6111] : [Braze] Remove devicePropertyAllowList in braze SDK initialization for empty string array and only pass devicePropertyAllowList when there is a non empty string is filled from UI side
  packages/browser-destinations/destinations/braze/src/__tests__/initialization.test.ts
  packages/browser-destinations/destinations/braze/src/index.ts
Labels: Ready for Release, not-partner-eng-review (device), team:segment, mode:device

#3221 Added discountApplication object property to Cordial's upsertOrder action payload
  packages/destination-actions/src/destinations/cordial/cordial-client.ts
  packages/destination-actions/src/destinations/cordial/upsertOrder/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/cordial/upsertOrder/__tests__/index.test.ts
  packages/destination-actions/src/destinations/cordial/upsertOrder/generated-types.ts
  packages/destination-actions/src/destinations/cordial/upsertOrder/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#3251 Fixing breaking snapshot test in main
  packages/destination-actions/src/destinations/taguchi/syncUserProfile/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/taguchi/syncUserProfile/__tests__/snapshot.test.ts
Labels: team:segment-core, mode:cloud

#3255 [MS Bing Ads Audiences] Registering MS Bing Ads Audiences
  packages/destination-actions/src/destinations/index.ts
Labels: mode:cloud, team:segment

#3266 STRATCONN-6177 - [GA4 Web] - domain setting
  packages/browser-destinations/destinations/google-analytics-4-web/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/generated-types.ts
  packages/browser-destinations/destinations/google-analytics-4-web/src/index.ts
Labels: partner-eng-review (cloud), team:segment-core, deploy:push, mode:device

#3244 [Vibe] Add Vibe Audience destination
  packages/destination-actions/src/destinations/vibe-audience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/vibe-audience/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/vibe-audience/constants.ts
  packages/destination-actions/src/destinations/vibe-audience/functions.ts
  packages/destination-actions/src/destinations/vibe-audience/generated-types.ts
  packages/destination-actions/src/destinations/vibe-audience/index.ts
  packages/destination-actions/src/destinations/vibe-audience/sync/generated-types.ts
  packages/destination-actions/src/destinations/vibe-audience/sync/index.ts
  packages/destination-actions/src/destinations/vibe-audience/types.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#3238 STRATCONN-6163: Implement batching for mobile device IDs in `addToAudMobileDeviceId`
  packages/destination-actions/src/destinations/first-party-dv360/addToAudMobileDeviceId/_tests_/index.test.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToAudMobileDeviceId/generated-types.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToAudMobileDeviceId/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/functions.ts
  packages/destination-actions/src/destinations/first-party-dv360/properties.ts
  packages/destination-actions/src/destinations/first-party-dv360/removeFromAudMobileDeviceId/generated-types.ts
  packages/destination-actions/src/destinations/first-party-dv360/removeFromAudMobileDeviceId/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#3134 STRATCONN-5980 - [Commission Junction] - New Web Destination
  packages/browser-destinations/destinations/cj/package.json
  packages/browser-destinations/destinations/cj/src/generated-types.ts
  packages/browser-destinations/destinations/cj/src/index.ts
  packages/browser-destinations/destinations/cj/src/order/__tests__/index.test.ts
  packages/browser-destinations/destinations/cj/src/order/generated-types.ts
  packages/browser-destinations/destinations/cj/src/order/hashing-utils.ts
  packages/browser-destinations/destinations/cj/src/order/index.ts
  packages/browser-destinations/destinations/cj/src/order/order-fields.ts
  packages/browser-destinations/destinations/cj/src/order/utils.ts
  packages/browser-destinations/destinations/cj/src/sitePage/__tests__/index.test.ts
  packages/browser-destinations/destinations/cj/src/sitePage/generated-types.ts
  packages/browser-destinations/destinations/cj/src/sitePage/index.ts
  packages/browser-destinations/destinations/cj/src/sitePage/utils.ts
  packages/browser-destinations/destinations/cj/src/types.ts
  packages/browser-destinations/destinations/cj/src/utils.ts
  packages/browser-destinations/destinations/cj/tsconfig.json
  packages/browser-destinations/package.json
Labels: Ready for Release, partner-eng-review (device), deploy:registration, team:segment-core, deploy:push, mode:device

#3278 Disable kafka retries
  packages/destination-actions/src/destinations/kafka/send/__tests__/index.test.ts
  packages/destination-actions/src/destinations/kafka/utils.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#3280 [MAIN] [MS-BING-CAPI] Destination code refactored
  packages/destination-actions/src/destinations/ms-bing-capi/generated-types.ts
  packages/destination-actions/src/destinations/ms-bing-capi/index.ts
  packages/destination-actions/src/destinations/ms-bing-capi/pageLoad/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/ms-bing-capi/pageLoad/__tests__/index.test.ts
  packages/destination-actions/src/destinations/ms-bing-capi/pageLoad/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/ms-bing-capi/pageLoad/generated-types.ts
  packages/destination-actions/src/destinations/ms-bing-capi/pageLoad/index.ts
  packages/destination-actions/src/destinations/ms-bing-capi/sendEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/ms-bing-capi/sendEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/ms-bing-capi/sendEvent/__tests__/sendEvent.test.ts
  packages/destination-actions/src/destinations/ms-bing-capi/sendEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/ms-bing-capi/sendEvent/__tests__/utils.test.ts
  packages/destination-actions/src/destinations/ms-bing-capi/sendEvent/constants.ts
  packages/destination-actions/src/destinations/ms-bing-capi/sendEvent/fields.ts
  packages/destination-actions/src/destinations/ms-bing-capi/sendEvent/generated-types.ts
  packages/destination-actions/src/destinations/ms-bing-capi/sendEvent/index.ts
  packages/destination-actions/src/destinations/ms-bing-capi/sendEvent/types.ts
  packages/destination-actions/src/destinations/ms-bing-capi/sendEvent/utils.ts
  packages/destination-actions/src/destinations/vibe-audience/__tests__/__snapshots__/snapshot.test.ts.snap
Labels: mode:cloud, deploy:push, team:segment

#3277 [MS Bing Ads Audiences] Add Sync Audience Action
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/__tests__/utils.test.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/constants.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/generated-types.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/index.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/syncAudiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/syncAudiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/syncAudiences/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/syncAudiences/fields.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/syncAudiences/generated-types.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/syncAudiences/index.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/types.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/utils.ts
  packages/destination-actions/src/destinations/ms-bing-capi/sendEvent/__tests__/sendEvent.test.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#3282 registering 2 destinations, vibe and cj
  packages/browser-destinations/destinations/cj/package.json
  packages/destination-actions/src/destinations/index.ts
  packages/destinations-manifest/src/index.ts
Labels: team:segment-core, mode:cloud, mode:device

#3287 Add error name in logs
  packages/destination-actions/src/destinations/kafka/send/__tests__/index.test.ts
  packages/destination-actions/src/destinations/kafka/utils.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud

#3295 [MS Bing Ads Audiences] Fix multistatus bug
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/__tests__/utils.test.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/syncAudiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/syncAudiences/fields.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/syncAudiences/index.ts
  packages/destination-actions/src/destinations/ms-bing-ads-audiences/utils.ts
Labels: mode:cloud, team:segment

#3286 STRATCONN-6081 - [TikTok Conversions] - UI tweaks for new CRM fields for TikTok Conversions
  packages/destination-actions/src/destinations/tiktok-conversions/__tests__/index.test.ts
  packages/destination-actions/src/destinations/tiktok-conversions/reportWebEvent/fields/common_fields.ts
  packages/destination-actions/src/destinations/tiktok-conversions/reportWebEvent/fields/travel_fields.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#3305 shift producer.disconnect() to finally block to disconnect kafka producer gracefully on errors
  packages/destination-actions/src/destinations/kafka/utils.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud

#3283 [MAIN][STRATCONN-6153] : [DV360] added feature flag for first party dv360 destination for upgrade version from v3 to v4
  packages/destination-actions/src/destinations/first-party-dv360/_tests_/index.test.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToAudContactInfo/_tests_/index.test.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToAudContactInfo/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToAudMobileDeviceId/_tests_/index.test.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToAudMobileDeviceId/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/functions.ts
  packages/destination-actions/src/destinations/first-party-dv360/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/properties.ts
  packages/destination-actions/src/destinations/first-party-dv360/removeFromAudContactInfo/_tests_/index.test.ts
  packages/destination-actions/src/destinations/first-party-dv360/removeFromAudContactInfo/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/removeFromAudMobileDeviceId/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#3309 STRATCONN-6121 - [Eventbridge] - Minor change post testing
  packages/destination-actions/src/destinations/amazon-eventbridge/send/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-eventbridge/send/functions.ts
  packages/destination-actions/src/destinations/amazon-eventbridge/send/hooks.ts
  packages/destination-actions/src/destinations/amazon-eventbridge/send/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#3313 [S3] - restricting certain types of field entry methods for S3 Destination
  packages/destination-actions/src/destinations/s3/__tests__/client.test.ts
  packages/destination-actions/src/destinations/s3/syncToS3/__tests__/index.test.ts
  packages/destination-actions/src/destinations/s3/syncToS3/client.ts
  packages/destination-actions/src/destinations/s3/syncToS3/fields.ts
  packages/destination-actions/src/destinations/s3/syncToS3/functions.ts
  packages/destination-actions/src/destinations/s3/syncToS3/generated-types.ts
  packages/destination-actions/src/destinations/s3/syncToS3/index.ts
  packages/destination-actions/src/destinations/s3/syncToS3/types.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#3320 [NTTS-447] Add optional schemaOverride setting for Snowflake destination
  packages/warehouse-destinations/src/destinations/snowflake/generated-types.ts
  packages/warehouse-destinations/src/destinations/snowflake/index.ts
Labels: deploy:push, team:segment

#3056 [MAIN] [STRATCONN] Added Session Plugin for Amplitude
  packages/browser-destinations/destinations/amplitude-plugins/src/sessionId/__tests__/sessionId.test.ts
  packages/browser-destinations/destinations/amplitude-plugins/src/sessionId/generated-types.ts
  packages/browser-destinations/destinations/amplitude-plugins/src/sessionId/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), deploy:push, team:segment, mode:device

#3220 STRATCONN-6154 - [Hubspot] - Delete Associations
  packages/core/src/__tests__/dynamic-fields-types.test.ts
  packages/core/src/destination-kit/action.ts
  packages/destination-actions/src/destinations/hubspot/errors.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/dissocations.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/lists.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/upsert-all-properties-matching-with-cache.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/client.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/common-fields.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/constants.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/cache-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/dynamic-field-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/hubspot-association-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/hubspot-list-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/hubspot-record-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/validation-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/generated-types.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/index.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/types.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push, actions:core
