Repository segmentio/action-destinations, pull requests merged in 2025-03, with the labels that each got.

#2777 Use Node 22 as default version
  .github/workflows/publish-canary.yml
  .github/workflows/publish.yml
  .github/workflows/version-packages.yml
  .nvmrc
Labels: team:segment-core

#2780 [Smart Hashing] [Amazon AMC] Implement Smart Hashing Util for Amazon AMC
  packages/destination-actions/src/destinations/amazon-amc/function.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/index.ts
Labels: Ready for Release, mode:cloud, team:segment

#2778 Update DV360 Protobuf Dependencies
  packages/destination-actions/package.json
  packages/destination-actions/src/destinations/display-video-360/__tests__/shared.test.ts
  packages/destination-actions/src/destinations/display-video-360/proto/protofile.ts
  packages/destination-actions/src/destinations/display-video-360/shared.ts
  yarn.lock
Labels: Ready for Release, team:segment-core, mode:cloud

#2718 fix: sanitised vwo pageview event name
  packages/destination-actions/src/destinations/vwo/pageVisit/__tests__/index.test.ts
  packages/destination-actions/src/destinations/vwo/pageVisit/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2769 [Smart Hashing] [LinkedIn Audiences] Use Smart Hashing Util for Hashing Email
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: Ready for Release, mode:cloud, team:segment

#2781 [Smart Hashing] [Pinterest Conversions] Implement Smart Hashing Util for Pinterest Conversions
  packages/destination-actions/src/destinations/pinterest-conversions/pinterset-capi-user-data.ts
  packages/destination-actions/src/destinations/pinterest-conversions/reportConversionEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/pinterest-conversions/reportConversionEvent/index.ts
Labels: Ready for Release, mode:cloud, team:segment

#2783 [SMART-HASHING] [STRATCONN-5546] Implemented smart hashing utilities in Yahoo audience
  packages/destination-actions/src/destinations/yahoo-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/updateSegment/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/utils-rt.ts
Labels: Ready for Release, mode:cloud, team:segment

#2787 Set Default Version to V21 in Facebook Custom Audiences (Actions)
  packages/destination-actions/src/destinations/facebook-custom-audiences/constants.ts
Labels: Ready for Release, mode:cloud, team:segment

#2773 update api url for dawnai
  packages/destination-actions/src/destinations/dawn/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dawn/identifyUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dawn/identifyUser/index.ts
  packages/destination-actions/src/destinations/dawn/index.ts
  packages/destination-actions/src/destinations/dawn/track/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dawn/track/index.ts
  packages/destination-actions/src/destinations/dawn/utils.ts
Labels: Ready for Release, mode:cloud, team:external

#2761 Braze regions and v5.7 [STRATCONN-5592]
  packages/browser-destinations/destinations/braze/package.json
  packages/browser-destinations/destinations/braze/src/__tests__/__snapshots__/integration.test.ts.snap
  packages/browser-destinations/destinations/braze/src/__tests__/integration.test.ts
  packages/browser-destinations/destinations/braze/src/generated-types.ts
  packages/browser-destinations/destinations/braze/src/index.ts
  yarn.lock
Labels: Ready for Release, deploy:push, team:external, mode:device

#2711 [Salesforce Marketing Cloud] Data Extension mapping save hook
  package.json
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/dataExtension.test.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/contactDataExtension/generated-types.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/contactDataExtension/index.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/dataExtension/generated-types.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/dataExtension/index.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-operations.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-properties.ts
  yarn.lock
Labels: team:segment-core, mode:cloud, deploy:push

#2807 Eventbridge cosmetic changes
  packages/destination-actions/src/destinations/amazon-eventbridge/generated-types.ts
  packages/destination-actions/src/destinations/amazon-eventbridge/index.ts
  packages/destination-actions/src/destinations/amazon-eventbridge/send/generated-types.ts
  packages/destination-actions/src/destinations/amazon-eventbridge/send/index.ts
Labels: Ready for Release, mode:cloud, deploy:push, team:segment

#2812 Cleanup Node 18 checks from CI
  .github/workflows/ci.yml
  .github/workflows/ext.yml
Labels: team:segment-core

#2793 [Smart Hashing] [Google Enhanced Conversions] Implement Smart hashing for Google Enhanced Conversions
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/functions.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/userList.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment2/index.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: mode:cloud, team:segment

#2794 [Smart Hashing] [Google Campaign Manager 360] Implement Smart hashing for Google Campaign Manager 360
  packages/destination-actions/src/destinations/google-campaign-manager-360/__tests__/utils.test.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionAdjustmentUpload/index.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionUpload/index.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/utils.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: mode:cloud, team:segment

#2799 [Smart Hashing] [Snap Conversions API] Implement Smart hashing for Snap Conversions API
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-v3.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: mode:cloud, team:segment

#2802 [Smart hashing] [Reddit Conversions] Implement Smart hashing for Reddit Conversions
  packages/destination-actions/src/destinations/reddit-conversions-api/__tests__/index.test.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/customEvent/index.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/standardEvent/index.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/utils.ts
Labels: mode:cloud, team:segment

#2796 [SMART-HASHING] [STRATCONN-5550] Updated hashing utils for tiktok-audiences
  packages/destination-actions/src/destinations/tiktok-audiences/__tests__/functions.test.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addToAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addUser/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/functions.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeFromAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeUser/index.ts
Labels: Ready for Release, mode:cloud, team:segment

#2800 [Smart Hashing] [Snap Audience] Implement Smart hashing for Snap Audience
  packages/destination-actions/src/destinations/snap-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/snap-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/snap-audiences/syncAudience/utils.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: mode:cloud, team:segment

#2808 [SMART-HASHING] [STRATCONN-5551] Updated hashing utils for tiktok-conversions
  packages/destination-actions/src/destinations/tiktok-conversions/__tests__/formatter.test.ts
  packages/destination-actions/src/destinations/tiktok-conversions/formatter.ts
  packages/destination-actions/src/destinations/tiktok-conversions/reportWebEvent/index.ts
  packages/destination-actions/src/destinations/tiktok-conversions/utils.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: mode:cloud, team:segment

#2809 [SMART-HASHING] [STRATCONN-5556] Updated hashing utils for tiktok-offline-conversions
  packages/destination-actions/src/destinations/tiktok-offline-conversions/__tests__/formatter.test.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/formatter.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/reportOfflineEvent/index.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/trackNonPaymentOfflineConversion/index.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/trackPaymentOfflineConversion/index.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/utils.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: mode:cloud, team:segment

#2791 [STRATCONN-5488] Introduces batch_keys field (pilot)
  packages/cli/src/commands/validate.ts
  packages/core/src/destination-kit/action.ts
Labels: Ready for Release, team:segment-core, actions:core

#2795 [SMART-HASHING] [STRATCONN-5539] Updated hashing utils for facebook conversions API
  packages/destination-actions/src/destinations/facebook-conversions-api/__tests__/user-data.test.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/addToCart/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/addToCart2/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/custom/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/custom2/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-user-data.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/initiateCheckout/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/initiateCheckout2/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/pageView/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/pageView2/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/purchase/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/purchase2/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/search/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/search2/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/viewContent/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/viewContent2/index.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: Ready for Release, mode:cloud, team:segment

#2821 Revert smart hashing implementation for snap-conversions
  packages/destination-actions/src/destinations/snap-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/snap-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/snap-audiences/syncAudience/utils.ts
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: team:segment-core, mode:cloud

#2827 [Twilio-Messaging-Omnichannel] Register and set up Basic Authentication
  packages/destination-actions/src/destinations/twilio-messaging-omnichannel/generated-types.ts
  packages/destination-actions/src/destinations/twilio-messaging-omnichannel/index.ts
  packages/destination-actions/src/destinations/twilio-messaging-omnichannel/sendMessage/fields.ts
  packages/destination-actions/src/destinations/twilio-messaging-omnichannel/sendMessage/generated-types.ts
  packages/destination-actions/src/destinations/twilio-messaging-omnichannel/sendMessage/index.ts
Labels: Ready for Release, deploy:registration, team:segment-core, mode:cloud, deploy:push

#2825 [Salesforce] Advanced stats for CSV generation
  packages/destination-actions/src/destinations/salesforce/__tests__/sf-utils.test.ts
  packages/destination-actions/src/destinations/salesforce/sf-operations.ts
  packages/destination-actions/src/destinations/salesforce/sf-utils.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#2816 [STRATCONN-5603] - Format timestamp fields without miliiseconds
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/functions.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#2814 [STRATCONN-5601] add subscription object support for unsubscribeProfile action in Klaviyo
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/types.ts
  packages/destination-actions/src/destinations/klaviyo/unsubscribeProfile/__tests__/index.test.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#2813 [STRATCONN-5616] | Made Event Properties hidden in Braze Cohorts.
  packages/destination-actions/src/destinations/braze-cohorts/syncAudiences/index.ts
Labels: Ready for Release, mode:cloud, deploy:push, team:segment

#2771 [Criteo] Audience Destination: set enable_batching to true by default
  packages/destination-actions/src/destinations/criteo-audiences/generated-types.ts
  packages/destination-actions/src/destinations/criteo-audiences/index.ts
Labels: Ready for Release, eng-acknowledged, mode:cloud, deploy:push, team:external

#2770 [algolia-insights] update presets for conversion events
  packages/destination-actions/src/destinations/algolia-insights/conversionEvents/index.ts
  packages/destination-actions/src/destinations/algolia-insights/index.ts
  packages/destination-actions/src/destinations/algolia-insights/productAddedEvents/index.ts
Labels: Ready for Release, eng-acknowledged, mode:cloud, team:external

#2829 Register twilio messaging omnichannel destination
  packages/destination-actions/src/destinations/index.ts
  packages/destination-actions/src/destinations/twilio-messaging-omnichannel/index.ts
Labels: team:segment-core, mode:cloud

#2831 Support min/max string length validation
  packages/core/src/__tests__/schema-validation.test.ts
  packages/core/src/destination-kit/fields-to-jsonschema.ts
  packages/core/src/destination-kit/types.ts
Labels: Ready for Release, team:segment-core, actions:core

#2826 [Salesforce Marketing Cloud] V2 Data Extension mapping save hook
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/contactDataExtensionV2/generated-types.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/contactDataExtensionV2/index.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/dataExtensionV2/generated-types.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/dataExtensionV2/index.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/index.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-operations.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-properties.ts
Labels: team:segment-core, mode:cloud, deploy:push

#2828 Eventbridge enhancements
  packages/destination-actions/src/destinations/amazon-eventbridge/functions.ts
  packages/destination-actions/src/destinations/amazon-eventbridge/send/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-eventbridge/send/generated-types.ts
  packages/destination-actions/src/destinations/amazon-eventbridge/send/index.ts
Labels: Ready for Release, mode:cloud, deploy:push, team:segment
