Repository segmentio/action-destinations, pull requests merged in 2025-04, with the labels that each got.

#2844 Revert "Fix Faulty Test cases"
  packages/destination-actions/src/destinations/hyperengage/__tests__/validateInput.test.ts
Labels: team:segment-core, mode:cloud

#2786 [STRATCONN-5473] Add destinationInstanceID and subscriptionId to support audience fanout for Liveramp Audiences
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/liveramp.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/awsClient.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#2836 [SMART-HASHING] [STRATCONN-5636] Updated smart-hashing in delivrai-activate
  packages/destination-actions/src/destinations/delivrai-activate/updateSegment/__tests__/index.test.ts
  packages/destination-actions/src/destinations/delivrai-activate/updateSegment/index.ts
  packages/destination-actions/src/destinations/delivrai-activate/utils-rt.ts
Labels: Ready for Release, mode:cloud, team:segment

#2837 [Smart Hashing] [Snap Conversions API] Implement Smart hashing for Snap Conversions API
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-v3.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/utils.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: Ready for Release, mode:cloud, team:segment

#2843 [Smart Hashing] [Snap Audience] Implement Smart hashing for Snap Audience
  packages/destination-actions/src/destinations/snap-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/snap-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/snap-audiences/syncAudience/utils.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: Ready for Release, mode:cloud, team:segment

#2847 [Smart Hashing] Add hashedPII category to all fields that are hashed using process hashing
  packages/core/src/destination-kit/types.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/index.ts
  packages/destination-actions/src/destinations/delivrai-activate/updateSegment/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-user-data.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/properties.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/common-fields.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionUpload/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/index.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
  packages/destination-actions/src/destinations/pinterest-conversions/pinterset-capi-user-data.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/fields.ts
  packages/destination-actions/src/destinations/snap-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-input-fields-deprecated.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-input-fields-v3.ts
  packages/destination-actions/src/destinations/tiktok-audiences/properties.ts
  packages/destination-actions/src/destinations/tiktok-conversions/common_fields.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/common_fields.ts
  packages/destination-actions/src/destinations/yahoo-audiences/updateSegment/index.ts
Labels: mode:cloud, actions:core, team:segment

#2848 [Smart Hashing] Remove redundant hashing descriptions
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/generated-types.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/postConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/index.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/common_fields.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/reportOfflineEvent/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/trackNonPaymentOfflineConversion/generated-types.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/trackPaymentOfflineConversion/generated-types.ts
Labels: team:segment-core, mode:cloud, deploy:push

#2850 [LAB-1803] Correct Presets for Linked Audience Activations
  packages/destination-actions/src/destinations/klaviyo/index.ts
Labels: mode:cloud, team:segment

#2854 Handles non-http error in SFMC multistatus handler
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/multistatus.test.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/dataExtension/index.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-operations.ts
Labels: team:segment-core, mode:cloud

#2852 [STRATCONN-5683] Amazon AMC - Increased timeout to 15 seconds
  packages/destination-actions/src/destinations/amazon-amc/function.ts
  packages/destination-actions/src/destinations/amazon-amc/index.ts
  packages/destination-actions/src/destinations/amazon-amc/utils.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#2810 [Google Ads] Standardize Phone Number Formatting
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion2.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadConversionAdjustment.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadConversionAdjustment2.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment2/index.ts
Labels: Ready for Release, team:segment-core, mode:cloud, deploy:push

#2833 [STRATCONN-5676] - Adds support braze web sdk - 5.8.1
  packages/browser-destinations/destinations/braze/src/__tests__/__snapshots__/integration.test.ts.snap
  packages/browser-destinations/destinations/braze/src/index.ts
  yarn.lock
Labels: Ready for Release, team:segment-core, mode:device

#2849 [STRATCONN-5602] - Sendgrid EU endpoint
  packages/destination-actions/src/destinations/sendgrid/generated-types.ts
  packages/destination-actions/src/destinations/sendgrid/index.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/__tests__/dynamic-fields.test.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/__tests__/index.test.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/constants.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/dynamic-fields.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/index.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/utils.ts
  packages/destination-actions/src/destinations/sendgrid/sendgrid-properties.ts
  packages/destination-actions/src/destinations/sendgrid/updateUserProfile/index.ts
Labels: Ready for Release, team:segment-core, mode:cloud, deploy:push

#2862 Update Liveramp Docs
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/generated-types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/generated-types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSftp/index.ts
Labels: Ready for Release, team:segment-core, mode:cloud, deploy:push

#2863 [Google Ads] Update membership lifespan to the new max value
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#2867 [STRATCONN-5733] - Add new mapping-kit github workflow
  .github/workflows/label-prs.yml
  scripts/github-action/compute-labels.js
Labels: team:segment-core

#2872 [TikTok] Add error when no audience found
  packages/destination-actions/src/destinations/tiktok-audiences/index.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#2818 Angler AI - Add missing payload field
  packages/destination-actions/src/destinations/angler-ai/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveCustomEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/angler-ai/saveCustomEvent/transform-payload.ts
Labels: Ready for Release, mode:cloud, team:external

#2789 Add fs_user_id and web_user_id to Optimizely payload interfaces
  packages/destination-actions/src/destinations/optimizely-data-platform/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/customEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/customEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/customEvent/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/emailEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/emailEvent/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/fields.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/nonEcommCustomEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/nonEcommCustomEvent/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-data-platform/upsertContact/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-data-platform/upsertContact/generated-types.ts
Labels: Ready for Release, mode:cloud, deploy:push, team:external

#2886 MultiStatus Documentation
  README.md
  docs/multistatus.md
Labels: team:segment-core

#2887 MultiStatus Readme Fix
  README.md
Labels: team:segment-core

#2889 Fix MultiStatus Readme
  docs/multistatus.md
Labels: team:segment-core

#2890 Disable failing logrocket tests
  packages/browser-destinations/destinations/logrocket/src/identify/__tests__/index.test.ts
  packages/browser-destinations/destinations/logrocket/src/track/__tests__/index.test.ts
Labels: team:segment-core, mode:device

#2885 Worked on handling empty array being sent to Klaviyo resulting 400 Bad request.
  packages/destination-actions/src/destinations/klaviyo/removeProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/index.ts
Labels: Ready for Release, mode:cloud, team:segment

#2884 Add initial status to drip destination
  packages/destination-actions/src/destinations/drip/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/drip/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/drip/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/drip/identify/generated-types.ts
  packages/destination-actions/src/destinations/drip/identify/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2881 Allow only dropdown value in objectType and toObjectType in UpsertCustomObjectRecord.
  packages/destination-actions/src/destinations/hubspot/upsertCustomObjectRecord/index.ts
Labels: Ready for Release, mode:cloud, deploy:push, team:segment

#2853 [STRAT-5634] | Multistatus Support on Google Enhanced Conversions.
  packages/core/src/errors.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/userList.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/constants.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/index.ts
Labels: Ready for Release, mode:cloud, actions:core, team:segment

#2851 Update Rokt-Audiences Destination to support emailsha256 values
  packages/destination-actions/src/destinations/rokt-audiences/index.ts
  packages/destination-actions/src/destinations/rokt-audiences/upsertCustomAudiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/rokt-audiences/upsertCustomAudiences/custom-audience-operations.ts
  packages/destination-actions/src/destinations/rokt-audiences/upsertCustomAudiences/generated-types.ts
  packages/destination-actions/src/destinations/rokt-audiences/upsertCustomAudiences/index.ts
Labels: Ready for Release, mode:cloud, deploy:push, team:external

#2842 Postscript Events for Entered/Exit Segment Audience
  packages/destination-actions/src/destinations/postscript/syncAudiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/postscript/syncAudiences/index.ts
Labels: Ready for Release, mode:cloud, team:external

#2819 [Podscribe] New hashed_email property field
  packages/destination-actions/src/destinations/podscribe/generated-types.ts
  packages/destination-actions/src/destinations/podscribe/index.ts
  packages/destination-actions/src/destinations/podscribe/page/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/podscribe/page/__tests__/index.test.ts
  packages/destination-actions/src/destinations/podscribe/page/index.ts
  packages/destination-actions/src/destinations/podscribe/track/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/podscribe/track/__tests__/index.test.ts
  packages/destination-actions/src/destinations/podscribe/track/index.ts
  packages/destination-actions/src/destinations/podscribe/utils.ts
Labels: Ready for Release, mode:cloud, deploy:push, team:external

#2888 STRATCONN-5564 - add sales objects
  packages/destination-actions/src/destinations/hubspot/upsertObject/constants.ts
Labels: Ready for Release, mode:cloud, team:segment
