Repository segmentio/action-destinations, pull requests merged in 2025-05, with the labels that each got.

#2898 Stratconn 5564 add objects
  packages/destination-actions/src/destinations/hubspot/upsertObject/constants.ts
Labels: Ready for Release, team:segment-core, mode:cloud, deploy:push

#2896 [BRAZE] - adding new regions for Braze
  packages/destination-actions/src/destinations/braze/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2897 Add User-Agent header to Drip destination for source identification
  packages/destination-actions/src/destinations/drip/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2893 small updates to the default mappings in the Reddit CAPI integration
  packages/destination-actions/src/destinations/reddit-conversions-api/__tests__/index.test.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/customEvent/generated-types.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/fields.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/index.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/standardEvent/generated-types.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2883 [Smart Hashing] [Liveramp Audiences] Cleanup
  packages/core/src/__tests__/hashing-utils.test.ts
  packages/core/src/hashing-utils.ts
  packages/core/src/index.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/__tests__/fb-operations.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/__tests__/index.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/operations.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/operations.ts
  packages/destination-actions/src/lib/hashing-utils.test.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, actions:core, team:segment

#2880 [STRATCONN-5489] - Add batch_keys to Klaviyo actions
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/index.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/unsubscribeProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/unsubscribeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2878 [STRATCONN-5657] - Add batch keys to webhook action destination
  packages/destination-actions/src/destinations/webhook-audiences/index.ts
  packages/destination-actions/src/destinations/webhook-audiences/send.types.ts
  packages/destination-actions/src/destinations/webhook/__test__/webhook.test.ts
  packages/destination-actions/src/destinations/webhook/send/generated-types.ts
  packages/destination-actions/src/destinations/webhook/send/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2838 [Userpilot] Add support for group method in cloud destination
  packages/destination-actions/src/destinations/userpilot/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/userpilot/identifyCompany/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/userpilot/identifyCompany/__tests__/index.test.ts
  packages/destination-actions/src/destinations/userpilot/identifyCompany/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/userpilot/identifyCompany/generated-types.ts
  packages/destination-actions/src/destinations/userpilot/identifyCompany/index.ts
  packages/destination-actions/src/destinations/userpilot/index.ts
  packages/destination-actions/src/destinations/userpilot/request-utils.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2792 Loops destination: ability to sync contact properties when sending events
  packages/destination-actions/src/destinations/loops/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/loops/createOrUpdateContact/index.ts
  packages/destination-actions/src/destinations/loops/sendEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/loops/sendEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/loops/sendEvent/generated-types.ts
  packages/destination-actions/src/destinations/loops/sendEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2766 [TOPSORT] fix: wrong mapping for purchase event & added optional vendor_id
  packages/destination-actions/src/destinations/topsort/purchase/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/topsort/purchase/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/topsort/purchase/__tests__/index.test.ts
  packages/destination-actions/src/destinations/topsort/purchase/generated-types.ts
  packages/destination-actions/src/destinations/topsort/purchase/index.ts
Labels: Ready for Release, partner-eng-review (cloud), eng-acknowledged, mode:cloud, deploy:push, team:external

#2860 [Smart Hashing] Add smart hashing documentation in readme
  README.md
Labels: not-partner-eng-review (cloud), team:segment

#2861 [Smart Hashing] Add eslint rule to limit usage of createHash from crypto module
  .eslintrc.js
  packages/destination-actions/src/destinations/criteo-audiences/criteo-audiences.ts
  packages/destination-actions/src/destinations/emarsys/emarsys-helper.ts
  packages/destination-actions/src/destinations/engage-messaging-sendgrid/previewApiLookup/apiLookups.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/postConversion/formatter.ts
  packages/destination-actions/src/destinations/nextdoor-capi/sendConversion/utils.ts
  packages/destination-actions/src/destinations/reddit-audiences/syncAudience/functions.ts
  packages/destination-actions/src/destinations/singlestore/index.ts
  packages/destination-actions/src/destinations/singlestore/util.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/utils.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/functions.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/client.ts
  packages/destination-actions/src/destinations/the-trade-desk-crm/functions.ts
  packages/destination-actions/src/destinations/tiktok-conversions-sandbox/formatter.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions-sandbox/formatter.ts
Labels: not-partner-eng-review (cloud), mode:cloud, team:segment

#2877 [Smart Hashing] Cleanup
  packages/destination-actions/src/destinations/amazon-amc/function.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToAudContactInfo/_tests_/index.test.ts
  packages/destination-actions/src/destinations/first-party-dv360/addToAudContactInfo/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/functions.ts
  packages/destination-actions/src/destinations/first-party-dv360/removeFromAudContactInfo/_tests_/index.test.ts
  packages/destination-actions/src/destinations/first-party-dv360/removeFromAudContactInfo/index.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionAdjustmentUpload/index.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionUpload/index.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/utils.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/api/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
  packages/destination-actions/src/destinations/pinterest-conversions/pinterset-capi-user-data.ts
  packages/destination-actions/src/destinations/pinterest-conversions/reportConversionEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/pinterest-conversions/reportConversionEvent/index.ts
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-v3.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/utils.ts
  packages/destination-actions/src/destinations/yahoo-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/yahoo-audiences/updateSegment/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/utils-rt.ts
Labels: not-partner-eng-review (cloud), mode:cloud, team:segment

#2879 [Smart Hashing] Cleanup
  packages/destination-actions/src/destinations/delivrai-activate/updateSegment/index.ts
  packages/destination-actions/src/destinations/delivrai-activate/utils-rt.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/helpers.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/__tests__/index.test.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/customEvent/index.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/standardEvent/index.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/utils.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addToAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/addUser/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/functions.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeFromAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/removeUser/index.ts
  packages/destination-actions/src/destinations/tiktok-conversions/formatter.ts
  packages/destination-actions/src/destinations/tiktok-conversions/reportWebEvent/index.ts
  packages/destination-actions/src/destinations/tiktok-conversions/utils.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/formatter.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/reportOfflineEvent/index.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/trackNonPaymentOfflineConversion/index.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/trackPaymentOfflineConversion/index.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/utils.ts
Labels: not-partner-eng-review (cloud), mode:cloud, team:segment

#2910 STRATCONN-5564: add quotes object support
  packages/destination-actions/src/destinations/hubspot/upsertObject/constants.ts
Labels: Ready for Release, team:segment-core, mode:cloud, deploy:push

#2894 Update subscription presets and action descriptions for audience destinations for Journeys V2
  packages/destination-actions/src/destinations/amazon-amc/index.ts
  packages/destination-actions/src/destinations/aws-s3/index.ts
  packages/destination-actions/src/destinations/delivrai-activate/index.ts
  packages/destination-actions/src/destinations/display-video-360/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/index.ts
  packages/destination-actions/src/destinations/iterable-lists/index.ts
  packages/destination-actions/src/destinations/iterable/index.ts
  packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
  packages/destination-actions/src/destinations/klaviyo/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/index.ts
  packages/destination-actions/src/destinations/reddit-audiences/index.ts
  packages/destination-actions/src/destinations/reddit-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/index.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/snap-audiences/index.ts
  packages/destination-actions/src/destinations/snap-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/taboola-actions/index.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/index.ts
  packages/destination-actions/src/destinations/webhook-audiences/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/index.ts
Labels: not-partner-eng-review (cloud), mode:cloud, team:segment

#2914 Update Drip identify batch endpoint
  packages/destination-actions/src/destinations/drip/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/drip/identify/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2913 [EagleEye] - new Destination
  packages/destination-actions/src/destinations/eagleeye/generated-types.ts
  packages/destination-actions/src/destinations/eagleeye/index.ts
  packages/destination-actions/src/destinations/eagleeye/triggerBehavioralAction/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/eagleeye/triggerBehavioralAction/__tests__/index.test.ts
  packages/destination-actions/src/destinations/eagleeye/triggerBehavioralAction/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/eagleeye/triggerBehavioralAction/generated-types.ts
  packages/destination-actions/src/destinations/eagleeye/triggerBehavioralAction/index.ts
  packages/destination-actions/src/destinations/eagleeye/triggerBehavioralAction/types.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, team:segment-core, mode:cloud, deploy:push

#2911 new Dub Destination
  packages/destination-actions/src/destinations/dub/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/dub/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/dub/config.ts
  packages/destination-actions/src/destinations/dub/generated-types.ts
  packages/destination-actions/src/destinations/dub/index.ts
  packages/destination-actions/src/destinations/dub/trackLead/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/dub/trackLead/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dub/trackLead/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/dub/trackLead/generated-types.ts
  packages/destination-actions/src/destinations/dub/trackLead/index.ts
  packages/destination-actions/src/destinations/dub/trackLead/types.ts
  packages/destination-actions/src/destinations/dub/trackSale/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/dub/trackSale/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dub/trackSale/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/dub/trackSale/generated-types.ts
  packages/destination-actions/src/destinations/dub/trackSale/index.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, team:segment-core, mode:cloud, deploy:push

#2909 [STRATCONN 5804] [Google Ads Conversions] Update Canary API Version to v19
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/functions.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/userList.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2908 Facebook Custom Audiences - Engage Support
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/__tests__/index.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/generated-types.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/index.ts
Labels: Ready for Release, team:segment-core, mode:cloud, deploy:push

#2906 Adds warehouse mode to destination kit
  packages/core/src/destination-kit/index.ts
  packages/core/src/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), actions:core, team:segment

#2903 [Smart Hashing] Rename processHashingV2 back to processHashing
  packages/destination-actions/src/destinations/amazon-amc/function.ts
  packages/destination-actions/src/destinations/delivrai-activate/utils-rt.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/helpers.ts
  packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-user-data.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/__tests__/fb-operations.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/fbca-operations.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/__tests__/index.test.ts
  packages/destination-actions/src/destinations/first-party-dv360/functions.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/utils.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment2/index.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/api/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/operations.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/operations.ts
  packages/destination-actions/src/destinations/pinterest-conversions/pinterset-capi-user-data.ts
  packages/destination-actions/src/destinations/podscribe/track/index.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/utils.ts
  packages/destination-actions/src/destinations/snap-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/snap-audiences/syncAudience/utils.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/snap-capi-v3.ts
  packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/utils.ts
  packages/destination-actions/src/destinations/tiktok-audiences/functions.ts
  packages/destination-actions/src/destinations/tiktok-conversions/formatter.ts
  packages/destination-actions/src/destinations/tiktok-offline-conversions/formatter.ts
  packages/destination-actions/src/destinations/yahoo-audiences/utils-rt.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2899 [Stackadapt Audiences] - API / Schema upgrade
  packages/destination-actions/src/destinations/stackadapt-audiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/functions.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardProfile/functions.ts
Labels: Ready for Release, partner-eng-review (cloud)

#2695 Fix incorrect mapping in mixpanel destination
  packages/destination-actions/src/destinations/mixpanel/mixpanel-properties.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2650 add `Report Content Event` to customerio destination
  packages/destination-actions/src/destinations/customerio/__tests__/reportContentEvent.test.ts
  packages/destination-actions/src/destinations/customerio/index.ts
  packages/destination-actions/src/destinations/customerio/reportContentEvent/generated-types.ts
  packages/destination-actions/src/destinations/customerio/reportContentEvent/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2917 [CM-360] - fixing timestamp
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionAdjustmentUpload/__tests__/index.test.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionUpload/__tests__/index.test.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2918 [Reddit Audiences] - fixing minor field issue
  packages/destination-actions/src/destinations/reddit-audiences/syncAudience/generated-types.ts
  packages/destination-actions/src/destinations/reddit-audiences/syncAudience/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2926 [Facebook Custom Audiences] - fixing fb breaking test
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/__tests__/index.test.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2928 [Deployment] - registering 3 new Destinations
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2905 Introduces Liquid template directives
  package.json
  packages/browser-destinations/liquid.stub.js
  packages/browser-destinations/webpack.config.js
  packages/core/src/mapping-kit/__tests__/liquid.test.ts
  packages/core/src/mapping-kit/index.ts
  packages/core/src/mapping-kit/liquid-directive.ts
  packages/core/src/mapping-kit/validate.ts
  packages/core/src/mapping-kit/value-keys.ts
  yarn.lock
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, actions:core, actions:mappingkit

#2907 Better error handling for Google Enhanced Conversions Create Audience
  packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2902 Explicitely handle CreateAudienceErrors for Facebook Custom Audiences
  packages/destination-actions/src/destinations/facebook-custom-audiences/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2933 [Podscribe] Send full property object to destination
  packages/destination-actions/src/destinations/podscribe/track/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/podscribe/track/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/podscribe/track/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2932 Add batch_size to identify fields in Drip (Actions)
  packages/destination-actions/src/destinations/drip/identify/generated-types.ts
  packages/destination-actions/src/destinations/drip/identify/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2938 [Ortto] - allow additional in traits field
  packages/destination-actions/src/destinations/ortto/common-fields.ts
  packages/destination-actions/src/destinations/ortto/trackActivity/generated-types.ts
  packages/destination-actions/src/destinations/ortto/trackActivity/index.ts
  packages/destination-actions/src/destinations/ortto/upsertContactProfile/generated-types.ts
  packages/destination-actions/src/destinations/ortto/upsertContactProfile/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2923 [Dot Digital] new Destination
  packages/destination-actions/src/destinations/dotdigital/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dotdigital/addContactToList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dotdigital/addContactToList/generated-types.ts
  packages/destination-actions/src/destinations/dotdigital/addContactToList/index.ts
  packages/destination-actions/src/destinations/dotdigital/api/dd-api.ts
  packages/destination-actions/src/destinations/dotdigital/api/index.ts
  packages/destination-actions/src/destinations/dotdigital/api/resources/dd-contact-api.ts
  packages/destination-actions/src/destinations/dotdigital/api/resources/dd-datafields-api.ts
  packages/destination-actions/src/destinations/dotdigital/api/resources/dd-enrolment-api.ts
  packages/destination-actions/src/destinations/dotdigital/api/resources/dd-lists-api.ts
  packages/destination-actions/src/destinations/dotdigital/api/types.ts
  packages/destination-actions/src/destinations/dotdigital/enrolContact/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dotdigital/enrolContact/generated-types.ts
  packages/destination-actions/src/destinations/dotdigital/enrolContact/index.ts
  packages/destination-actions/src/destinations/dotdigital/generated-types.ts
  packages/destination-actions/src/destinations/dotdigital/index.ts
  packages/destination-actions/src/destinations/dotdigital/input-fields/contact-identifier.ts
  packages/destination-actions/src/destinations/dotdigital/input-fields/index.ts
  packages/destination-actions/src/destinations/dotdigital/input-fields/types.ts
  packages/destination-actions/src/destinations/dotdigital/removeContactFromList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/dotdigital/removeContactFromList/generated-types.ts
  packages/destination-actions/src/destinations/dotdigital/removeContactFromList/index.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, team:segment-core, mode:cloud, deploy:push

#2858 add intercom_user_jwt
  packages/browser-destinations/destinations/intercom/src/identifyUser/__tests__/index.test.ts
  packages/browser-destinations/destinations/intercom/src/identifyUser/generated-types.ts
  packages/browser-destinations/destinations/intercom/src/identifyUser/index.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:push, team:external, mode:device

#2946 Fixing main
  .yarn/install-state.gz
  .yarnrc.yml
  packages/destination-actions/src/destinations/drip/identify/generated-types.ts
  packages/destination-actions/src/destinations/reddit-conversions-api/utils.ts
Labels: team:segment-core, mode:cloud, deploy:push
