Repository segmentio/action-destinations, pull requests merged in 2025-07, with the labels that each got.

#3030 Upgrade typescript to 5.5.4
  .eslintrc.js
  package.json
  packages/core/package.json
  packages/destination-actions/package.json
  yarn.lock
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, actions:core

#3041 Revert "Upgrade typescript to 5.5.4"
  .eslintrc.js
  package.json
  packages/core/package.json
  packages/destination-actions/package.json
  yarn.lock
Labels: team:segment-core, actions:core

#2924 [Hubspot] Add de-duplication logic in Hubspot
  packages/destination-actions/src/destinations/hubspot/upsertObject/__tests__/validate.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/common-fields.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/constants.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/functions/validation-functions.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/generated-types.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/index.ts
  packages/destination-actions/src/destinations/hubspot/upsertObject/types.ts
Labels: partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#3048 Adds copilot agent guidelines
  .github/copilot-instructions.md
  docs/pr-guidelines/pr-checks.md
  docs/pr-guidelines/pull-request-guidance.md
Labels: team:segment-core

#3064 [Facebook CAPI Web] - fixing bad presets
  packages/browser-destinations/destinations/facebook-conversions-api-web/src/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:device

#3066 feat: Add comprehensive test suite for Aampe destination
  packages/destination-actions/src/destinations/aampe/__tests__/index.test.ts
  packages/destination-actions/src/destinations/aampe/fields.ts
  packages/destination-actions/src/destinations/aampe/index.ts
  packages/destination-actions/src/destinations/aampe/sendEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/aampe/sendEvent/generated-types.ts
  packages/destination-actions/src/destinations/aampe/sendEvent/index.ts
  packages/destination-actions/src/destinations/aampe/types.ts
  packages/destination-actions/src/destinations/aampe/upsertUserProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/aampe/upsertUserProfile/generated-types.ts
  packages/destination-actions/src/destinations/aampe/upsertUserProfile/index.ts
Labels: mode:cloud, deploy:push, team:external

#3068 [EagleEye] - Converting to Audience Destination
  packages/destination-actions/src/destinations/eagleeye-audiences/generated-types.ts
  packages/destination-actions/src/destinations/eagleeye-audiences/index.ts
  packages/destination-actions/src/destinations/eagleeye-audiences/triggerBehavioralAction/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/eagleeye-audiences/triggerBehavioralAction/__tests__/index.test.ts
  packages/destination-actions/src/destinations/eagleeye-audiences/triggerBehavioralAction/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/eagleeye-audiences/triggerBehavioralAction/generated-types.ts
  packages/destination-actions/src/destinations/eagleeye-audiences/triggerBehavioralAction/index.ts
  packages/destination-actions/src/destinations/eagleeye-audiences/triggerBehavioralAction/types.ts
  packages/destination-actions/src/destinations/eagleeye/generated-types.ts
  packages/destination-actions/src/destinations/eagleeye/index.ts
  packages/destination-actions/src/destinations/index.ts
Labels: partner-eng-review (cloud), deploy:registration, team:segment-core, mode:cloud, deploy:push

#3069 Registering Eagle Eye Audiences destination
  packages/destination-actions/src/destinations/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#3071 [Eagleeye] - mapping bugfix
  packages/destination-actions/src/destinations/eagleeye-audiences/triggerBehavioralAction/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#3067 [Attentive] - Bug fixes
  packages/destination-actions/src/destinations/attentive/customEvents/index.ts
  packages/destination-actions/src/destinations/attentive/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#3073 [Aampe] - Register new Destination
  packages/destination-actions/src/destinations/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#3075 [Singlestore] - add batch size limits
  packages/destination-actions/src/destinations/singlestore/send/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#3076 STRATCONN-5928: Enable editing batch_size for Amazon AMC
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/generated-types.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#3079 [Aampe] - Fixing linting issue breaking build
  packages/destination-actions/src/destinations/aampe/__tests__/snapshot.test.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#3088 s3_aws_region marked required
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/generated-types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/index.ts
Labels: not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#3039 Stratconn 6002 braze canvas trigger
  packages/destination-actions/src/destinations/braze/index.ts
  packages/destination-actions/src/destinations/braze/triggerCanvas/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/braze/triggerCanvas/__tests__/dynamic-field-functions.test.ts
  packages/destination-actions/src/destinations/braze/triggerCanvas/__tests__/index.test.ts
  packages/destination-actions/src/destinations/braze/triggerCanvas/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/braze/triggerCanvas/functions/dynamic-field-functions.ts
  packages/destination-actions/src/destinations/braze/triggerCanvas/generated-types.ts
  packages/destination-actions/src/destinations/braze/triggerCanvas/index.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#3065 added context.personas.computation_key for update audience
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud

#3096 [ACTVTNS-161] Update Email Field Intercom
  packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
Labels: mode:cloud, team:segment

#3087 Updated SingleStore table data types
  packages/destination-actions/src/destinations/singlestore/index.ts
  packages/destination-actions/src/destinations/singlestore/send/__tests__/index.test.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2940 [Google Enhanced Conversions]- adding additional validation for gclid wbraid and gbraid
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion2.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion2/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#3011 [TOPSORT] feat: impressions list
  packages/destination-actions/src/destinations/topsort/impressionsList/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/topsort/impressionsList/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/topsort/impressionsList/__tests__/index.test.ts
  packages/destination-actions/src/destinations/topsort/impressionsList/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/topsort/impressionsList/generated-types.ts
  packages/destination-actions/src/destinations/topsort/impressionsList/index.ts
  packages/destination-actions/src/destinations/topsort/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#3081 Add new integration_source api file for segment creation/sync
  packages/destination-actions/src/destinations/taboola-actions/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taboola-actions/index.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/taboola-actions/syncAudience/client.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#3102 [Epsilon] - register new destination
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#3118 STRATCONN-6002 - braze canvas trigger
  packages/destination-actions/src/destinations/braze/index.ts
Labels: team:segment-core, mode:cloud

#3117 STRATCONN-6096 - [Insider] - SD-123243 | change email field from required to optional
  packages/destination-actions/src/destinations/insider-audiences/insider-helpers.ts
  packages/destination-actions/src/destinations/insider-audiences/insiderAudiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/insider-audiences/insiderAudiences/generated-types.ts
  packages/destination-actions/src/destinations/insider-audiences/insiderAudiences/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#3092 STRATCONN-6051 - [Clay] - New Destination
  packages/destination-actions/src/destinations/clay/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/clay/__tests__/index.test.ts
  packages/destination-actions/src/destinations/clay/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/clay/generated-types.ts
  packages/destination-actions/src/destinations/clay/index.ts
  packages/destination-actions/src/destinations/clay/pageVisit/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/clay/pageVisit/__tests__/index.test.ts
  packages/destination-actions/src/destinations/clay/pageVisit/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/clay/pageVisit/generated-types.ts
  packages/destination-actions/src/destinations/clay/pageVisit/index.ts
  packages/destination-actions/src/destinations/clay/track/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/clay/track/__tests__/index.test.ts
  packages/destination-actions/src/destinations/clay/track/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/clay/track/generated-types.ts
  packages/destination-actions/src/destinations/clay/track/index.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#3119 [MAIN] [STRATCONN-6079] : SFMC-Mark specific error to retryable error status 500 if status code 400 is returned from SFMC in specific situation.
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/multistatus.test.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-operations.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/types.ts
Labels: not-partner-eng-review (cloud), mode:cloud, team:segment

#3111 Amazon Conversions API - Adding validation to pass currencyCode and unitsSold only when event type is OFF_AMAZON_PURCHASES
  packages/destination-actions/src/destinations/amazon-conversions-api/trackConversion/__tests__/utils.test.ts
  packages/destination-actions/src/destinations/amazon-conversions-api/trackConversion/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#3085 [STRATCONN-6006] - CM360 handle 200 responses with errors
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionAdjustmentUpload/__tests__/index.test.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionUpload/__tests__/index.test.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/types.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#3122 Registering Clay Destination
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#3090 STRATCONN-6039 [Livelike] - new Action
  packages/destination-actions/src/destinations/livelike-cloud/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/livelike-cloud/__tests__/index.test.ts
  packages/destination-actions/src/destinations/livelike-cloud/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/livelike-cloud/constants.ts
  packages/destination-actions/src/destinations/livelike-cloud/index.ts
  packages/destination-actions/src/destinations/livelike-cloud/syncToUserGroup/__tests__/index.test.ts
  packages/destination-actions/src/destinations/livelike-cloud/syncToUserGroup/generated-types.ts
  packages/destination-actions/src/destinations/livelike-cloud/syncToUserGroup/index.ts
  packages/destination-actions/src/destinations/livelike-cloud/syncToUserGroup/types.ts
  packages/destination-actions/src/destinations/livelike-cloud/syncToUserGroup/utils.ts
  packages/destination-actions/src/destinations/livelike-cloud/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/livelike-cloud/trackEvent/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#3120 scaffold new bing ads audiences destination
  packages/destination-actions/src/destinations/bing-ads-audiences/generated-types.ts
  packages/destination-actions/src/destinations/bing-ads-audiences/index.ts
Labels: partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:segment
