Repository segmentio/action-destinations, pull requests merged in 2025-08, with the labels that each got.

#3132 [Bing Ads Audiences] Add description in action
  packages/destination-actions/src/destinations/bing-ads-audiences/syncAudiences/index.ts
Labels: partner-eng-review (cloud), mode:cloud, team:segment

#3055 [Braze] Fix US-09 REST endpoint
  packages/destination-actions/src/destinations/braze/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#3136 [Attentive] - bug fixes post testing
  packages/destination-actions/src/destinations/attentive/ecommEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/attentive/ecommEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/attentive/fields.ts
  packages/destination-actions/src/destinations/attentive/functions.ts
  packages/destination-actions/src/destinations/attentive/subscribeUser/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/attentive/types.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#3141 Registering 2 new Destinations
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#3143 [STRATCONN-6025] - Update default batch size for S3 action
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#3095 Stackadapt-Audience: add isPii field to upsertExternalAudienceMapping query
  packages/destination-actions/src/destinations/stackadapt-audiences/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardAudienceEvent/functions.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/forwardProfile/__tests__/index.test.ts
  packages/destination-actions/src/destinations/stackadapt-audiences/functions.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#3145 NTTS-341 Add specificEvent presets to the snowflake destination for linked audiences
  packages/warehouse-destinations/src/destinations/snowflake/index.ts
  packages/warehouse-destinations/src/destinations/snowflake/sendCustomEvent/audience-default-fields.ts
  packages/warehouse-destinations/src/destinations/snowflake/sendCustomEvent/generated-types.ts
  packages/warehouse-destinations/src/destinations/snowflake/sendCustomEvent/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), deploy:push, team:segment

#3178 rethrowing error for CM360
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionAdjustmentUpload/__tests__/index.test.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/conversionUpload/__tests__/index.test.ts
  packages/destination-actions/src/destinations/google-campaign-manager-360/utils.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#3181 [Epsilon] - making company magic a separate setting field
  packages/destination-actions/src/destinations/epsilon/generated-types.ts
  packages/destination-actions/src/destinations/epsilon/index.ts
  packages/destination-actions/src/destinations/epsilon/sendEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/epsilon/sendEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/epsilon/sendEvent/index.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#3177 STRATCONN-6128 - fix unsubscribe list bug
  packages/destination-actions/src/destinations/iterable-lists/syncAudience/iterable-client.ts
  packages/destination-actions/src/destinations/iterable-lists/types.ts
Labels: partner-eng-review (cloud), team:segment-core, mode:cloud

#3024 Pipes through statsContext to evaluateLiquid directive function
  packages/core/src/destination-kit/action.ts
  packages/core/src/destination-kit/index.ts
  packages/core/src/mapping-kit/index.ts
  packages/core/src/mapping-kit/liquid-directive.ts
Labels: Ready for Release, not-partner-eng-review (cloud), actions:core, team:segment, actions:mappingkit

#3185 Enhance GitHub Copilot instructions
  .github/copilot-instructions.md
Labels: not-partner-eng-review (cloud), team:segment-core

#3180 Add @aws-sdk/client-sts dependency
  package.json
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core
