Repository segmentio/action-destinations, pull requests merged in 2025-01, with the labels that each got.

#2666 Worked on fixing braze_id default mappings of Braze Actions.
  packages/destination-actions/src/destinations/braze/__tests__/__snapshots__/braze.test.ts.snap
  packages/destination-actions/src/destinations/braze/__tests__/braze.test.ts
  packages/destination-actions/src/destinations/braze/__tests__/multistatus.test.ts
  packages/destination-actions/src/destinations/braze/updateUserProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/removeProfile/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2646 Braze regions
  packages/browser-destinations/destinations/braze/src/index.ts
  packages/destination-actions/src/destinations/braze/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external, mode:device

#2664 [Sendgrid lists] - multistatus responses
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/index.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/utils.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/types.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2661 [STRATCONN-4101 & STRATCONN - 4099] Update Amazon Ads normalisation
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2657 Update field descriptions to be in line with Amplitude functionality
  packages/destination-actions/src/destinations/amplitude/logEventV2/generated-types.ts
  packages/destination-actions/src/destinations/amplitude/logEventV2/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2655 [TOPSORT] Action Definitions for Banner Events
  packages/destination-actions/src/destinations/topsort/click/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/topsort/click/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/topsort/click/__tests__/index.test.ts
  packages/destination-actions/src/destinations/topsort/click/generated-types.ts
  packages/destination-actions/src/destinations/topsort/click/index.ts
  packages/destination-actions/src/destinations/topsort/impression/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/topsort/impression/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/topsort/impression/__tests__/index.test.ts
  packages/destination-actions/src/destinations/topsort/impression/generated-types.ts
  packages/destination-actions/src/destinations/topsort/impression/index.ts
  packages/destination-actions/src/destinations/topsort/index.ts
  yarn.lock
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, deploy:push, team:external

#2647 [SFMC] Remove stats for SFMC
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/contactDataExtension/index.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/dataExtension/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2645 Update: Format Date type objects to permissible Iterable date string
  packages/destination-actions/src/destinations/iterable/updateUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/iterable/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:external

#2671 [SendGrid]- sendEmail Action - change to default mappings for cc and bcc fields
  packages/destination-actions/src/destinations/sendgrid/sendEmail/fields.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/generated-types.ts
  packages/destination-actions/src/destinations/sendgrid/sendEmail/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2668 Normalize email addresses for Google Enhanced Conversions
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2669 [STRATCONN] [MAIN] Updated all the data processing states of FCAPI
  packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-properties.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2667 allow custom global key for Koala
  packages/browser-destinations/destinations/koala/src/init-script.ts
Labels: Ready for Release, not-partner-eng-review (device), team:external, mode:device

#2660 [MAIN] [STRATCONN] Intercom web custom inbox button selector
  packages/browser-destinations/destinations/intercom/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/intercom/src/index.ts
  packages/browser-destinations/destinations/intercom/src/init-script.ts
Labels: Ready for Release, not-partner-eng-review (device), team:segment, mode:device

#2536 [MAIN] [STRATCONN] 4261 Mixpanel Multistatus support
  packages/destination-actions/src/destinations/mixpanel/__test__/multistatus.test.ts
  packages/destination-actions/src/destinations/mixpanel/common/utils.ts
  packages/destination-actions/src/destinations/mixpanel/trackEvent/index.ts
  packages/destination-actions/src/destinations/mixpanel/trackPurchase/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2680 Braze regions
  packages/destination-actions/src/destinations/braze-cohorts/index.ts
Labels: Ready for Release, mode:cloud, team:segment

#2679 [Optimizely Web] - major refactor and testing
  packages/destination-actions/src/destinations/optimizely-web/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-web/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/optimizely-web/index.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/__tests__/page.test.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/__tests__/track.test.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/client.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/constants.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/fields.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/index.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/types.ts
  packages/destination-actions/src/destinations/optimizely-web/trackEvent/utils.ts
Labels: Ready for Release, team:segment-core, mode:cloud, deploy:push

#2639 [SFMC] Add Multistatus Support for SFMC
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/multistatus.test.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/contactDataExtension/index.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/dataExtension/index.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-operations.ts
  packages/destination-actions/src/destinations/salesforce-marketing-cloud/types.ts
Labels: not-partner-eng-review (cloud), mode:cloud, team:segment

#2663 [STRATCONN-5314] | Multistatus support on amazon-amc
  packages/destination-actions/src/destinations/amazon-amc/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/function.ts
  packages/destination-actions/src/destinations/amazon-amc/index.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/__tests__/index.test.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/index.ts
  packages/destination-actions/src/destinations/amazon-amc/utils.ts
Labels: not-partner-eng-review (cloud), mode:cloud, team:segment

#2685 Revert "update: update VWO SmartCode to version 2.1"
  packages/browser-destinations/destinations/vwo/src/init-script.ts
Labels: team:segment-core, mode:device

#2689 [LinkedIn Conversions] Bumps linkedin version to 202411 since 202401 has been deprecated
  packages/destination-actions/src/destinations/linkedin-conversions/constants.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud

#2686 updating smart code snippet to not cause opacity 0 in hide element style
  packages/browser-destinations/destinations/vwo/src/init-script.ts
Labels: partner-eng-review (device), team:segment, mode:device

#2665 [HEAP] update browser destination code to load heap js v5 script
  packages/browser-destinations/destinations/heap/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/heap/src/generated-types.ts
  packages/browser-destinations/destinations/heap/src/identifyUser/__tests__/index.test.ts
  packages/browser-destinations/destinations/heap/src/index.ts
  packages/browser-destinations/destinations/heap/src/init-script.ts
  packages/browser-destinations/destinations/heap/src/test-utilities.ts
  packages/browser-destinations/destinations/heap/src/trackEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/heap/src/types.ts
Labels: partner-eng-review (device), deploy:push, team:external, mode:device

#2690 [SendGrid Lists] - updating default mapping
  packages/destination-actions/src/destinations/sendgrid-audiences/syncAudience/fields.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2688 [Google Ads] Send non-American country codes correctly
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/functions.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2681 Allowing pre-hashed emails for Criteo Audiences.
  packages/destination-actions/src/destinations/criteo-audiences/addUserToAudience/index.ts
  packages/destination-actions/src/destinations/criteo-audiences/removeUserFromAudience/index.ts
Labels: Ready for Release, partner-eng-review (cloud), mode:cloud, team:segment

#2675 [STRATCONN-5384] Update LiveRamp phone_number hashing algo
  packages/core/src/__tests__/hashing-utils.test.ts
  packages/core/src/hashing-utils.ts
  packages/core/src/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/operations.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/operations.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, actions:core

#2619 [Antavo ] New Antavo Destination
  packages/destination-actions/src/destinations/antavo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/antavo/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/antavo/event/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/antavo/event/__tests__/event.test.ts
  packages/destination-actions/src/destinations/antavo/event/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/antavo/event/generated-types.ts
  packages/destination-actions/src/destinations/antavo/event/index.ts
  packages/destination-actions/src/destinations/antavo/generated-types.ts
  packages/destination-actions/src/destinations/antavo/index.ts
  packages/destination-actions/src/destinations/antavo/profile/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/antavo/profile/__tests__/profile.test.ts
  packages/destination-actions/src/destinations/antavo/profile/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/antavo/profile/generated-types.ts
  packages/destination-actions/src/destinations/antavo/profile/index.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, mode:cloud, deploy:push, team:external

#2674 [STRATCONN-5399]-Handles refresh token retry for multistatus responses
  packages/core/src/__tests__/destination-kit.test.ts
  packages/core/src/destination-kit/index.ts
  packages/core/src/retry.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, actions:core

#2698 Registers new "Antavo" destination
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2700 [liveramp] Hotfix: Imports hashing functions with the same syntax as other imports
  packages/destination-actions/src/destinations/liveramp-audiences/operations.ts
Labels: team:segment-core, mode:cloud

#2692 [Multiple Destinations] - cleaning up some test noise
  packages/cli/src/commands/validate.ts
  packages/destination-actions/src/destinations/1plusx-asset-api/__tests__/index.test.ts
  packages/destination-actions/src/destinations/actable-predictive/sendCustomEvent/index.ts
  packages/destination-actions/src/destinations/actable-predictive/sendEmailEvent/index.ts
  packages/destination-actions/src/destinations/actable-predictive/sendTransactionEvent/index.ts
  packages/destination-actions/src/destinations/actable-predictive/sendWebEvent/index.ts
  packages/destination-actions/src/destinations/delivrai-activate/updateSegment/index.ts
  packages/destination-actions/src/destinations/friendbuy/trackCustomer/__tests__/index.test.ts
  packages/destination-actions/src/destinations/friendbuy/trackPurchase/__tests__/index.test.ts
  packages/destination-actions/src/destinations/friendbuy/trackSignUp/__tests__/index.test.ts
  packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#2705 [STRATCONN-5380] - Fix google enhanced conversion error parsing
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/userList.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#2696 [FUNK-1643] add bearer token to webhook extensible
  packages/destination-actions/src/destinations/webhook-extensible/index.ts
Labels: Ready for Release, mode:cloud, team:segment

#2099 Required Fields V2 - Conditionally Required Fields
  README.md
  packages/core/src/__tests__/__snapshots__/schema-validation.test.ts.snap
  packages/core/src/__tests__/schema-validation.test.ts
  packages/core/src/destination-kit/fields-to-jsonschema.ts
  packages/core/src/destination-kit/types.ts
  packages/destination-actions/src/destinations/salesforce/lead/index.ts
  packages/destination-actions/src/destinations/salesforce/sf-properties.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud, actions:core
