Repository segmentio/action-destinations, pull requests merged in 2025-06, with the labels that each got.

#2955 [Nextdoor] - minor changes to Nextdoor
  packages/destination-actions/src/destinations/nextdoor-capi/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/nextdoor-capi/__tests__/index.test.ts
  packages/destination-actions/src/destinations/nextdoor-capi/sendConversion/generated-types.ts
  packages/destination-actions/src/destinations/nextdoor-capi/sendConversion/index.ts
  packages/destination-actions/src/destinations/nextdoor-capi/sendConversion/types.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2960 [Amazon Ads CAPI] correcting Slug name for amazon capi destination
  packages/destination-actions/src/destinations/amazon-conversions-api/index.ts
Labels: partner-eng-review (cloud)

#2959 Stratconn 5875/add braze catalog hook
  packages/destination-actions/src/destinations/braze/upsertCatalogItem/__tests__/index.test.ts
  packages/destination-actions/src/destinations/braze/upsertCatalogItem/generated-types.ts
  packages/destination-actions/src/destinations/braze/upsertCatalogItem/index.ts
  packages/destination-actions/src/destinations/braze/upsertCatalogItem/utils.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2963 [Amazon CAPI] - Fixing breaking test
  packages/destination-actions/src/destinations/amazon-conversions-api/__tests__/index.test.ts
Labels: team:segment-core, mode:cloud

#2968 Revert "[MAIN][STRATCONN] Added prefix [Segment] in event_type of amplitude"
  packages/destination-actions/src/destinations/amplitude/__tests__/amplitude.test.ts
  packages/destination-actions/src/destinations/amplitude/logEvent/index.ts
  packages/destination-actions/src/destinations/amplitude/logEventV2/index.ts
  packages/destination-actions/src/destinations/amplitude/logPurchase/index.ts
Labels: team:segment-core, mode:cloud

#2965 [Linkedin Conversions] Bump linked api version to 202505
  packages/destination-actions/src/destinations/linkedin-conversions/constants.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2991 registering google-data-manager
  packages/destination-actions/src/destinations/google-data-manager/ingest/index.ts
  packages/destination-actions/src/destinations/google-data-manager/remove/index.ts
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2994 Add docs for batch_keys and other advanced batching configuration
  README.md
Labels: team:segment-core

#2996 [Google Ads] Fixes Journeys use cases with the userList action
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2998 STRATCONN-5915 - [Posthog] - new Destination
  packages/destination-actions/src/destinations/posthog/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/posthog/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/posthog/event/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/posthog/event/__tests__/index.test.ts
  packages/destination-actions/src/destinations/posthog/event/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/posthog/event/generated-types.ts
  packages/destination-actions/src/destinations/posthog/event/index.ts
  packages/destination-actions/src/destinations/posthog/generated-types.ts
  packages/destination-actions/src/destinations/posthog/identify/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/posthog/identify/__tests__/index.test.ts
  packages/destination-actions/src/destinations/posthog/identify/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/posthog/identify/generated-types.ts
  packages/destination-actions/src/destinations/posthog/identify/index.ts
  packages/destination-actions/src/destinations/posthog/index.ts
  packages/destination-actions/src/destinations/posthog/types.ts
Labels: Ready for Release, partner-eng-review (cloud), deploy:registration, team:segment-core, mode:cloud, deploy:push

#3003 STRATCONN-5938 - [Roadway AI] - New Destiantion
  packages/destination-actions/src/destinations/metronome/roadwayai/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/metronome/roadwayai/__tests__/index.test.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/generated-types.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/groupUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/groupUser/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/groupUser/generated-types.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/groupUser/index.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/identifyUser/__tests__/index.test.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/identifyUser/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/identifyUser/index.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/index.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/payload-transformer.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/request-types.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/trackEvent/__tests__/index.test.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/trackEvent/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/trackEvent/generated-types.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/trackEvent/index.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/trackPageView/__tests__/index.test.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/trackPageView/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/trackPageView/generated-types.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/trackPageView/index.ts
  packages/destination-actions/src/destinations/metronome/roadwayai/unified-fields.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2971 [Liveramp] Add bucket path mapping in liveramp S3
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/liveramp.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/generated-types.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/index.ts
  packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredS3/s3.ts
  packages/destination-actions/src/destinations/liveramp-audiences/awsClient.ts
Labels: not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2977 STRATCONN-5919 [Kafka] - Connections bug
  packages/destination-actions/src/destinations/kafka/constants.ts
  packages/destination-actions/src/destinations/kafka/depends-on.ts
  packages/destination-actions/src/destinations/kafka/index.ts
  packages/destination-actions/src/destinations/kafka/send/__tests__/index.test.ts
  packages/destination-actions/src/destinations/kafka/send/index.ts
  packages/destination-actions/src/destinations/kafka/types.ts
  packages/destination-actions/src/destinations/kafka/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#3000 [warehouse-destinations] Fix getDefinitions method to require from dist folder
  packages/warehouse-destinations/src/destinations/index.ts
Labels: not-partner-eng-review (cloud), team:segment-core

#3012 STRATCONN-5915 - [Posthog] - Bugfix
  packages/destination-actions/src/destinations/posthog/generated-types.ts
  packages/destination-actions/src/destinations/posthog/index.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2988 [STRATCONN-5882] - Enable gating based on patch code coverage
  codecov.yml
Labels: not-partner-eng-review (cloud), team:segment-core

#2947 STRATCONN-5849 - braze_api_campaign
  packages/destination-actions/src/destinations/braze/index.ts
  packages/destination-actions/src/destinations/braze/triggerCampaign/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/braze/triggerCampaign/__tests__/dynamic-field-functions.test.ts
  packages/destination-actions/src/destinations/braze/triggerCampaign/__tests__/index.test.ts
  packages/destination-actions/src/destinations/braze/triggerCampaign/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/braze/triggerCampaign/functions/dynamic-field-functions.ts
  packages/destination-actions/src/destinations/braze/triggerCampaign/generated-types.ts
  packages/destination-actions/src/destinations/braze/triggerCampaign/index.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#2930 Add upsertCatalogItem action for braze cloud
  packages/destination-actions/src/destinations/braze/index.ts
  packages/destination-actions/src/destinations/braze/upsertCatalogItem/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/braze/upsertCatalogItem/__tests__/index.test.ts
  packages/destination-actions/src/destinations/braze/upsertCatalogItem/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/braze/upsertCatalogItem/generated-types.ts
  packages/destination-actions/src/destinations/braze/upsertCatalogItem/index.ts
  packages/destination-actions/src/destinations/braze/upsertCatalogItem/types.ts
  packages/destination-actions/src/destinations/braze/upsertCatalogItem/utils.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push

#3026 [Amazon CAPI] - adjusting timeout
  packages/destination-actions/src/destinations/amazon-conversions-api/index.ts
  packages/destination-actions/src/destinations/amazon-conversions-api/trackConversion/utils.ts
Labels: Ready for Release, partner-eng-review (cloud), team:segment-core, mode:cloud

#3025 Handle non braze error types
  packages/destination-actions/src/destinations/braze/upsertCatalogItem/utils.ts
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core, mode:cloud

#3020 STRATCONN-5333 - support email identify braze
  packages/destination-actions/src/destinations/braze/identifyUser2/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/braze/identifyUser2/__tests__/index.test.ts
  packages/destination-actions/src/destinations/braze/identifyUser2/__tests__/snapshot.test.ts
  packages/destination-actions/src/destinations/braze/identifyUser2/generated-types.ts
  packages/destination-actions/src/destinations/braze/identifyUser2/index.ts
Labels: not-partner-eng-review (cloud), team:segment-core, mode:cloud, deploy:push
