Repository segmentio/action-destinations, pull requests merged in 2025-02, with the labels that each got.

#2704 STRAT-5398 | Klaviyo(Actions) |Allow user to configure event name and product event name in OrderCompleted Action.
  packages/destination-actions/src/destinations/klaviyo/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/__snapshots__/snapshot.test.ts.snap
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/__tests__/index.test.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/orderCompleted/index.ts
Labels: Ready for Release, mode:cloud, deploy:push, team:segment

#2710 [STRATCONN-5449] Update GEC - userList action to common hashed function
  packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/functions.test.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#2712 [STRATCONN-5445] - Fixes process consent casing in DV360 Actions
  packages/destination-actions/src/destinations/display-video-360/__tests__/shared.test.ts
  packages/destination-actions/src/destinations/display-video-360/proto/protofile.ts
  packages/destination-actions/src/destinations/display-video-360/shared.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#2722 Remove `abort-controller package` in favor of built-in AbortController
  packages/core/package.json
  packages/core/src/__tests__/request-client.test.ts
  packages/core/src/request-client.ts
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/amazon-amc/syncAudiencesToDSP/__tests__/index.test.ts
  packages/destination-actions/src/destinations/hubspot/upsertContact/__tests__/__snapshots__/index.test.ts.snap
  packages/destination-actions/src/destinations/hubspot/upsertContact/__tests__/index.test.ts
  yarn.lock
Labels: Ready for Release, team:segment-core, mode:cloud, actions:core

#2720 Upgrade Facebook Conversion API from v20 to v21
  packages/destination-actions/src/destinations/facebook-conversions-api/constants.ts
Labels: mode:cloud, team:segment

#2725 Fix typescript issues in Destinations and CLI
  packages/cli/src/commands/generate/action.ts
  packages/cli/src/commands/init.ts
  packages/destination-actions/src/destinations/display-video-360/shared.ts
  packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
  packages/destination-actions/src/destinations/optimizely-feature-experimentation-actions/trackEvent/functions.ts
Labels: team:segment-core, mode:cloud

#2719 [Salesforce] Adds logging for closing bulk jobs
  packages/destination-actions/src/destinations/salesforce/account/index.ts
  packages/destination-actions/src/destinations/salesforce/account2/index.ts
  packages/destination-actions/src/destinations/salesforce/cases/index.ts
  packages/destination-actions/src/destinations/salesforce/cases2/index.ts
  packages/destination-actions/src/destinations/salesforce/contact/index.ts
  packages/destination-actions/src/destinations/salesforce/contact2/index.ts
  packages/destination-actions/src/destinations/salesforce/customObject/index.ts
  packages/destination-actions/src/destinations/salesforce/customObject2/index.ts
  packages/destination-actions/src/destinations/salesforce/lead/index.ts
  packages/destination-actions/src/destinations/salesforce/lead2/index.ts
  packages/destination-actions/src/destinations/salesforce/opportunity/index.ts
  packages/destination-actions/src/destinations/salesforce/opportunity2/index.ts
  packages/destination-actions/src/destinations/salesforce/sf-operations.ts
Labels: team:segment-core, mode:cloud

#2732 Dynamic field queries
  packages/cli/src/lib/server.ts
  packages/core/src/destination-kit/types.ts
Labels: team:segment-core, actions:core

#2735 Update unit tests exposing URLSearchParams
  packages/destination-actions/src/destinations/amplitude/__tests__/amplitude.test.ts
  packages/destination-actions/src/destinations/twilio/__tests__/twilio.test.ts
Labels: team:segment-core, mode:cloud

#2727 [STRATCONN-5484] Add new field to send raw user_agent
  packages/destination-actions/src/destinations/amplitude/identifyUser/generated-types.ts
  packages/destination-actions/src/destinations/amplitude/identifyUser/index.ts
  packages/destination-actions/src/destinations/amplitude/logEvent/generated-types.ts
  packages/destination-actions/src/destinations/amplitude/logEvent/index.ts
  packages/destination-actions/src/destinations/amplitude/logEventV2/generated-types.ts
  packages/destination-actions/src/destinations/amplitude/logEventV2/index.ts
  packages/destination-actions/src/destinations/amplitude/logPurchase/generated-types.ts
  packages/destination-actions/src/destinations/amplitude/logPurchase/index.ts
Labels: Ready for Release, team:segment-core, mode:cloud, deploy:push

#2676 Adding extra match fields according to LinkedIn Specification.
  packages/destination-actions/src/destinations/linkedin-audiences/api/index.ts
  packages/destination-actions/src/destinations/linkedin-audiences/index.ts
  packages/destination-actions/src/destinations/linkedin-audiences/types.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2738 Upgrade Github Actions Runner to Ubuntu 22.02 and actions/cache to v3
  .github/workflows/ci.yml
  .github/workflows/ext.yml
  .github/workflows/label-prs.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish.yml
  .github/workflows/required-field-check.yml
Labels: team:segment-core

#2737 Upgrade linter and fix linting issues
  .eslintrc.js
  package.json
  packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
  packages/actions-shared/src/friendbuy/util.ts
  packages/browser-destinations/destinations/friendbuy/src/trackCustomEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/friendbuy/src/trackCustomer/__tests__/index.test.ts
  packages/browser-destinations/destinations/friendbuy/src/trackPage/__tests__/index.test.ts
  packages/browser-destinations/destinations/friendbuy/src/trackPurchase/__tests__/index.test.ts
  packages/browser-destinations/destinations/friendbuy/src/trackSignUp/__tests__/index.test.ts
  packages/browser-destinations/destinations/wisepops/src/setCustomProperties/__tests__/index.test.ts
  packages/browser-destinations/destinations/wisepops/src/trackEvent/__tests__/index.test.ts
  packages/browser-destinations/destinations/wisepops/src/trackGoal/__tests__/index.test.ts
  packages/browser-destinations/destinations/wisepops/src/trackPage/__tests__/index.test.ts
  packages/core/src/mapping-kit/__tests__/validate.test.ts
  packages/destination-actions/src/destinations/amazon-amc/__tests__/index.test.ts
  packages/destination-actions/src/destinations/display-video-360/shared.ts
  packages/destination-actions/src/destinations/engage-messaging-sendgrid/__tests__/send-email.test.ts
  packages/destination-actions/src/destinations/pipedrive/utils.ts
  packages/destination-actions/src/destinations/salesforce/sf-operations.ts
  yarn.lock
Labels: team:segment-core, mode:cloud, actions:core, mode:device

#2740 Set Default version to v21 in Facebook Conversion API
  packages/destination-actions/src/destinations/facebook-conversions-api/constants.ts
Labels: Ready for Release, mode:cloud, team:segment

#2743 CRIT logging for actions salesforce, should show in prod
  packages/destination-actions/src/destinations/salesforce/sf-operations.ts
Labels: team:segment-core, mode:cloud

#2714 [LAB-1682] Create presets for each standard audience action destination
  packages/destination-actions/src/destinations/amazon-amc/index.ts
  packages/destination-actions/src/destinations/aws-s3/index.ts
  packages/destination-actions/src/destinations/delivrai-activate/index.ts
  packages/destination-actions/src/destinations/display-video-360/index.ts
  packages/destination-actions/src/destinations/dynamic-yield-audiences/index.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/index.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
  packages/destination-actions/src/destinations/iterable-lists/index.ts
  packages/destination-actions/src/destinations/iterable/index.ts
  packages/destination-actions/src/destinations/klaviyo/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/index.ts
  packages/destination-actions/src/destinations/reddit-audiences/index.ts
  packages/destination-actions/src/destinations/sendgrid-audiences/index.ts
  packages/destination-actions/src/destinations/snap-audiences/index.ts
  packages/destination-actions/src/destinations/taboola-actions/index.ts
  packages/destination-actions/src/destinations/tiktok-audiences/index.ts
  packages/destination-actions/src/destinations/webhook-audiences/index.ts
  packages/destination-actions/src/destinations/yahoo-audiences/index.ts
Labels: Ready for Release, mode:cloud, team:segment

#2746 [Publish] Fix linting issues in unit tests
  packages/browser-destinations/destinations/adobe-target/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/adobe-target/src/triggerView/__tests__/index.test.ts
  packages/browser-destinations/destinations/adobe-target/src/upsertProfile/__tests__/index.test.ts
  packages/browser-destinations/destinations/bucket/src/__tests__/index.test.ts
  packages/browser-destinations/destinations/bucket/src/group/__tests__/index.test.ts
  packages/browser-destinations/destinations/bucket/src/identifyUser/__tests__/index.test.ts
  packages/browser-destinations/destinations/bucket/src/trackEvent/__tests__/index.test.ts
Labels: team:segment-core, mode:device

#2733 Adding oauth2.0 to First Party DV360
  packages/destination-actions/src/destinations/first-party-dv360/_tests_/index.test.ts
  packages/destination-actions/src/destinations/first-party-dv360/functions.ts
  packages/destination-actions/src/destinations/first-party-dv360/index.ts
  packages/destination-actions/src/destinations/first-party-dv360/types.ts
Labels: team:segment-core, mode:cloud

#2750 [STRATCONN-5516] | Revert "Worked on fixing braze_id default mappings of Braze Actions."
  packages/destination-actions/src/destinations/braze/__tests__/__snapshots__/braze.test.ts.snap
  packages/destination-actions/src/destinations/braze/__tests__/braze.test.ts
  packages/destination-actions/src/destinations/braze/__tests__/multistatus.test.ts
  packages/destination-actions/src/destinations/braze/updateUserProfile/index.ts
Labels: Ready for Release, mode:cloud, team:segment

#2749 Advanced logging of payloads from Salesforce based on a feature flag
  packages/destination-actions/src/destinations/salesforce/account/index.ts
  packages/destination-actions/src/destinations/salesforce/account2/index.ts
  packages/destination-actions/src/destinations/salesforce/cases/index.ts
  packages/destination-actions/src/destinations/salesforce/cases2/index.ts
  packages/destination-actions/src/destinations/salesforce/contact/index.ts
  packages/destination-actions/src/destinations/salesforce/contact2/index.ts
  packages/destination-actions/src/destinations/salesforce/customObject/index.ts
  packages/destination-actions/src/destinations/salesforce/customObject2/index.ts
  packages/destination-actions/src/destinations/salesforce/lead/index.ts
  packages/destination-actions/src/destinations/salesforce/lead2/index.ts
  packages/destination-actions/src/destinations/salesforce/opportunity/index.ts
  packages/destination-actions/src/destinations/salesforce/opportunity2/index.ts
  packages/destination-actions/src/destinations/salesforce/sf-operations.ts
Labels: team:segment-core, mode:cloud

#2748 [Klaviyo] Upgrade to revision 2025-01-15
  packages/destination-actions/src/destinations/klaviyo/config.ts
  packages/destination-actions/src/destinations/klaviyo/functions.ts
  packages/destination-actions/src/destinations/klaviyo/subscribeProfile/index.ts
  packages/destination-actions/src/destinations/klaviyo/unsubscribeProfile/index.ts
Labels: Ready for Release, team:segment-core, mode:cloud

#2757 Upgrade size-limit package
  packages/browser-destinations/package.json
  packages/destination-subscriptions/package.json
  yarn.lock
Labels: team:segment-core, actions:core

#2754 Update Copyright to 2025
  README.md
  packages/actions-shared/README.md
  packages/ajv-human-errors/README.md
  packages/browser-destinations/README.md
  packages/browser-destinations/destinations/1flow/README.md
  packages/browser-destinations/destinations/cdpresolution/README.md
  packages/browser-destinations/destinations/contentstack-web/README.md
  packages/browser-destinations/destinations/devrev/README.md
  packages/browser-destinations/destinations/evolv-ai/README.md
  packages/browser-destinations/destinations/google-campaign-manager/README.md
  packages/browser-destinations/destinations/hubble-web/README.md
  packages/browser-destinations/destinations/jimo/README.md
  packages/browser-destinations/destinations/nextdoor-plugins/README.md
  packages/browser-destinations/destinations/pendo-web-actions/README.md
  packages/browser-destinations/destinations/reddit-plugins/README.md
  packages/browser-destinations/destinations/replaybird/README.md
  packages/browser-destinations/destinations/rupt/README.md
  packages/browser-destinations/destinations/snap-plugins/README.md
  packages/cli/README.md
  packages/cli/templates/destinations/browser/README.md
  packages/core/README.md
  packages/destination-actions/README.md
  packages/destination-subscriptions/README.md
Labels: team:segment-core, actions:core, mode:device

#2723 Simplifies type generation for hooks
  packages/cli/src/commands/generate/types.ts
  packages/core/src/destination-kit/action.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/generated-types.ts
  packages/destination-actions/src/destinations/google-enhanced-conversions/userList/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/upsertProfile/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-conversions/api/api.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/api/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/generated-types.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
  packages/destination-actions/src/destinations/marketo-static-lists/addToList/generated-types.ts
Labels: team:segment-core, mode:cloud, deploy:push, actions:core

#2756 [Smart Hashing] Add New Smart Hashing Util
  packages/core/src/index.ts
  packages/destination-actions/src/lib/hashing-utils.test.ts
  packages/destination-actions/src/lib/hashing-utils.ts
Labels: actions:core, team:segment

#2741 Fix inconsistencies between node v18 and v22
  package.json
  packages/actions-shared/package.json
  packages/browser-destinations/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/destination-kit/index.ts
  packages/destination-actions/package.json
  packages/destination-actions/src/destinations/amplitude/__tests__/amplitude.test.ts
  packages/destination-actions/src/destinations/braze/utils.ts
  packages/destination-actions/src/destinations/pushwoosh/utilities.ts
  packages/destination-actions/tsconfig.build.json
  yarn.lock
Labels: team:segment-core, mode:cloud, actions:core

#2742 [STRATCONN-5404] | Upgrade Facebook API in Facebook Custom Audience (Actions) to v21
  packages/destination-actions/src/destinations/facebook-custom-audiences/__tests__/fb-operations.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/__tests__/index.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/constants.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/fbca-operations.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/index.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/__tests__/index.test.ts
  packages/destination-actions/src/destinations/facebook-custom-audiences/sync/index.ts
Labels: Ready for Release, mode:cloud, team:segment

#2758 Expose SyncModeDefinition in actions-core to make it compatible with action-cli
  packages/core/src/index.ts
Labels: Ready for Release, team:segment-core, actions:core

#2759 [Smart Hashing] [LinkedIn Conversions] Use Smart Hashing Util for Hashing Email
  packages/destination-actions/src/destinations/linkedin-conversions/api/index.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/__tests__/index.test.ts
  packages/destination-actions/src/destinations/linkedin-conversions/streamConversion/index.ts
Labels: Ready for Release, not-partner-eng-review (cloud), mode:cloud, team:segment

#2763 Introduce Node v22 parallel builds in Github Actions
  .github/workflows/ci.yml
  .github/workflows/ext.yml
Labels: Ready for Release, not-partner-eng-review (cloud), team:segment-core

#2767 Weekly Deploy: Register amazon eventbridge
  packages/destination-actions/src/destinations/index.ts
Labels: team:segment-core, mode:cloud

#2764 [MAIN] [STRATCONN-5376] Klaviyo action destination sync failed issue.
  packages/destination-actions/src/destinations/klaviyo/generated-types.ts
  packages/destination-actions/src/destinations/klaviyo/index.ts
  packages/destination-actions/src/destinations/klaviyo/properties.ts
Labels: not-partner-eng-review (cloud), mode:cloud, deploy:push, team:segment

#2772 [required fields v2] Fixes an issue with schema validation in a specific case
  packages/core/src/__tests__/__snapshots__/schema-validation.test.ts.snap
  packages/core/src/__tests__/schema-validation.test.ts
  packages/core/src/destination-kit/fields-to-jsonschema.ts
Labels: team:segment-core, actions:core

#2774 Adds yarn clean-build command
  README.md
  package.json
  scripts/clean.sh
Labels: team:segment-core

#2776 Upgrade Node base version to 18.17.1
  .nvmrc
  README.md
  package.json
  packages/actions-shared/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/destination-actions/package.json
Labels: team:segment-core, actions:core
